### ISSUE TITLE
[OmniSci] core dumped when using append operation

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3045] opened 2021-05-06 09:54 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Ubuntu 20.04`
- **Modin version** (`modin.__version__`): 626446e6999fde43ff32cbee5df1b1c147d6d7b2
- **Python version**: `3.7.10`
- **Code we can use to reproduce**:
```python

from time import time

import numpy as np
from modin.pandas import DataFrame, concat

df1 = DataFrame(np.random.randint(10, size=(5000, 5000)), columns=[f"col{x}" for x in range(5000)])

start = time()
df1.append(df1)._query_compiler._modin_frame._execute()
print(f"merge time: {time()-start}")
```

### Source code / logs

```bash
FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.
UserWarning: Due to https://github.com/pandas-dev/pandas/issues/35092, Pandas ignores sort=False; Modin correctly does not sort.
2021-05-06T12:48:34.711048 E 2910542 0 DBHandler.cpp:255 This build isn't CUDA enabled, will run on CPU
2021-05-06T12:48:34.712542 E 2910542 0 Calcite.cpp:286 Appears to be orphaned Calcite server already running, shutting it down
2021-05-06T12:48:34.712685 E 2910542 0 Calcite.cpp:288 Please check that you are not trying to run two servers on same port
2021-05-06T12:48:34.712730 E 2910542 0 Calcite.cpp:289 Attempting to shutdown orphaned Calcite server
2021-05-06T12:48:34.721821 E 2910542 0 Calcite.cpp:294 orphaned Calcite server shutdown
Thrift: Thu May  6 12:48:34 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Thu May  6 12:48:35 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Thu May  6 12:48:35 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Thu May  6 12:48:35 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
2021-05-06T12:49:00.957369 F 2910542 1 RelAlgExecutor.cpp:1035 Check failed: it_ok.second
Aborted (core dumped)

```

**Comment by ienkovich** [comment] 2021-05-07 16:03
This seems to be related to intel-ai/omniscidb#158. In this test, two operands of the `UNION ALL` operation refer to the same node. In our serializer, we generate two separate scan nodes, but Calcite merges them and we trigger the bug in the OmniSci server. With `MODIN_USE_CALCITE=False` test passes.

**Comment by AndreyPavlenko** [comment] 2022-09-21 18:45
Closing as not reproducible. If you could reproduce the issue, please reopen.

**Closed by AndreyPavlenko** 2022-09-21 18:45 UTC
Labels: bug 🦗, OmniSci
