### ISSUE TITLE
Modin failed during adding a new column via `DataFrame.loc[mask, "new_column"]`

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#4219] opened 2022-02-17 12:56 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): https://github.com/modin-project/modin/commit/b7027597985a442734a57949d72e3fa0625b4d43
- **Python version**: 3.8.11
- **Code we can use to reproduce**:

```python
# import pandas as pd
import modin.pandas as pd

df = pd.DataFrame({"A": [0,1,2,3,4]})
df2 = pd.DataFrame({"A": ["a", "b", "c", "d", "e"]})

mask = pd.Series([True, False, False, True, True])

df.loc[mask, "A_new"] = df2.loc[mask, "A"]
print(df)
```

### Describe the problem

Modin is failed during adding a new column via `DataFrame.loc[mask, "new_column"]`

### Source code / logs

Pandas output:
```bash
   A A_new
0  0     a
1  1   NaN
2  2   NaN
3  3     d
4  4     e
```

Modin output:
```bash
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    df.loc[mask, "A_new"] = df2.loc[mask, "A"]
  File "/localdisk/aprutsko/modin/modin/pandas/indexing.py", line 741, in __setitem__
    row_lookup, col_lookup = self._compute_lookup(row_loc, col_loc)
  File "/localdisk/aprutsko/modin/modin/pandas/indexing.py", line 868, in _compute_lookup
    raise KeyError(missing_labels)
KeyError: array(['A_new'], dtype='<U5')
```

**Comment by devin-petersohn** [comment] 2022-02-17 19:01
@RehanSD is this related to other work you've done?

**Comment by mvashishtha** [comment] 2022-02-22 15:01
Duplicate of https://github.com/modin-project/modin/issues/3764

**Closed by mvashishtha** 2022-02-22 15:01 UTC
Labels: bug 🦗
