### ISSUE TITLE
Throwing RayTaskError

### ISSUE THREAD

**Issue by saptarshim** [modin-project/modin#457] opened 2019-02-06 17:39 UTC
I can read the csv file easily with regular pandas but when using modin it's throwing the exception. 

---------------------------------------------------------------------------
RayTaskError                              Traceback (most recent call last)
<ipython-input-26-8b66b1d9fc59> in <module>()
      1 start = time.time()      
----> 2 data = pd.read_csv("data/train_feature_10000000.csv")
      3 stop = time.time()

~/projects/modin/modin/pandas/io.py in parser_func(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
     93     ):
     94         _, _, _, kwargs = inspect.getargvalues(inspect.currentframe())
---> 95         return _read(**kwargs)
     96 
     97     return parser_func

~/projects/modin/modin/pandas/io.py in _read(**kwargs)
    106         kwargs: Keyword arguments in pandas.read_csv
    107     """
--> 108     pd_obj = BaseFactory.read_csv(**kwargs)
    109     # This happens when `read_csv` returns a TextFileReader object for iterating through
    110     if isinstance(pd_obj, pandas.io.parsers.TextFileReader):

~/projects/modin/modin/data_management/factories.py in read_csv(cls, **kwargs)
     53     @classmethod
     54     def read_csv(cls, **kwargs):
---> 55         return cls._determine_engine()._read_csv(**kwargs)
     56 
     57     @classmethod

~/projects/modin/modin/data_management/factories.py in _read_csv(cls, **kwargs)
     57     @classmethod
     58     def _read_csv(cls, **kwargs):
---> 59         return cls.io_cls.read_csv(**kwargs)
     60 
     61     @classmethod

~/projects/modin/modin/engines/ray/pandas_on_ray/io.py in read_csv(cls, filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    335             "float_precision": float_precision,
    336         }
--> 337         return cls._read(**kwargs)
    338 
    339     @classmethod

~/projects/modin/modin/engines/ray/pandas_on_ray/io.py in _read(cls, filepath_or_buffer, **kwargs)
    405         else:
    406             return cls._read_csv_from_file_pandas_on_ray(
--> 407                 filepath_or_buffer, filtered_kwargs
    408             )
    409 

~/projects/modin/modin/engines/ray/pandas_on_ray/io.py in _read_csv_from_file_pandas_on_ray(cls, filepath, kwargs)
    200         index_col = kwargs.get("index_col", None)
    201         if index_col is None:
--> 202             new_index = pandas.RangeIndex(sum(ray.get(index_ids)))
    203         else:
    204             new_index_ids = get_index.remote([empty_pd_df.index.name], *index_ids)

~/anaconda3/lib/python3.6/site-packages/ray/worker.py in get(object_ids, worker)
   2200                 if isinstance(value, RayTaskError):
   2201                     last_task_error_raise_time = time.time()
-> 2202                     raise value
   2203             return values
   2204         else:

RayTaskError: ray_worker (pid=9109, host=sm-ws)
  File "/home/saptarshi/projects/modin/modin/engines/ray/pandas_on_ray/io.py", line 583, in _read_csv_with_offset_pandas_on_ray
    pandas_df = pandas.read_csv(BytesIO(to_read), **kwargs)
  File "/home/saptarshi/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/saptarshi/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/home/saptarshi/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/home/saptarshi/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1848, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 876, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 891, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 945, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 932, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2112, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: EOF inside string starting at line 1219595

**Comment by devin-petersohn** [comment] 2019-02-06 17:53
Hi @saptarshim, what version of python are you running and how did you install modin? There is another issue #247 that had a similar issue and it was related to the environment. Are you running this in a container?

Also what args did you pass to `read_csv`?

**Comment by saptarshim** [comment] 2019-02-06 18:01
I am running Python 3.6.8 :: Anaconda
I didn't pass any argument. Here is the code based on the example provided. I can sen the csv file if that helps. I tried with other CSV files and it seems to work but not on this one.

start = time.time()
data = pd.read_csv("data/train_feature_10000000.csv")
stop = time.time()

**Comment by devin-petersohn** [comment] 2019-02-06 18:09
Does it work if you run it in [out of core](https://modin.readthedocs.io/en/latest/out_of_core.html) mode? Note this is an experimental mode and will likely be slower.

```bash
MODIN_OUT_OF_CORE=true ipython # or python
```

If you can send the CSV that would be great. A link or attachment to bug_reports@modin.org would help a lot. Thanks!

**Comment by saptarshim** [comment] 2019-02-07 16:53
Hi,
      I tried but out of core didn't work as far as I can tell. The CSV file is 7.2GB not sure how to send it.
Thanks.

**Comment by devin-petersohn** [comment] 2019-02-07 17:23
@saptarshim If you can send the first 1000 or so lines, I can just create a test dataset that is around that size. We do run stress tests on files even larger than this (see results [here](https://rise.cs.berkeley.edu/blog/modin-pandas-on-ray-october-2018/)), but those tests are usually run on a larger machine (At least 32GB of memory).

How much memory does the system that you're running on have? Out of core would alleviate memory issues if that is the cause. 

Is there more to the stack trace? Feel free to paste as much of the output as there is, even if there are duplicate messages. Sometimes the cause of these issues is buried in the traceback.

**Comment by devin-petersohn** [comment] 2020-06-01 14:46
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.

**Closed by devin-petersohn** 2020-06-01 14:46 UTC
Labels: Memory :floppy_disk:
