### ISSUE TITLE
Improve sort_values

### ISSUE THREAD

**Issue by williamma12** [modin-project/modin#158] opened 2018-10-12 04:51 UTC
### Describe the problem
Currently `sort_values` sorts the values and updates the index/columns based off of the sorted values. We'd like to create a more efficient way of sorting and preferably something that actually parallelizes the work.

**Comment by eavidan** [comment] 2018-12-09 16:11
hey,
I would like to take this one
Any thought on how we would like to implement this, considering we have both rows and columns partitioned?

**Comment by devin-petersohn** [comment] 2018-12-10 16:54
Hey @eavidan thanks for taking up the issue!

For the first pass, I think we can just try to avoid the collecting of the data and broadcasting of the results. If you take a look at (https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L3753), we are collecting the values before sorting, then broadcasting out. 

A better way to do this would be to bin the values and sort within those bins. To choose the edges of the bins, it should be possible to do a sampling of the data within the column(s) selected.

**Comment by eavidan** [comment] 2018-12-12 16:59
Hey @devin-petersohn 
I agree that the first option would make this operation into a scalable one, but will not benefit performance. If I am not mistaken, sorting would probably get slower

I was thinking about a simple merge sort, but the partitioning across columns make it a bit harder.
I started using the map_partition function in order to sort each partition.
could you point me to some helper functions that may assist me in achieving this?
or am I complicating/simplifying things?

**Comment by devin-petersohn** [comment] 2018-12-12 17:24
Good point, Ray has had a lot of success with a distributed merge-sort. I have also been prototyping a distributed Series, which could help with this. 

The challenge with `sort_values` is that you can pass in a list of columns in order to break ties. e.g.

```python
df.sort_values(["year", "month", "day", "hour", "minute"])
```

This would be valid if year, month, day, hour, and minute were all columns. In this case, working directly on the `block_partitions` would be challenging because there may require communication between different blocks in the same row to break ties. Currently, because we collect the values and convert to pandas for simplified implementation, we could end up materializing a majority of the table just to do the sort.

We do have abstractions for treating the data as if it were partitioned only along columns or only along rows. There are some internal APIs ([`BaseBlockPartitions.map_across_full_axis`](https://github.com/modin-project/modin/blob/master/modin/engines/base/block_partitions.py#L255)) that allow this (they work on the [`AxisPartition` objects](https://github.com/modin-project/modin/blob/master/modin/engines/base/axis_partition.py). 

There is also a [manual shuffle method](https://github.com/modin-project/modin/blob/master/modin/engines/base/block_partitions.py#L927) (it is not yet used or tested anywhere that I am aware), which might be useful as well. Additionally, one option is to just implement what you want in Ray and then we can port the code into Modin and create the necessary abstractions. This might be easiest in this case if the abstractions are not sufficient.

Let me know if you need any other pointers to the internal API. Thanks!

**Comment by devin-petersohn** [comment] 2018-12-17 18:19
Thanks @eavidan! I should be able to get to this tomorrow. At a glance, it looks pretty good. We should be able to abstract out the core logic and fit it into Modin. Thanks again!

**Comment by gshimansky** [comment] 2021-01-22 20:09
I took a look at the current version of `sort_values` test and I see that we don't test for
1. `ignore_index` parameter (it appeared in Pandas 1.0.0, so it is probably too new).
2. List of booleans in `ascending` parameter.
3. `kind` parameter (just in case).
4. More than 2 columns in `by`.
5. MultiIndex levels in `by`.
6. `key` parameter (another new parameter since Pandas 1.1.0).

I want to start with improving the test so that it would cover all possible parameters.

**Comment by gshimansky** [comment] 2021-01-29 20:38
I have a question about distributed sort implementation. In my understanding there should be five parts of operation (so simplicity I write about case with `axis=0`)
1. `reset_index` index in partitions with `RangeIndex` to avoid problems with duplicates in dataframe index and creating another column(s) in dataframe to shuffle index contents together with data. This should also allow sorting levels of MultiIndex if they are specified in `by`.
2. Call `sort_values` to sort data in individual partitions. If columns specified in `by` happen to be distributed into different partition columns, this should be done across axis, otherwise we can perform this operation only on the affected partitions column.
3. Build new index for rows from different partitions sequentially comparing them. This may be complicated in case of array specified in `ascending` parameter.
4. Call `reindex` like we do now to reshuffle rows according to new order.
5. Restore index from index column(s) if `ignore_index` is `False`.

What do you think? My question is, is our `reindex` implementation efficient enough to be used here, or should I think of something else?

**Comment by mvashishtha** [comment] 2022-08-17 15:10
I'm marking this as a duplicate of #3535. If we want to improve `sort_values` perf more, we can open a separate issue.

**Comment by mvashishtha** [comment] 2022-08-17 15:10
Duplicate of #3535

**Closed by mvashishtha** 2022-08-17 15:10 UTC
Labels: good first issue 🔰, Performance 🚀
