### ISSUE TITLE
df.sort_values error ValueError: cannot reindex on an axis with duplicate labels

### ISSUE THREAD

**Issue by xiaogangzhu** [modin-project/modin#4676] opened 2022-07-15 04:26 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **Modin version** (`modin.__version__`): 0.15.2
- **Python version**: 3.8
- **Code we can use to reproduce**:

### Describe the problem

after concat two df, I want to use df.sort_values() but it produces following error, which when I use pandas there is no error.
### Source code / logs

when I use it produce error
`pd.concat([df_proc, last_row_yesterday_copy]).sort_values(by=['msgtime', 'vin'])`

`Traceback (most recent call last):
  File "main.py", line 19, in <module>
    result,last_row_today,bad_vin_list = run_model(data,last_row_yesterday,today)
  File "/home/tstone10/PycharmProjects/isolation_resis/isolation_model.py", line 247, in run_model
    last_row_today = generate_last_row_today(df_proc,last_row_yesterday)
  File "/home/tstone10/PycharmProjects/isolation_resis/isolation_model.py", line 208, in generate_last_row_today
    last_row_today = pd.concat([last_row_today,last_row_yesterday]).sort_values(by='msgtime')
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/logging/logger_metaclass.py", line 68, in log_wrap
    return method(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/pandas/base.py", line 2889, in sort_values
    result = self._query_compiler.sort_rows_by_column_values(
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/logging/logger_metaclass.py", line 68, in log_wrap
    return method(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/storage_formats/pandas/query_compiler.py", line 3104, in sort_rows_by_column_values
    result = self.reset_index(drop=True).reindex(axis=0, labels=new_index2)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/logging/logger_metaclass.py", line 68, in log_wrap
    return method(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/storage_formats/pandas/query_compiler.py", line 516, in reindex
    new_modin_frame = self._modin_frame.apply_full_axis(
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/logging/logger_metaclass.py", line 68, in log_wrap
    return method(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 115, in run_f_on_minimally_updated_metadata
    result = f(self, *args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 1906, in apply_full_axis
    return self.broadcast_apply_full_axis(
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/logging/logger_metaclass.py", line 68, in log_wrap
    return method(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 115, in run_f_on_minimally_updated_metadata
    result = f(self, *args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 2352, in broadcast_apply_full_axis
    result = self.__constructor__(
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/logging/logger_metaclass.py", line 68, in log_wrap
    return method(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 222, in __init__
    self._filter_empties()
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/logging/logger_metaclass.py", line 68, in log_wrap
    return method(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 442, in _filter_empties
    [
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 449, in <listcomp>
    if i < len(self._row_lengths) and self._row_lengths[i] != 0
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 236, in _row_lengths
    self._row_lengths_cache = [
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 237, in <listcomp>
    obj.length() for obj in self._partitions.T[0]
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py", line 289, in length
    self._length_cache = ray.get(self._length_cache)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::deploy_ray_func() (pid=537977, ip=19.244.16.99)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 532, in deploy_ray_func
    result = func(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 162, in deploy_axis_func
    result = func(dataframe, *kwargs.pop("args", ()), **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 1393, in _tree_reduce_func
    series_result = func(df, *args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/modin/core/storage_formats/pandas/query_compiler.py", line 518, in <lambda>
    lambda df: df.reindex(labels=labels, axis=axis, **kwargs),
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/pandas/util/_decorators.py", line 324, in wrapper
    return func(*args, **kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/pandas/core/frame.py", line 4804, in reindex
    return super().reindex(**kwargs)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/pandas/core/generic.py", line 4966, in reindex
    return self._reindex_axes(
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/pandas/core/frame.py", line 4623, in _reindex_axes
    frame = frame._reindex_index(
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/pandas/core/frame.py", line 4642, in _reindex_index
    return self._reindex_with_indexers(
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/pandas/core/generic.py", line 5032, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 679, in reindex_indexer
    self.axes[axis]._validate_can_reindex(indexer)
  File "/home/tstone10/anaconda3/envs/tf/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4107, in _validate_can_reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels
`

but if I use there is no error
`pd.concat([df_proc, last_row_yesterday_copy]).drop_duplicates().sort_values(by=['msgtime', 'vin'])`

**Comment by mvashishtha** [comment] 2022-07-15 15:23
@xiaogangzhu thank you for reporting this bug! I have the following reproducer on my mac (specs below):

```python
import modin.pandas as pd

df_small = pd.DataFrame(list(range(1000)))
df = pd.concat([df_small] * 3)
df.sort_values(by=0)
```

The script works in pandas, but in modin I get a stack trace like the one you gave:

<details>

<summary>Stack trace</summary>

```
---------------------------------------------------------------------------
RayTaskError(ValueError)                  Traceback (most recent call last)
Input In [1], in <cell line: 5>()
      3 df_small = pd.DataFrame(list(range(1000)))
      4 df = pd.concat([df_small] * 3)
----> 5 df.sort_values(by=0)

File ~/software_sources/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/software_sources/modin/modin/pandas/base.py:2850, in BasePandasDataset.sort_values(self, by, axis, ascending, inplace, kind, na_position, ignore_index, key)
   2848 ascending = validate_ascending(ascending)
   2849 if axis == 0:
-> 2850     result = self._query_compiler.sort_rows_by_column_values(
   2851         by,
   2852         ascending=ascending,
   2853         kind=kind,
   2854         na_position=na_position,
   2855         ignore_index=ignore_index,
   2856         key=key,
   2857     )
   2858 else:
   2859     result = self._query_compiler.sort_columns_by_row_values(
   2860         by,
   2861         ascending=ascending,
   (...)
   2865         key=key,
   2866     )

File ~/software_sources/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/software_sources/modin/modin/core/storage_formats/pandas/query_compiler.py:3185, in PandasQueryCompiler.sort_rows_by_column_values(self, columns, ascending, **kwargs)
   3180 # Index without duplicates
   3181 new_index2 = broadcast_values2.sort_values(
   3182     by=columns, axis=0, ascending=ascending, **kwargs
   3183 ).index
-> 3185 result = self.reset_index(drop=True).reindex(axis=0, labels=new_index2)
   3186 if ignore_index:
   3187     result = result.reset_index(drop=True)

File ~/software_sources/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/software_sources/modin/modin/core/storage_formats/pandas/query_compiler.py:517, in PandasQueryCompiler.reindex(self, axis, labels, **kwargs)
    515 new_index = self.index if axis else labels
    516 new_columns = labels if axis else self.columns
--> 517 new_modin_frame = self._modin_frame.apply_full_axis(
    518     axis,
    519     lambda df: df.reindex(labels=labels, axis=axis, **kwargs),
    520     new_index=new_index,
    521     new_columns=new_columns,
    522 )
    523 return self.__constructor__(new_modin_frame)

File ~/software_sources/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:115, in lazy_metadata_decorator.<locals>.decorator.<locals>.run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    113     elif apply_axis == "rows":
    114         obj._propagate_index_objs(axis=0)
--> 115 result = f(self, *args, **kwargs)
    116 if apply_axis is None and not transpose:
    117     result._deferred_index = self._deferred_index

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:1906, in PandasDataframe.apply_full_axis(self, axis, func, new_index, new_columns, dtypes)
   1868 @lazy_metadata_decorator(apply_axis="both")
   1869 def apply_full_axis(
   1870     self,
   (...)
   1875     dtypes=None,
   1876 ):
   1877     """
   1878     Perform a function across an entire axis.
   1879
   (...)
   1904     The data shape may change as a result of the function.
   1905     """
-> 1906     return self.broadcast_apply_full_axis(
   1907         axis=axis,
   1908         func=func,
   1909         new_index=new_index,
   1910         new_columns=new_columns,
   1911         dtypes=dtypes,
   1912         other=None,
   1913     )

File ~/software_sources/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:115, in lazy_metadata_decorator.<locals>.decorator.<locals>.run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    113     elif apply_axis == "rows":
    114         obj._propagate_index_objs(axis=0)
--> 115 result = f(self, *args, **kwargs)
    116 if apply_axis is None and not transpose:
    117     result._deferred_index = self._deferred_index

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:2352, in PandasDataframe.broadcast_apply_full_axis(self, axis, func, other, new_index, new_columns, apply_indices, enumerate_partitions, dtypes)
   2348 elif dtypes is not None:
   2349     dtypes = pandas.Series(
   2350         [np.dtype(dtypes)] * len(new_axes[1]), index=new_axes[1]
   2351     )
-> 2352 result = self.__constructor__(
   2353     new_partitions,
   2354     *new_axes,
   2355     None,
   2356     None,
   2357     dtypes,
   2358 )
   2359 if new_index is not None:
   2360     result.synchronize_labels(axis=0)

File ~/software_sources/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:222, in PandasDataframe.__init__(self, partitions, index, columns, row_lengths, column_widths, dtypes)
    220 self._column_widths_cache = column_widths
    221 self._dtypes = dtypes
--> 222 self._filter_empties()

File ~/software_sources/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:442, in PandasDataframe._filter_empties(self)
    435 if len(self.axes[0]) == 0 or len(self.axes[1]) == 0:
    436     # This is the case for an empty frame. We don't want to completely remove
    437     # all metadata and partitions so for the moment, we won't prune if the frame
    438     # is empty.
    439     # TODO: Handle empty dataframes better
    440     return
    441 self._partitions = np.array(
--> 442     [
    443         [
    444             self._partitions[i][j]
    445             for j in range(len(self._partitions[i]))
    446             if j < len(self._column_widths) and self._column_widths[j] != 0
    447         ]
    448         for i in range(len(self._partitions))
    449         if i < len(self._row_lengths) and self._row_lengths[i] != 0
    450     ]
    451 )
    452 self._column_widths_cache = [w for w in self._column_widths if w != 0]
    453 self._row_lengths_cache = [r for r in self._row_lengths if r != 0]

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:449, in <listcomp>(.0)
    435 if len(self.axes[0]) == 0 or len(self.axes[1]) == 0:
    436     # This is the case for an empty frame. We don't want to completely remove
    437     # all metadata and partitions so for the moment, we won't prune if the frame
    438     # is empty.
    439     # TODO: Handle empty dataframes better
    440     return
    441 self._partitions = np.array(
    442     [
    443         [
    444             self._partitions[i][j]
    445             for j in range(len(self._partitions[i]))
    446             if j < len(self._column_widths) and self._column_widths[j] != 0
    447         ]
    448         for i in range(len(self._partitions))
--> 449         if i < len(self._row_lengths) and self._row_lengths[i] != 0
    450     ]
    451 )
    452 self._column_widths_cache = [w for w in self._column_widths if w != 0]
    453 self._row_lengths_cache = [r for r in self._row_lengths if r != 0]

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:236, in PandasDataframe._row_lengths(self)
    234 if self._row_lengths_cache is None:
    235     if len(self._partitions.T) > 0:
--> 236         self._row_lengths_cache = [
    237             obj.length() for obj in self._partitions.T[0]
    238         ]
    239     else:
    240         self._row_lengths_cache = []

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:237, in <listcomp>(.0)
    234 if self._row_lengths_cache is None:
    235     if len(self._partitions.T) > 0:
    236         self._row_lengths_cache = [
--> 237             obj.length() for obj in self._partitions.T[0]
    238         ]
    239     else:
    240         self._row_lengths_cache = []

File ~/software_sources/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py:289, in PandasOnRayDataframePartition.length(self)
    285         self._length_cache, self._width_cache = _get_index_and_columns.remote(
    286             self._data
    287         )
    288 if isinstance(self._length_cache, ObjectIDType):
--> 289     self._length_cache = ray.get(self._length_cache)
    290 return self._length_cache

File ~/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/ray/worker.py:1831, in get(object_refs, timeout)
   1829     worker.core_worker.dump_object_store_memory_usage()
   1830 if isinstance(value, RayTaskError):
-> 1831     raise value.as_instanceof_cause()
   1832 else:
   1833     raise value

RayTaskError(ValueError): ray::deploy_ray_func() (pid=49016, ip=127.0.0.1)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 533, in deploy_ray_func
    result = func(*args, **kwargs)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 162, in deploy_axis_func
    result = func(dataframe, *kwargs.pop("args", ()), **kwargs)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py", line 1393, in _tree_reduce_func
    series_result = func(df, *args, **kwargs)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/storage_formats/pandas/query_compiler.py", line 519, in <lambda>
    lambda df: df.reindex(labels=labels, axis=axis, **kwargs),
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/pandas/util/_decorators.py", line 324, in wrapper
    return func(*args, **kwargs)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/pandas/core/frame.py", line 4804, in reindex
    return super().reindex(**kwargs)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/pandas/core/generic.py", line 4966, in reindex
    return self._reindex_axes(
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/pandas/core/frame.py", line 4623, in _reindex_axes
    frame = frame._reindex_index(
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/pandas/core/frame.py", line 4642, in _reindex_index
    return self._reindex_with_indexers(
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/pandas/core/generic.py", line 5032, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 679, in reindex_indexer
    self.axes[axis]._validate_can_reindex(indexer)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 4107, in _validate_can_reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels
```

</details>

**Internal details**

The breaking line from the query compiler is: https://github.com/modin-project/modin/blob/5af9832d7fad3d17f05d63908bc377e61542d953/modin/core/storage_formats/pandas/query_compiler.py#L3185

But after `reset_index(drop=True)`, the index should be a unique `RangeIndex` from 0 to the number of rows. The virtual partitions (created after [rebalancing partitions](https://github.com/modin-project/modin/blob/5af9832d7fad3d17f05d63908bc377e61542d953/modin/core/dataframe/pandas/partitioning/partition_manager.py#L1297) after the concat) aren't propagating the `reset_index` correctly before the `reindex `. This seems to be a bug with virtual partitions only because non-virtual partitions can handle the sort correctly:

```python
import modin.pandas as pd

df = pd.DataFrame(list(range(1000)) * 3)
df.sort_values(by=0)
```

**System Information**
- Modin: 5af9832d7fad3d17f05d63908bc377e61542d953
- Python: 3.10.4
- macOS Monterey 12.4

**Comment by xiaogangzhu** [comment] 2022-07-18 06:01
Is it going to fix?

**Comment by mvashishtha** [comment] 2022-07-18 22:14
@xiaogangzhu no one is working on this bug right now, but you can work around it by doing this part of your workflow in pandas, like so:

```python
modin_df = pd.concat([df_proc, last_row_yesterday_copy])
pandas_df = modin_df._to_pandas()
pandas_df_sorted = pandas_df.sort_values(by=['msgtime', 'vin'])
modin_df_sorted = pd.DataFrame(pandas_df_sorted)
```

This will unfortunately have some performance penalties because converting a Modin frame to pandas, as well as converting a pandas dataframe to Modin, take time.

Once someone is working on this bug, they will be assigned to it on this issue web page.

**Comment by xiaogangzhu** [comment] 2022-07-21 02:07
Thanks!

**Closed** 2022-08-04 20:42 UTC
Labels: bug 🦗
