### ISSUE TITLE
Is there a way to avoid slow cold start with the ray engine?

### ISSUE THREAD

**Issue by KrystofS** [modin-project/modin#5179] opened 2022-11-02 12:47 UTC
First execution of Modin with the ray engine seems very slow. My results and used code bellow.
```
from consts import csvDataSets
import pandas as pd
import modin.pandas as mpd
from modin.config import Engine
import ray
import time
from modin.config import BenchmarkMode
BenchmarkMode.put(True)

Engine.put("ray")
ray.init(runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})

start = time.time()
brvehins1_df = pd.read_csv(csvDataSets + "brvehins1.csv")
end = time.time()
print(f'Pandas execution time: {end - start}')

for _ in range(5):
    start = time.time()
    brvehins1_df = mpd.read_csv(csvDataSets + "brvehins1.csv")
    end = time.time()
    print(f'Modin execution time: {end - start}')
```

The output:
```
Pandas execution time: 3.890420436859131
Modin execution time: 5.389143705368042
Modin execution time: 1.5507605075836182
Modin execution time: 1.4909210205078125
Modin execution time: 1.5514976978302002
Modin execution time: 1.5203297138214111
```
The csv is around 300 MB. My machine has i7-1165G7 with 32 GB of RAM. So neither is particularly extreme or specific in any way.

Is there any elegant way to avoid cold start short of just executing something?

**Comment by mvashishtha** [comment] 2022-11-02 17:11
@KrystofS thank you for reporting this issue. Unfortunately I don't know any good solutions for cold start with ray. It seems the first time each ray worker runs something, it will pay a startup cost. I'm going to mark this issue as a duplicate of #5157, a recent issue that describes nearly the same problem. Please follow that issue for updates.

**Comment by mvashishtha** [comment] 2022-11-02 17:11
Duplicate of #5157

**Closed by mvashishtha** 2022-11-02 17:11 UTC
Labels: question ❓, Triage 🩹
