### ISSUE TITLE
 self._query_compiler.columns RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by deepalib-cuelogic** [modin-project/modin#1706] opened 2020-07-10 16:39 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

**Comment by devin-petersohn** [comment] 2020-07-10 23:11
Hi @deepalib-cuelogic thanks for posting!

We need more information to reproduce and fix this issue. Can you share the code that produced this error? Thanks!

**Comment by pyrito** [comment] 2022-08-18 21:57
Closing due to lack of information/reproducer.

**Closed by pyrito** 2022-08-18 21:57 UTC
Labels: Needs more information ❔
