### ISSUE TITLE
set_index InvalidIndexError

### ISSUE THREAD

**Issue by mrweijianli** [modin-project/modin#4254] opened 2022-02-22 21:49 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Big Sur
- **Modin version** (`modin.__version__`): 0.13.2
- **Python version**: Python 3.9.7
- **Code we can use to reproduce**: 

### Describe the problem

When I tried to set_index of multiple columns, the following error appeared:
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

### Source code / logs

After some experiments, I think it's the following combination of code that caused the error:
```
data1 = data1.reset_index(level=[0])
data1 = data1.set_index(['ric', 'source', 'date'])
```
The data1 in the first line has a MultiIndex of 2 levels. The first level is a datetime64[ns], named, "date", and the second is int64.
The column 'ric' is string, 'source' is string and 'date' comes the the reset_index.

Traceback:
```
(deploy_ray_func pid=10725) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10734) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10724) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10729) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10722) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10730) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10735) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10727) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10723) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10732) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10720) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10731) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10726) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10728) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10721) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
(deploy_ray_func pid=10733) RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
---------------------------------------------------------------------------
RayTaskError(InvalidIndexError)           Traceback (most recent call last)
Input In [8], in <module>
----> 1 dc.compare_diff_ratio_for_all_rics()

Input In [6], in DataCompare.compare_diff_ratio_for_all_rics(self)
     31 data2['source'] = '2'
     32 data1 = data1.reset_index(level=[0])
---> 34 data1 = data1.set_index(['ric', 'source', 'date'])
     35 data2 = data2.reset_index()
     36 data2 = data2.set_index(['ric', 'source', 'date'])

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/pandas/dataframe.py:1951, in DataFrame.set_index(self, keys, drop, append, inplace, verify_integrity)
   1949     else:
   1950         return
-> 1951 new_query_compiler = self._query_compiler.set_index_from_columns(
   1952     keys, drop=drop, append=append
   1953 )
   1955 if verify_integrity and not new_query_compiler.index.is_unique:
   1956     duplicates = new_query_compiler.index[
   1957         new_query_compiler.index.duplicated()
   1958     ].unique()

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py:613, in PandasQueryCompiler.set_index_from_columns(self, keys, drop, append)
    610 def set_index_from_columns(
    611     self, keys: List[Hashable], drop: bool = True, append: bool = False
    612 ):
--> 613     new_modin_frame = self._modin_frame.to_labels(keys)
    614     if append:
    615         arrays = []

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:840, in PandasDataframe.to_labels(self, column_list)
    826 def to_labels(self, column_list: List[Hashable]) -> "PandasDataframe":
    827     """
    828     Move one or more columns into the row labels. Previous labels are dropped.
    829 
   (...)
    838         A new PandasDataframe that has the updated labels.
    839     """
--> 840     extracted_columns = self.mask(col_labels=column_list).to_pandas()
    841     if len(column_list) == 1:
    842         new_labels = pandas.Index(extracted_columns.squeeze(axis=1))

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:110, in lazy_metadata_decorator.<locals>.decorator.<locals>.run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    108     elif apply_axis == "rows":
    109         obj._propagate_index_objs(axis=0)
--> 110 result = f(self, *args, **kwargs)
    111 if apply_axis is None and not transpose:
    112     result._deferred_index = self._deferred_index

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:744, in PandasDataframe.mask(self, row_labels, row_positions, col_labels, col_positions)
    742 else:
    743     new_col_order = None
--> 744 return intermediate._reorder_labels(
    745     row_positions=new_row_order, col_positions=new_col_order
    746 )

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:110, in lazy_metadata_decorator.<locals>.decorator.<locals>.run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    108     elif apply_axis == "rows":
    109         obj._propagate_index_objs(axis=0)
--> 110 result = f(self, *args, **kwargs)
    111 if apply_axis is None and not transpose:
    112     result._deferred_index = self._deferred_index

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:884, in PandasDataframe._reorder_labels(self, row_positions, col_positions)
    882     ordered_cols = ordered_rows
    883     col_idx = self.columns
--> 884 return self.__constructor__(ordered_cols, row_idx, col_idx)

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:201, in PandasDataframe.__init__(self, partitions, index, columns, row_lengths, column_widths, dtypes)
    199 self._column_widths_cache = column_widths
    200 self._dtypes = dtypes
--> 201 self._filter_empties()

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:421, in PandasDataframe._filter_empties(self)
    414 if len(self.axes[0]) == 0 or len(self.axes[1]) == 0:
    415     # This is the case for an empty frame. We don't want to completely remove
    416     # all metadata and partitions so for the moment, we won't prune if the frame
    417     # is empty.
    418     # TODO: Handle empty dataframes better
    419     return
    420 self._partitions = np.array(
--> 421     [
    422         [
    423             self._partitions[i][j]
    424             for j in range(len(self._partitions[i]))
    425             if j < len(self._column_widths) and self._column_widths[j] != 0
    426         ]
    427         for i in range(len(self._partitions))
    428         if i < len(self._row_lengths) and self._row_lengths[i] != 0
    429     ]
    430 )
    431 self._column_widths_cache = [w for w in self._column_widths if w != 0]
    432 self._row_lengths_cache = [r for r in self._row_lengths if r != 0]

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:428, in <listcomp>(.0)
    414 if len(self.axes[0]) == 0 or len(self.axes[1]) == 0:
    415     # This is the case for an empty frame. We don't want to completely remove
    416     # all metadata and partitions so for the moment, we won't prune if the frame
    417     # is empty.
    418     # TODO: Handle empty dataframes better
    419     return
    420 self._partitions = np.array(
    421     [
    422         [
    423             self._partitions[i][j]
    424             for j in range(len(self._partitions[i]))
    425             if j < len(self._column_widths) and self._column_widths[j] != 0
    426         ]
    427         for i in range(len(self._partitions))
--> 428         if i < len(self._row_lengths) and self._row_lengths[i] != 0
    429     ]
    430 )
    431 self._column_widths_cache = [w for w in self._column_widths if w != 0]
    432 self._row_lengths_cache = [r for r in self._row_lengths if r != 0]

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:215, in PandasDataframe._row_lengths(self)
    213 if self._row_lengths_cache is None:
    214     if len(self._partitions.T) > 0:
--> 215         self._row_lengths_cache = [
    216             obj.length() for obj in self._partitions.T[0]
    217         ]
    218     else:
    219         self._row_lengths_cache = []

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:216, in <listcomp>(.0)
    213 if self._row_lengths_cache is None:
    214     if len(self._partitions.T) > 0:
    215         self._row_lengths_cache = [
--> 216             obj.length() for obj in self._partitions.T[0]
    217         ]
    218     else:
    219         self._row_lengths_cache = []

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py:295, in PandasOnRayDataframePartition.length(self)
    291         self._length_cache, self._width_cache = get_index_and_columns.remote(
    292             self.oid
    293         )
    294 if isinstance(self._length_cache, ObjectIDType):
--> 295     self._length_cache = ray.get(self._length_cache)
    296 return self._length_cache

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/opt/anaconda3/envs/py39/lib/python3.9/site-packages/ray/worker.py:1733, in get(object_refs, timeout)
   1731     worker.core_worker.dump_object_store_memory_usage()
   1732 if isinstance(value, RayTaskError):
-> 1733     raise value.as_instanceof_cause()
   1734 else:
   1735     raise value

RayTaskError(InvalidIndexError): ray::deploy_ray_func() (pid=10721, ip=127.0.0.1)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 491, in deploy_ray_func
    result = func(*args)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 159, in deploy_axis_func
    dataframe = pandas.concat(list(partitions), axis=axis, copy=False)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 359, in concat
    return op.get_result()
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 588, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
2022-02-22 14:46:10,752	ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::deploy_ray_func() (pid=10725, ip=127.0.0.1)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 491, in deploy_ray_func
    result = func(*args)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 159, in deploy_axis_func
    dataframe = pandas.concat(list(partitions), axis=axis, copy=False)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 359, in concat
    return op.get_result()
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 588, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
2022-02-22 14:46:10,753	ERROR worker.py:85 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::deploy_ray_func() (pid=10725, ip=127.0.0.1)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 491, in deploy_ray_func
    result = func(*args)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 159, in deploy_axis_func
    dataframe = pandas.concat(list(partitions), axis=axis, copy=False)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 359, in concat
    return op.get_result()
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 588, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/Users/leevi/opt/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```
The pandas.errors.InvalidIndexError message above repeats indefinitely.

**Comment by mvashishtha** [comment] 2022-02-24 02:42
@Leevisir thank you for the detailed issue! I am unable to reproduce the bug in Modin 0.13.2. Here's what I have after following your instructions:

```python
import modin.pandas as pd
df = pd.DataFrame(
    {"ric": ["a", "a", "c"], "source": ["d", "d", "f"]},
    index=[pd.DatetimeIndex([0, 0, 2], name="date"), pd.Index([0, 1, 2])],
    dtype="string")
df = df.reset_index(level=[0])
df = df.set_index(['ric', 'source', 'date'])
print(df)
```

This works fine for me, and prints:

```
Empty DataFrame
Columns: []
Index: [(a, d, 1970-01-01 00:00:00), (a, d, 1970-01-01 00:00:00), (c, f, 1970-01-01 00:00:00.000000002)]
```

Could you please try to give a self-contained example that reproduces the bug?

By the way, I really appreciate the stack trace, but for next time, it would be even better if you could put it in a collapsible section by following the instructions [here](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab). That way, people viewing this issue can understand it or scroll through your first comment more quickly.

**Comment by mvashishtha** [comment] 2022-09-22 03:04
@mrweijianli the other Modin contributors and I would really like to help, but we still don't have a reproducer for this issue, and it's been over 8 months since we asked for more information. I'm going to close this issue for now. If you can provide more information or you have more questions, please comment here.

**Closed by mvashishtha** 2022-09-22 03:04 UTC
Labels: Needs more information ❔, P3
