### ISSUE TITLE
Test `test_udf.py::test_agg_apply` passed, but Ray workers throws errors

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#3403] opened 2021-09-03 13:54 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Modin version** (`modin.__version__`): https://github.com/modin-project/modin/commit/b68c89bfb242f3709b4a8cc552b7b3b04b4f2ff8
- **Python version**: 3.8.10
- **Code we can use to reproduce**:
```bash
export MODIN_ENGINE=ray
pytest -s modin/pandas/test/dataframe/test_udf.py::test_agg_apply
```
Output
```bash
pandas.core.base.SpecificationError: Function names must be unique if there is no new column names assigned
2021-09-03 16:51:49,434 ERROR worker.py:78 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::deploy_ray_func() (pid=4147170, ip=10.125.130.30)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 330, in _function_with_tracing
    return function(*args, **kwargs)
  File "/localdisk/aprutsko/modin/modin/engines/ray/pandas_on_ray/frame/axis_partition.py", line 207, in deploy_ray_func
    result = func(*args)
  File "/localdisk/aprutsko/modin/modin/engines/base/frame/axis_partition.py", line 303, in deploy_axis_func
    result = func(dataframe, **kwargs)
  File "/localdisk/aprutsko/modin/modin/engines/base/frame/data.py", line 1153, in _map_reduce_func
    series_result = func(df, *args, **kwargs)
  File "/localdisk/aprutsko/modin/modin/backends/pandas/query_compiler.py", line 2454, in <lambda>
    lambda df: pandas.DataFrame(df.apply(func, axis, *args, **kwargs)),
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/frame.py", line 8736, in apply
    return op.apply()
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/apply.py", line 659, in apply
    return self.apply_multiple()
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/apply.py", line 518, in apply_multiple
    return self.obj.aggregate(self.f, self.axis, *self.args, **self.kwargs)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/frame.py", line 8543, in aggregate
    relabeling, func, columns, order = reconstruct_func(func, **kwargs)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/aggregation.py", line 87, in reconstruct_func
    raise SpecificationError(
pandas.core.base.SpecificationError: Function names must be unique if there is no new column names assigned


---------- coverage: platform linux, python 3.8.10-final-0 -----------
Coverage XML written to file coverage.xml


======================================================================================= 28 passed, 68 warnings in 14.13s ========================================================================================
```

**Comment by devin-petersohn** [comment] 2021-09-20 14:18
@prutskov Any idea why this is happening? If an excepiton is thrown in the workers, it should be rethrown when we call `to_pandas` internally.

**Comment by RehanSD** [comment] 2022-10-12 03:22
Confirmed that this is reproducible on master!

**Comment by mvashishtha** [comment] 2022-10-12 03:24
Duplicate of #3722

**Closed by mvashishtha** 2022-10-12 03:24 UTC
Labels: bug 🦗
