### ISSUE TITLE
Import Modin Fails with ImportError: cannot import name 'match' from 'pandas' 

### ISSUE THREAD

**Issue by lordgrenville** [modin-project/modin#475] opened 2019-02-20 10:12 UTC
### System information
- **OS Platform and Distribution**: MacBook Pro Mojave 10.4.2
- **Modin installed from (source or binary)**: binary (pip)
- **Modin version**: 0.3.1
- **Python version**: 3.7.1
- **Exact command to reproduce**:
import modin.pandas as pd

### Describe the problem
Just installed Modin in a conda env with Pandas 0.24. Running `import modin.pandas as pd` yields an ImportError.
### Source code / logs
Traceback:
```ImportError                               Traceback (most recent call last)
<ipython-input-990-7e7b44bd7fd7> in <module>
----> 1 import modin.pandas as pd

~/miniconda3/lib/python3.7/site-packages/modin/pandas/__init__.py in <module>
      6 # in order to keep all pandas instances across nodes consistent
      7 import pandas
----> 8 from pandas import (
      9     eval,
     10     unique,

ImportError: cannot import name 'match' from 'pandas' (/Users/joshfriedlander/miniconda3/lib/python3.7/site-packages/pandas/__init__.py)```

**Comment by devin-petersohn** [comment] 2019-02-20 14:50
Hi @lordgrenville, Modin 0.3.1 is not compatible with pandas 0.24. We released it just before pandas 0.24 was released, and the next release will have pandas 0.24 compatibility. There were quite a few API changes in pandas 0.24, so it will not work out of the box with Modin 0.3.1. Does your code have a specific requirement for pandas 0.24?

We are finalizing the update to 0.24 in #451. We are targeting a pre-release near the end of the week.

Your issue raises a good point related to more effective error messages related to pandas version. Currently, we check for the version, but it happens after the imports for what is exposed through pandas. We do this for linting purposes, but we should probably move it to run before these imports in case pandas changes their public API again.

Relevant code: https://github.com/modin-project/modin/blob/226c705a5a9c57260766fd9c29b2b75d54c1f3db/modin/pandas/__init__.py#L67-L74

**Comment by lordgrenville** [comment] 2019-02-20 16:43
Thanks for the comprehensive and helpful response @devin-petersohn . In fact my production code does not use 0.24 - I was just in a conda env I use for exploring stuff.

**Comment by devin-petersohn** [comment] 2019-02-26 03:54
Hi @lordgrenville, pandas 0.24.1 support is merged, and it should be working now. We have just released a pre-release for version 0.4, you can try with `pip install --pre modin`. Let me know if it is working for you or if you run into any issues!

**Comment by nixie** [comment] 2019-02-26 16:00
Hi, I had the same issue as @lordgrenville and the pre-release installation fixed it for me. Thanks!

**Comment by devin-petersohn** [comment] 2019-03-21 18:49
Since 0.4 is released, I am closing this. Please feel free to reopen if the issue is still present.

`pip install -U modin` to update.

**Closed by devin-petersohn** 2019-03-21 18:49 UTC
Labels: dependencies :link:
