### ISSUE TITLE
DataFrame operations affect other DataFrames

### ISSUE THREAD

**Issue by jeffreykennethli** [modin-project/modin#4183] opened 2022-02-09 14:55 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 12.0.1
- **Modin version** (`modin.__version__`): 0.13.1
- **Python version**: 3.8.8
- **Code we can use to reproduce**:
```
# import pandas as pd
import modin.pandas as pd

df = pd.DataFrame(data={"col1": [1, 2], "col2": [3, 4]})

a = pd.DataFrame(df.sum().reset_index())
b = pd.DataFrame(df.mean().reset_index())
b.columns = ["b_col1", "b_col2"]
b["b_col2"] = b["b_col2"] / 2 # This is the operation that causes the corruption.

print(a.columns) 
# Modin returns Index(['b_col1', 'b_col2'], dtype='object')
# pandas returns Index(['index', 0], dtype='object')
```

### Describe the problem
When two dataframes are created from the same DataFrame, their column names can become corrupted by an operation on the other. I haven't had time to dig into a simpler reproducible case that would help find the source of the bug, except that without the line `b["b_col2"] = b["b_col2"] / 2` this mistake doesn't happen.

**Comment by mvashishtha** [comment] 2022-02-09 17:32
@jeffreykennethli thanks for finding this! I believe that the cause is that `a` and `b` in your example share a query compiler and Modin thus makes them [sibling objects.](https://github.com/modin-project/modin/blob/32cff0d820f0149189d434cc5880f6fa91f5fd70/modin/pandas/base.py#L112). Assigning to `b["b_col2"]` calls [`_update_inplace`](https://github.com/modin-project/modin/blob/32cff0d820f0149189d434cc5880f6fa91f5fd70/modin/pandas/base.py#L216), which resets the query compilers of all siblings to the query compiler of the current dataframe.

I'm working on a fix.

**Comment by mvashishtha** [comment] 2022-02-09 19:27
Because all dataframes share the same `_siblings` object,  once any dataframe adds a sibling [here](https://github.com/modin-project/modin/blob/32cff0d820f0149189d434cc5880f6fa91f5fd70/modin/pandas/dataframe.py#L131), every dataframe gets that sibling. Here's a simpler reproducible example:

```python
import modin.pandas as pd
df1 = pd.DataFrame([[1]])
df1 = pd.DataFrame(df1)
df2 = pd.DataFrame([[2]])
# This will change the value in both df1 and df2.
# In pandas, it will only change the value in df2.
df2.iloc[0, 0] = 3
```

**Closed** 2022-03-01 19:20 UTC
Labels: bug 🦗, pandas concordance 🐼
