### ISSUE TITLE
Implement command line options for Embedded database

### ISSUE THREAD

**Issue by anton-malakhov** [modin-project/modin#1612] opened 2020-06-16 09:14 UTC
### Describe the problem
DBEngine does not support a way for specifying command line options. Please implement it by factoring out them from MapDServer.cpp into a new shared library or header

**Comment by igalink** [comment] 2020-10-22 13:39
The issue is partly fixed in the PR: https://github.com/intel-ai/omniscidb/pull/104
Where DBEngine::executeDML and DBEngine::executeRA functions changed to allow configure query execution options.

**Comment by igalink** [comment] 2020-11-09 21:09
Steps to compete the task:
1. Include CommandLineOptions object from ThriftHandler library  to DBEngine
2. Fill it using the Python kwargs as a string.

**Comment by igalink** [comment] 2020-12-10 14:56
The new PR created and approved: https://github.com/intel-ai/omniscidb/pull/119
Waiting for #2382 testing

**Comment by igalink** [comment] 2021-01-25 13:34
To leave the DBE interface unchanged,
it is necessary to add the transformation of the parameter list to the command line to create the CommandLineOptions. In the names of the input parameters, replace the underscore with a hyphen.

**Comment by igalink** [comment] 2021-02-04 15:29
All changes are done.
PR updated: https://github.com/intel-ai/omniscidb/pull/119/

**Closed** 2021-02-11 07:38 UTC
Labels: OmniSci
