### ISSUE TITLE
Incompatible Python 3.7, Pandas 1.x, Modin (latest 0.7.1)

### ISSUE THREAD

**Issue by DavidMertz** [modin-project/modin#1113] opened 2020-02-27 05:09 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
```
% uname -a
Linux popkdm 5.3.0-7625-generic #27~1576774560~19.10~f432cd8-Ubuntu SMP Thu Dec 19 20:35:37 UTC  x86_64 x86_64 x86_64 GNU/Linux
```
PopOS! (Ubuntu based)

- **Modin version** (`modin.__version__`):

0.7.1

- **Python version**:

3.7

- **Code we can use to reproduce**:

```python
In [1]: import modin.pandas as pdm
UserWarning: The pandas version installed does not match the required pandas version in Modin. This may cause undesired side effects!
FutureWarning: The pandas.SparseArray class is deprecated and will be removed from pandas in a future version. Use pandas.arrays.SparseArray instead.
FutureWarning: The SparseSeries class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
FutureWarning: The SparseDataFrame class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b8f4f5bc2460> in <module>
----> 1 import modin.pandas as pdm

~/miniconda3/envs/cleaning/lib/python3.7/site-packages/modin/pandas/__init__.py in <module>
     78
     79 from .. import __version__
---> 80 from .concat import concat
     81 from .dataframe import DataFrame
     82 from .datetimes import to_datetime

~/miniconda3/envs/cleaning/lib/python3.7/site-packages/modin/pandas/concat.py in <module>
      1 import pandas
----> 2 from .dataframe import DataFrame
      3 from .series import Series
      4
      5

~/miniconda3/envs/cleaning/lib/python3.7/site-packages/modin/pandas/dataframe.py in <module>
     19
     20 from modin.error_message import ErrorMessage
---> 21 from .utils import from_pandas, from_non_pandas, to_pandas, _inherit_docstrings
     22 from .iterator import PartitionIterator
     23 from .series import Series

~/miniconda3/envs/cleaning/lib/python3.7/site-packages/modin/pandas/utils.py in <module>
----> 1 from ..data_management.factories import BaseFactory
      2
      3
      4 def from_non_pandas(df, index, columns, dtype):
      5     new_qc = BaseFactory.from_non_pandas(df, index, columns, dtype)

~/miniconda3/envs/cleaning/lib/python3.7/site-packages/modin/data_management/factories.py in <module>
    201
    202
--> 203 class PandasOnRayFactory(BaseFactory):
    204
    205     from modin.engines.ray.pandas_on_ray.io import PandasOnRayIO

~/miniconda3/envs/cleaning/lib/python3.7/site-packages/modin/data_management/factories.py in PandasOnRayFactory()
    203 class PandasOnRayFactory(BaseFactory):
    204
--> 205     from modin.engines.ray.pandas_on_ray.io import PandasOnRayIO
    206
    207     io_cls = PandasOnRayIO

~/miniconda3/envs/cleaning/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/io.py in <module>
      8     SQLReader,
      9 )
---> 10 from modin.backends.pandas.parsers import (
     11     PandasCSVParser,
     12     PandasJSONParser,

~/miniconda3/envs/cleaning/lib/python3.7/site-packages/modin/backends/pandas/parsers.py in <module>
      3 from pandas.core.dtypes.cast import find_common_type
      4 from pandas.core.dtypes.concat import union_categoricals
----> 5 from pandas.io.common import _infer_compression
      6 from modin.engines.base.io import FileReader
      7 from modin.data_management.utils import split_result_of_axis_func_pandas

ImportError: cannot import name '_infer_compression' from 'pandas.io.common' (/home/dmertz/miniconda3/envs/cleaning/lib/python3.7/site-packages/pandas/io/common.py)
```
### Describe the problem

Traceback on import. Cannot import modin at all.  Note that `pip install modin` downgrades Pandas, which is not usable to me for other reasons.

**Comment by devin-petersohn** [comment] 2020-02-27 05:25
Thanks @DavidMertz for reporting!

There were a large amount of API changes with pandas 1.0. I have been working on it and there's a WIP PR #1081. Closing as this is a duplicate of #981 (it was previously named incorrectly). 

As a side note, we pin to a specific pandas version because it is important that we guarantee the drop-in nature of Modin and since pandas API is changing often, we need to pin to a version to make this guarantee.

**Comment by devin-petersohn** [comment] 2020-02-27 05:25
If you would like to discuss pandas 1.0 compatibility further please comment on #981. Thanks again for reporting!

**Closed** 2020-02-27 05:25 UTC
Labels: bug :bug:, duplicate :recycle:
