### ISSUE TITLE
Renaming index then grouping results in crash

### ISSUE THREAD

**Issue by alcinos** [modin-project/modin#4033] opened 2022-01-23 03:22 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Modin version** (`modin.__version__`): 0.12.1
- **Python version**:3.9.6

### Describe the problem
Renaming the index name following the solution outlined in the accepted solution on StackOverflow (https://stackoverflow.com/questions/19851005/rename-pandas-dataframe-index), followed by a groupby on the new name results in a crash.
I tested only the version on Ray.
Minimal reproducer
```
import modin.pandas as pd
df = pd.DataFrame([[0,0],[0,1],[1,2],[1,3]],  columns=("A", "B")).set_index("A")
df.index.names = ["foo"]
df.groupby("foo").apply(lambda df: df.sum())
```
This results in a traceback in all the Ray workers, with an exception `ValueError: level name foo is not the name of the index` 
Example backtrace:
```
  File "/home/alcinos/miniconda3/envs/mdetr/lib/python3.9/site-packages/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/axis_partition.py", line 211, in deploy_ray_func
    result = func(*args)
  File "/home/alcinos/miniconda3/envs/mdetr/lib/python3.9/site-packages/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 160, in deploy_axis_func
    result = func(dataframe, **kwargs)
  File "/home/alcinos/miniconda3/envs/mdetr/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 1181, in _map_reduce_func
    series_result = func(df, *args, **kwargs)
  File "/home/alcinos/miniconda3/envs/mdetr/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py", line 2806, in <lambda>
    func=lambda df, by=None, partition_idx=None: groupby_agg_builder(
  File "/home/alcinos/miniconda3/envs/mdetr/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py", line 2800, in groupby_agg_builder
    return compute_groupby(df.copy(), drop, partition_idx)
  File "/home/alcinos/miniconda3/envs/mdetr/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py", line 2743, in compute_groupby
    grouped_df = df.groupby(by=by, axis=axis, **groupby_kwargs)
  File "/home/alcinos/miniconda3/envs/mdetr/lib/python3.9/site-packages/pandas/core/frame.py", line 7631, in groupby
    return DataFrameGroupBy(
  File "/home/alcinos/miniconda3/envs/mdetr/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 889, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/home/alcinos/miniconda3/envs/mdetr/lib/python3.9/site-packages/pandas/core/groupby/grouper.py", line 750, in get_grouper
    raise ValueError(
ValueError: level name foo is not the name of the index
```

Note that after the rename, grouping by the old name "A" doesn’t work (which is the intended behaviour), and triggers a `KeyError`, as expected.

This can bug can be worked around at the cost of resetting + setting the index again (although I’m not sure what the performance implications of this mitigation are):
```
df.reset_index().set_index("foo").groupby("foo").apply(lambda df: df.sum())
```
However, I’m filling this bug because the behivour is inconsistent with vanilla pandas, which seems to be a core goal for Modin.

**Comment by gshimansky** [comment] 2022-01-24 23:42
This is a duplicate of #1618 I believe

**Comment by vnlitvinov** [comment] 2022-08-29 15:10
@alcinos could you please re-check if this is valid? I've ran your reproducer and did not encounter any exceptions on both 0.15.2 and current master.

**Closed** 2022-08-29 15:11 UTC
Labels: bug 🦗
