### ISSUE TITLE
Update docs as to when Modin operators work best

### ISSUE THREAD

**Issue by YarShev** [modin-project/modin#7217] opened 2024-04-25 11:33 UTC

**Comment by rootsmusic** [comment] 2024-04-25 20:36
Duplicate of issue #5062

**Comment by YarShev** [comment] 2024-04-25 21:26
@rootsmusic, why do you think this issue is a duplicate of #5062?

**Comment by rootsmusic** [comment] 2024-04-25 22:00
@YarShev Your issue didn't have any description.  From its title, I can only assume that it's at least related to the other issue.  That other issue is similarly requesting updating the docs about cases for which modin would work best.

**Comment by YarShev** [comment] 2024-04-25 22:37
The issue you mentioned is about handling data sizes which Modin performs well on, while this issue is related to the Modin operators and the cases when these operators works best. I would even suggest to close that issue as we already have a note in docs about the data sizes which Modin performs well on ([link](https://modin.readthedocs.io/en/stable/#modin-is-a-dataframe-for-datasets-from-1mb-to-1tb)). What do you think?

**Comment by rootsmusic** [comment] 2024-04-25 22:44
(@YarShev Sorry about assuming in this case.)  I can't answer for the other issue's author.  But I'll delete my earlier comment.

**Closed** 2024-04-26 13:32 UTC
Labels: documentation 📜
