### ISSUE TITLE
Relabeling Modin Frame loses partitions shape cache

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3111] opened 2021-06-01 12:30 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version** (`modin.__version__`): a3ddf2f
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
import modin.pandas as pd

df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

modin_frame = df._query_compiler._modin_frame
src_cache = modin_frame._partitions[0][0]._length_cache

modin_frame.columns = ["c", "d"]
relabeled_cache = modin_frame._partitions[0][0]._length_cache

assert (
    src_cache == relabeled_cache
), f"src: {src_cache} | relabeled: {relabeled_cache}"
```
Output:
```
Traceback (most recent call last):
  File "tst3.py", line 13, in <module>
    ), f"src: {src_cache} | relabeled: {relabeled_cache}"
AssertionError: src: 3 | relabeled: None
```

### Describe the problem
Setting new axis labels should not change partitioning, so the shape of partitions and so its cache should be untouched.

The cache is losing because propagating new labels into partitions (performed by [`PandasFrame.synchronize_labels`](https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/engines/base/frame/data.py#L332)) done just like regular function applying:
https://github.com/modin-project/modin/blob/a3ddf2f01163a312416d2a8bc456ba9582ae9b4d/modin/engines/base/frame/data.py#L360-L368
This doesn't give any hints to partition that the shape will be unchanged, so it resets the shape cache.

It seems that there should be some mechanism (for example different apply-function, or a parameter for the existed one) telling partition that it can preserve shape cache.

**Comment by dchigarev** [comment] 2021-06-10 10:14
Performance changes after recently merged 51658b49b54ce89f1277f8b73bdef4cf909e53fd showed, that loss of the partitions shape cache may become a real bottleneck in many operations, so we should be attentive to such kind of issues and possibly resolve them ASAP. That's why I want to ping you (@devin-petersohn) to accelerate this a bit and hear your opinion about what's the better way to solve this issue.

<details><summary>Performance changes in ASV</summary>

![image](https://user-images.githubusercontent.com/62142979/121503838-1bbf8a80-c9ea-11eb-8d16-8c61145653a9.png)

**Non**-perma link to the results: [link](https://modin.org/modin-bench/#summarylist?sort=3&dir=desc&python=3.8)

</details>

My proposal would be the following:
- Add `const` parameter to the partitions `.apply` method, indicating that the applied function does not change the shape of the partition (fake "const" looks like a hack to me, since we can't ensure a **real** constancy of the passed function and so can bring a lot of inconsistency between the real partition shape and its cache. However, I can't figure out something better)

**Comment by devin-petersohn** [comment] 2021-06-10 14:13
@dchigarev A couple of high level things to point out:

1.) The performance is probably not due to loss of partitions shape cache. `add_to_apply_calls` does not interact with the length or width, so it is just carried over.
2.) 51658b4 probably should not have been merged. I propose we revert it. @vnlitvinov @YarShev It sacrifices performance of the common case in the interest of faster performance in an edge case and I do not think we should be doing that.
3.) A better way of handling the metadata (labels and lengths/widths) needs to be implemented, but not on a per-operator basis.

**Comment by devin-petersohn** [comment] 2021-06-10 14:54
After a bit more review, let's keep 51658b4 for now. I think we can work off of it and make something generally applicable. @dchigarev I did a little testing on some better metadata management I am trying to put together, please take a look and give some feedback:

https://github.com/devin-petersohn/modin/tree/perf/2992-update

So far I get performance improvement in `groupby` and `count` by around 8-10x. Can you tell me if you get the same?

**Comment by vnlitvinov** [comment] 2021-06-10 14:56
@devin-petersohn #3113 was improving how masking is handled, I am not sure it sacrifices performance in a common case.

As for your new branch - could you please describe the idea of that decorator?..

**Comment by devin-petersohn** [comment] 2021-06-10 15:00
The decorator allows higher level metadata management of the labels. Benchmarking shows that a good amount of task time is spent applying the labels, even if they are not needed. This decorator enables query planning at the metadata level, so we can defer the application of labels in the remote partitions as long as possible (which is always better for performance).

**Comment by YarShev** [comment] 2021-06-10 19:34
The performance increase after [51658b4](https://github.com/modin-project/modin/commit/51658b49b54ce89f1277f8b73bdef4cf909e53fd) merged looks intuitive because we preliminary send a remote task to compute length and width and then just grab the result with `ray.get` or `.result()` by need. As for the decorator, it looks good at first glance but let's wait for @dchigarev gets the results.

**Comment by YarShev** [comment] 2021-06-10 19:38
@devin-petersohn , what is the reason to change `default_block_size=32` to `default_block_size=1`?

**Comment by dchigarev** [comment] 2021-06-11 15:28
@devin-petersohn can you provide the script that you're running to measure the performance changes? Running our ASV Groupby benchmarks on 3482a9ecab2a7ce7cab2a732bfc65563dcd984f6 (commit where `default_block_size` is untouched) gives no changes in performance:
(The reason is obvious, there is no place to get profit from deferring index applying if there is only one operation in the flow)
<details><summary>ASV Results</summary>

```
git checkout perf/2992-update
MODIN_TEST_DATASET_SIZE=Big MODIN_CPUS=16 asv continuous origin/master HEAD~1 --launch-method=spawn -b TimeGroupByDefaultAggregations --split --no-only-changed

       before           after         ratio
     [cf259f1c]       [3482a9ec]
     <0.10.0^0>       <perf/2992-update~1>
# MapReduce-groupby:
# (5k, 5k):
          291±9ms         288±10ms     0.99  benchmarks.TimeGroupByDefaultAggregations.time_groupby_sum((5000, 5000), 100)
          423±6ms          440±8ms     1.04  benchmarks.TimeGroupByDefaultAggregations.time_groupby_sum((5000, 5000), 'huge_amount_groups')
         245±10ms         246±30ms     1.01  benchmarks.TimeGroupByDefaultAggregations.time_groupby_count((5000, 5000), 100)
          361±8ms          363±7ms     1.00  benchmarks.TimeGroupByDefaultAggregations.time_groupby_count((5000, 5000), 'huge_amount_groups')
          120±5ms          116±1ms     0.97  benchmarks.TimeGroupByDefaultAggregations.time_groupby_size((5000, 5000), 100)
          125±1ms          121±2ms     0.97  benchmarks.TimeGroupByDefaultAggregations.time_groupby_size((5000, 5000), 'huge_amount_groups')
# (30kk, 10):
          363±6ms          364±4ms     1.00  benchmarks.TimeGroupByDefaultAggregations.time_groupby_sum((30000000, 10), 100)
          391±9ms         396±10ms     1.01  benchmarks.TimeGroupByDefaultAggregations.time_groupby_sum((30000000, 10), 'huge_amount_groups')
          278±2ms          276±4ms     0.99  benchmarks.TimeGroupByDefaultAggregations.time_groupby_count((30000000, 10), 100)
          312±5ms         319±20ms     1.02  benchmarks.TimeGroupByDefaultAggregations.time_groupby_count((30000000, 10), 'huge_amount_groups')
          178±3ms         170±20ms     0.96  benchmarks.TimeGroupByDefaultAggregations.time_groupby_size((30000000, 10), 100)
         232±20ms         220±20ms     0.95  benchmarks.TimeGroupByDefaultAggregations.time_groupby_size((30000000, 10), 'huge_amount_groups')
# FullAxis-groupby:
# (5k, 5k):
         153±30ms         172±20ms    ~1.12  benchmarks.TimeGroupByDefaultAggregations.time_groupby_mean((5000, 5000), 100)
         292±10ms          281±5ms     0.96  benchmarks.TimeGroupByDefaultAggregations.time_groupby_mean((5000, 5000), 'huge_amount_groups')
# (30kk, 10):
       5.26±0.01s       5.16±0.02s     0.98  benchmarks.TimeGroupByDefaultAggregations.time_groupby_mean((30000000, 10), 100)
       5.39±0.02s          5.51±0s     1.02  benchmarks.TimeGroupByDefaultAggregations.time_groupby_mean((30000000, 10), 'huge_amount_groups')
```

</details>

As I understood we can get the perf improvement only for those operations that are marked as "inherit" ([`groupby_reduce`](https://github.com/devin-petersohn/modin/blob/22644eab939cd35bdcccdac0f59979c281137f5d/modin/engines/base/frame/data.py#L2158) is not one of them), otherwise we still have to do this "expensive" labels propagation. 

Overall, the idea of deferring index propagation looks good, in addition to [my comment](https://github.com/devin-petersohn/modin/commit/3482a9ecab2a7ce7cab2a732bfc65563dcd984f6#r52041772) for 3482a9ecab2a7ce7cab2a732bfc65563dcd984f6 I would suggest to also defer backward labels propagation: from partitions to the frame ([`_compute_axis_labels`](https://github.com/devin-petersohn/modin/blob/22644eab939cd35bdcccdac0f59979c281137f5d/modin/engines/base/frame/data.py#L2207)) by allowing for `_index_cache` and `_columns_cache` to be `None`, we can recompute them only for the explicit accesses, which should help in workloads where we don't need labels information.

**Comment by devin-petersohn** [comment] 2021-06-15 14:00
>what is the reason to change default_block_size=32 to default_block_size=1?

This gives us higher degrees of parallelism, particularly for a lower number of columns. The PR fixes some of the issues with parallelism because it decreases the initial cost of applying the index.

>As I understood we can get the perf improvement only for those operations that are marked as "inherit"

"inherit" does provide significant improvement as you said, but "opposite" can also provide the same benefit for `groupby_reduce` if the non grouping axis (usually the `index`) does not require the label propagation. In the ASV benchmark case, the `index` is already applied. 

Here's a simple script (to run on master and 3482a9e):

```python
import modin.pandas as pd
import numpy as np
import time

arr = np.random.randint(0, 100, size=(2**20, 2**8))
df = pd.DataFrame(arr, columns=["col{}".format(i) for i in range(2**8)])
s = time.time()
df.groupby("col1").count()
print("No index reassign:", time.time() - s)
df.index = df.index + 1  # set index
s = time.time()
df.groupby("col1").count()
print("Index reassing:", time.time() - s)
```

The difference between the two times is ~2x on this 1GB dataset on master. On 3482a9e they are comparable. The `index` assignment will also happen if you just read a csv file without the `index_col` parameter, so it's a common case.

>I would suggest to also defer backward labels propagation: from partitions to the frame (_compute_axis_labels) by allowing for _index_cache and _columns_cache to be None, we can recompute them only for the explicit accesses, which should help in workloads where we don't need labels information.

Yes, I like this idea a lot. I think it is a very natural next step.

Part of the reason I originally brought up the labels is because a similar approach to handling the shape cache can also be used to propagate and defer the calculation.

**Comment by YarShev** [comment] 2021-06-15 16:24
> > what is the reason to change default_block_size=32 to default_block_size=1?
> 
> This gives us higher degrees of parallelism, particularly for a lower number of columns. The PR fixes some of the issues with parallelism because it decreases the initial cost of applying the index.

I think `default_block_size=1` may slowdown some cases and ideally it should be computed from a condition including MODIN_CPUS and as well as index and columns a dataframe.

**Comment by devin-petersohn** [comment] 2021-06-15 16:47
@YarShev `default_block_size` is only the minimum (it should probably be renamed), current partitioning is based on number of CPUs and number of columns/rows as you suggest.

**Comment by YarShev** [comment] 2021-06-15 18:16
@devin-petersohn , oh, I see. I thought `default_block_size` has another responsibility for some reason. I imagined the following case:

1) we have df with shape (100M, 19)
2) we have number of CPUs that is equal to 10
3) when we want to make up column partitions, we will have 2 column partitions with shapes (100M, 10) and (100M, 9)

However, it might be better to have 10 column partitions with shapes (100M, 2) for each one, except the last one that would have shape (100M, 1).

**Comment by devin-petersohn** [comment] 2021-06-15 20:04
@YarShev that is what should happen in this commit. In master, all 19 columns will be on one worker because minimum size is 32.

**Comment by devin-petersohn** [comment] 2021-06-25 14:40
@dchigarev I would like to combine your effort on shape performance improvements with my approach to label performance improvements, do you have progress on shape improvements?

**Comment by dchigarev** [comment] 2021-06-25 18:09
@devin-petersohn I thought It wouldn't be good to work on similar approaches in parallel, so I've done nothing so far...
I think that to be consistent we should do a one thing first (labels or shapes) and basing on that approach do the rest one.

What's the status of [`2992-update` branch](https://github.com/devin-petersohn/modin/tree/perf/2992-update)? If you'd like so I can polish your approach presented there and make a PR, or if this branch already has a mergable-quality code I can start working on the same cache-preserving/propagation system for the shapes.

**Comment by naren-ponder** [comment] 2021-12-17 16:02
Groupby Results with Metadata Labeling PR #3662 and `df = pd.DataFrame(np.random.randint(0, 100, size=(2**20, 2**8))).add_prefix("col")`:

Before PR:
```
In [4]: %timeit df.groupby("1").count()
1.43 s ± 205 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

After PR:
`In [4]: %timeit df.groupby("1").count()
865 ms ± 271 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

**Comment by pyrito** [comment] 2022-09-01 15:25
@mvashishtha @naren-ponder do you guys know what the status of this is?

**Comment by pyrito** [comment] 2022-09-01 15:26
@mvashishtha @naren-ponder it looks like the reproducer isn't failing anymore? What's the status of this?

**Comment by mvashishtha** [comment] 2022-09-01 18:53
I think #3662 fixed this.

**Closed by mvashishtha** 2022-09-01 18:53 UTC
Labels: bug 🦗, Performance 🚀, P0
