### ISSUE TITLE
BUG: repr sometimes selects same column/row twice

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#6104] opened 2023-05-10 16:58 UTC
porting commit https://github.com/ponder-org/modin-public/commit/d98dec18d0544c0d734dc67635aeb4774c39b8ec

this issue still needs a reproducer

**Comment by devin-petersohn** [comment] 2023-05-15 21:51
@mvashishtha I don't think this issue actually presents or shows. There is some weirdness with the calculation, but the duplicate column will always disappear during the display phase. I tried multiple different ways and could not reproduce the issue.

**Comment by mvashishtha** [comment] 2023-05-15 22:45
It seems the modin code is [by default](https://github.com/modin-project/modin/blob/ac92faef5293c2f8e7e93e5031068c7370e6b668/modin/pandas/dataframe.py#L244) setting num_cols to len(columns) so we don’t run into this issue by default.

however if i mess with the max_columns option I can get it:

```python
import modin.pandas as pd
import pandas
pandas.set_option("display.max_columns", 20)
df = pd.DataFrame([list(range(21))])
print(df)
```

i don’t know if anything appears wrong visually but col_indexer has the duplicate column 10: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] 

and that is a problem when `iloc` on axis 1 is selecting columns from a database..

**Comment by RehanSD** [comment] 2023-05-23 08:51
Should we close this issue @mvashishtha @devin-petersohn?

**Comment by mvashishtha** [comment] 2023-05-23 14:51
@RehanSD no, it's still relevant, but we don't need to fix it right now.

**Closed** 2023-05-25 15:49 UTC
Labels: bug 🦗, pandas.dataframe, P2
