### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2192] opened 2020-10-02 06:36 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

Cc @devin-petersohn

**Comment by devin-petersohn** [comment] 2021-01-15 15:46
Closing as duplicate of #2618

**Closed by devin-petersohn** 2021-01-15 15:46 UTC
Labels: P2, documentation :bookmark_tabs:
