### ISSUE TITLE
test_udf.py -> pandas.core.base.SpecificationError

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4955] opened 2022-09-12 15:30 UTC
```
pytest modin/pandas/test/dataframe/test_udf.py
[...]
2022-09-12 08:29:18,560	ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::deploy_ray_func() (pid=79817, ip=127.0.0.1)
  File "modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 509, in deploy_ray_func
    result = func(*args, **kwargs)
  File "modin/core/dataframe/pandas/partitioning/axis_partition.py", line 152, in deploy_axis_func
    result = func(dataframe, *kwargs.pop("args", ()), **kwargs)
  File "modin/core/dataframe/pandas/dataframe/dataframe.py", line 1523, in _tree_reduce_func
    series_result = func(df, *args, **kwargs)
  File "modin/core/storage_formats/pandas/query_compiler.py", line 2501, in <lambda>
    lambda df: pandas.DataFrame(df.apply(func, axis, *args, **kwargs)),
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 8848, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/usr/local/lib/python3.9/site-packages/pandas/core/apply.py", line 704, in apply
    return self.apply_multiple()
  File "/usr/local/lib/python3.9/site-packages/pandas/core/apply.py", line 563, in apply_multiple
    return self.obj.aggregate(self.f, self.axis, *self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 8655, in aggregate
    relabeling, func, columns, order = reconstruct_func(func, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/apply.py", line 1260, in reconstruct_func
    raise SpecificationError(
pandas.core.base.SpecificationError: Function names must be unique if there is no new column names assigned

```

**Comment by pyrito** [comment] 2022-09-12 18:50
Seems like this is a duplicate of: https://github.com/modin-project/modin/issues/3403

**Closed** 2022-09-12 20:58 UTC
Labels: bug 🦗, Triage 🩹
