### ISSUE TITLE
UserWarning: The Dask Engine for Modin is experimental.

### ISSUE THREAD

**Issue by wanghuqiang123** [modin-project/modin#1792] opened 2020-07-24 03:02 UTC
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 63533 instead
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 63552 instead
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 63565 instead
UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 63566 instead
UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 63567 instead
UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 63568 instead
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<_wrap_awaitable() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py:677> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\distributed\core.py", line 290, in _
    await self.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\distributed\nanny.py", line 295, in start
    response = await self.instantiate()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\distributed\nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\distributed\nanny.py", line 575, in start
    await self.process.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\distributed\process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\distributed\process.py", line 202, in _start
    process.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by devin-petersohn** [comment] 2020-07-24 13:50
Hi @wanghuqiang123, this is a duplicate of #843, which is a Dask issue. Further questions or discussion can be directed there. Thanks!

**Closed by devin-petersohn** 2020-07-24 13:50 UTC
Labels: bug :bug:, duplicate :recycle:
