### ISSUE TITLE
modin's `df.equals()` doesn't treat nans as equal like pandas

### ISSUE THREAD

**Issue by honno** [modin-project/modin#4653] opened 2022-07-07 12:01 UTC
In pandas, [`df.equals()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html) will treat nans as equals.

```python
>>> import pandas as pd
>>> pd_df = pd.DataFrame({"foo": [float("nan")]})
>>> pd_df.equals(pd_df)
True
```

However in modin nans are not treated as equal (at least when using ray)

```python
>>> from modin.config import Engine
>>> Engine.put("ray")
>>> from modin import pandas as mpd
>>> modin_df = mpd.DataFrame({"foo": [float("nan")]})
>>> modin_df.equals(modin_df)
False
```

This certainly isn't "wrong" behaviour, and could infact be preferred. I think it'd help if the [`equals()` listing as an implemented dataframe method](https://modin.readthedocs.io/en/stable/supported_apis/dataframe_supported.html) would be noted to specify this behaviour, if nan-equals behaviour isn't something that is desired (or even possible).

- **OS Platform and Distribution**: Ubuntu 20.04.4
- **Modin version**: 0.15.2
- **Ray version**: 1.12.1
- **Python version**: 3.8

**Comment by mvashishtha** [comment] 2022-07-07 15:35
Duplicate of #4071

**Comment by mvashishtha** [comment] 2022-07-07 15:38
@honno thank you for reporting this issue. Yes, this is a known bug with both `None` and `NaN`. I made #4148, a PR to fix the bug, but there was an [open question](https://github.com/modin-project/modin/pull/4148#issuecomment-1098564017) about whether there was a better fix. That thread hasn't been picked up for a long time.

For now I'll close this issue so #4071 remains the canonical one.

**Closed by mvashishtha** 2022-07-07 15:38 UTC
