### ISSUE TITLE
Ray Dataset convert to Modin Dataframe

### ISSUE THREAD

**Issue by CansuCandan** [modin-project/modin#3366] opened 2021-08-23 12:12 UTC
Hi,

We read data from HDFS using Ray Dataframe. Our aim is convert Ray dataframe to Modin dataframe but `ds.to_modin() ` is not exist. Can you help us?

Thank you!

**Comment by devin-petersohn** [comment] 2021-08-23 13:25
Hi @CansuCandan, thanks for posting!

We have an open issue tracking this #3213. Would you be ok to move the conversation there? It will help keep the conversations targeted.

**Comment by devin-petersohn** [comment] 2021-08-23 13:26
Closing as duplicate of #3213

**Closed by devin-petersohn** 2021-08-23 13:26 UTC
Labels: new feature/request :speech_balloon:
