### ISSUE TITLE
BUG: The wrong of docs in the chapter of "SQL on Modin Dataframes"

### ISSUE THREAD

**Issue by kevin0929** [modin-project/modin#5656] opened 2023-02-15 02:18 UTC
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
import modin.experimental.sql as sql
import ray
ray.init(runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})

# read google play app store list from csv
gstore_apps_df = pd.read_csv("https://tinyurl.com/googleplaystorecsv")

# You can then define the query that you want to perform
query_str = "SELECT App, Category, Rating FROM gstore_apps WHERE Price = '0'"


# And simply apply that query to a dataframe
result_df = sql.query(query_str, gstore_apps=gstore_apps_df)

# Print result
print(result_df)
```

### Issue Description

I was recently reading the documentation for Modin and followed the instructions step by step, but I encountered an issue. Specifically, in the chapter on "SQL on Modin Dataframes," I pasted the code as described in the documentation, but when I executed it, I received an error message: "ValueError: Cannot mask with non-boolean array containing NA / NaN values."

After some further investigation, I discovered a solution: adding the code "gstore_apps_df = gstore_apps_df.dropna()" after reading the csv file. This code removes any NaN values from "gstore_apps_df," which should prevent the error from occurring again.

### Expected Behavior
```bash
2023-02-15 10:14:28,441	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32mhttp://127.0.0.1:8265 [39m[22m
UserWarning: `read_*` implementation has mismatches with pandas:
Data types of partitions are different! Please refer to the troubleshooting section of the Modin documentation to fix this issue.
UserWarning: `from_dict` is not currently supported by PandasOnRay, defaulting to pandas implementation.
Please refer to https://modin.readthedocs.io/en/stable/supported_apis/defaulting_to_pandas.html for explanation.
                                                    App        Category  Rating
0        Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1
1                                   Coloring book moana  ART_AND_DESIGN     3.9
2     U Launcher Lite �V FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7
3                                 Sketch - Draw & Paint  ART_AND_DESIGN     4.5
4                 Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3
...                                                 ...             ...     ...
1848                                     Period Tracker         MEDICAL     4.9
1849                                  LabCorp | Patient         MEDICAL     3.6
1850                        Anatomy Learning - 3D Atlas         MEDICAL     4.5
1851                  Super Hearing Super Ear Amplifier         MEDICAL     4.1
1852               Moodpath - Depression & Anxiety Test         MEDICAL     4.6

[1853 rows x 3 columns]
```
### Error Logs

<details>

```bash
2023-02-15 10:11:05,151	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32mhttp://127.0.0.1:8265 [39m[22m
UserWarning: `read_*` implementation has mismatches with pandas:
Data types of partitions are different! Please refer to the troubleshooting section of the Modin documentation to fix this issue.
Traceback (most recent call last):
  File "c:\Users\tn781\Desktop\Ray\modin\modin_SQL.py", line 15, in <module>
    result_df = sql.query(query_str, gstore_apps=gstore_apps_df)
  File "C:\Users\tn781\anaconda3\lib\site-packages\modin\experimental\sql\__init__.py", line 47, in query
    return _query_impl(sql, *args, **kwargs)
  File "C:\Users\tn781\anaconda3\lib\site-packages\dfsql\__init__.py", line 30, in sql_query
    result = ds.query(sql, reduce_output=reduce_output)
  File "C:\Users\tn781\anaconda3\lib\site-packages\dfsql\data_sources\base_data_source.py", line 172, in query
    return self.execute_query(query, reduce_output=reduce_output)
  File "C:\Users\tn781\anaconda3\lib\site-packages\dfsql\data_sources\base_data_source.py", line 543, in execute_query
    return self.execute_select(query, reduce_output=reduce_output)
  File "C:\Users\tn781\anaconda3\lib\site-packages\dfsql\data_sources\base_data_source.py", line 400, in execute_select
    source_df = source_df[index.values]
  File "C:\Users\tn781\anaconda3\lib\site-packages\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\Users\tn781\anaconda3\lib\site-packages\modin\pandas\base.py", line 3665, in __getitem__
    return self._getitem(key)
  File "C:\Users\tn781\anaconda3\lib\site-packages\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\Users\tn781\anaconda3\lib\site-packages\modin\pandas\dataframe.py", line 3209, in _getitem
    return DataFrame(query_compiler=self._query_compiler.getitem_array(key))
  File "C:\Users\tn781\anaconda3\lib\site-packages\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\Users\tn781\anaconda3\lib\site-packages\modin\core\storage_formats\pandas\query_compiler.py", line 2221, in getitem_array
    if is_bool_indexer(key):
  File "C:\Users\tn781\anaconda3\lib\site-packages\pandas\core\common.py", line 135, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values
```
</details>

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 9068fbcfd7d4c169018ae706d6c96edea6db0cd1
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Traditional)_Taiwan.950

Modin dependencies
------------------
modin            : 0.18.1
ray              : 2.2.0
dask             : 2021.04.0
distributed      : 2021.04.0
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.3
numpy            : 1.21.0
pytz             : 2021.1
dateutil         : 2.8.1
setuptools       : 52.0.0.post20210125
pip              : 21.0.1
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
sphinx           : 4.0.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.8
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
brotli           : 
fastparquet      : None
fsspec           : 0.9.0
gcsfs            : None
matplotlib       : 3.2.2
numba            : 0.53.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
snappy           : None
sqlalchemy       : 1.4.46
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None
tzdata           : None
None

</details>

**Comment by pyrito** [comment] 2023-02-15 15:33
@kevin0929 thank you so much for opening the issue! You can go ahead and open a PR for this if you would like to contribute your patch? I'd be happy to help you get it merged in!

**Comment by kevin0929** [comment] 2023-02-17 06:36
I have opened a PR, thank you!

**Comment by anmyachev** [comment] 2023-02-20 20:42
@pyrito I can't reproduce it. My `read_csv` function defaults to pandas, apparently due to the fact that I use proxies in the environment. For the review, we need someone who reproduces this problem.

It looks like we have two problems here. First, when the reading still takes place in Modin, then we observe the error indicated in this issue. The second is that `fsspec` does not work with proxies. Perhaps that is why pandas still uses `urllib.request` to work with these protocols. @jbrockmendel am i right or wrong about `urllib.request`?

https://github.com/pandas-dev/pandas/blame/3b295c9b4891cd995f40b2bf9856b960e957f73f/pandas/io/common.py#L273-L282

@kevin0929 thanks for the contribution!

**Comment by jbrockmendel** [comment] 2023-02-20 21:14
im not aware of any proxy-related reasons for using urllib.request

**Comment by anmyachev** [comment] 2023-02-20 21:22
> im not aware of any proxy-related reasons for using urllib.request

ok, any other reasons? (not related to proxy)

**Comment by jbrockmendel** [comment] 2023-02-20 21:32
IIRC i implemented the current lazy import just for import speed.  Before that it would have been at module-level, and before that it would have been a `six` import.  So I think it is just inertia

**Comment by mvashishtha** [comment] 2023-02-28 23:18
@pyrito @kevin0929 @anmyachev I still can't reproduce the error in the original post. Why would the nulls cause a problem?

**Comment by anmyachev** [comment] 2023-03-06 16:35
> This seems like an issue that not everyone will encounter. I am not sure if a specific version or system or I use modin.pandas to read csv may cause this error. However, I think adding this piece of code may completely avoid encountering this problem. Thank everyone for helping me review this issue. If you think it is okay, I will close this issue and PR. Thank you!

Hi @kevin0929!
This problem may also be due to the internal partitioning of the dataframe in Modin. Therefore, we need to at least eliminate this factor, since it can affect many users. Could you run your slightly modified example code and show the output here? This will help us a lot.
```python
import modin.pandas as pd
import modin.experimental.sql as sql
import ray
ray.init(runtime_env={'env_vars': {'__MODIN_AUTOIMPORT_PANDAS__': '1'}})

# read google play app store list from csv
gstore_apps_df = pd.read_csv("https://tinyurl.com/googleplaystorecsv")
print(f"DTYPES: {gstore_apps_df.dtypes}")
print(F"PARTITIONS SHAPE: {gstore_apps_df._query_compiler._modin_frame._partitions.shape}")


# You can then define the query that you want to perform
query_str = "SELECT App, Category, Rating FROM gstore_apps WHERE Price = '0'"


# And simply apply that query to a dataframe
result_df = sql.query(query_str, gstore_apps=gstore_apps_df)

# Print result
print(result_df)
```

Also, if you don't mind, can you show your current environment? (`conda list`)

**Comment by kevin0929** [comment] 2023-03-06 17:03
Sorry, I have no idea why this can work and I can't also reproduc the error.But oddly, it's result is different my last try.
I feel so shame that I waste you guys time.Please accept my apologies for my stupid.

```
2023-03-07 00:59:07,985 INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
UserWarning: `read_*` implementation has mismatches with pandas:
Data types of partitions are different! Please refer to the troubleshooting section of the Modin documentation to fix this issue.
DTYPES: App                object
Category           object        
Rating            float64        
Reviews            object        
Size               object        
Installs           object        
Type               object        
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object
PARTITIONS SHAPE: (8, 1)
UserWarning: `from_dict` is not currently supported by PandasOnRay, defaulting to pandas implementation.
Please refer to https://modin.readthedocs.io/en/stable/supported_apis/defaulting_to_pandas.html for explanation.
                                                     App             Category Rating
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN    4.1
1                                    Coloring book moana       ART_AND_DESIGN    3.9
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN    4.7
3                                  Sketch - Draw & Paint       ART_AND_DESIGN    4.5
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN    4.3
...                                                  ...                  ...    ...
10035                                   Sya9a Maroc - FR               FAMILY    4.5
10036                   Fr. Mike Schmitz Audio Teachings               FAMILY    5.0
10037                             Parkinson Exercices FR              MEDICAL   <NA>
10038                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE    4.5
10039      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE    4.5

[10040 rows x 3 columns]
```

**Comment by anmyachev** [comment] 2023-03-06 18:11
> ```python
> https://tinyurl.com/googleplaystorecsv
> ```

Don't worry, everything is fine. Maybe the dataset has changed.

I think we can close the pull request and issue :)

**Comment by pyrito** [comment] 2023-03-06 18:23
@kevin0929 no worries at all! You did not waste our time! Sometimes weird issues like this can happen and posting an issue can provide more clarity to you and others who run into similar problems. Thanks for opening the issue and feel free to open other issues you find with Modin! It's a huge help to the community and we really appreciate it - 😄

**Comment by anmyachev** [comment] 2023-03-06 20:11
@kevin0929 feel free to reopen if needed

**Closed by anmyachev** 2023-03-06 20:11 UTC
Labels: bug 🦗, documentation 📜, P2
