### ISSUE TITLE
Improve performance of "mean" groupby aggregation

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3585] opened 2021-10-20 23:59 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

Currently "mean" aggregation uses `_apply_agg_function` which later calls `broadcast_apply_full_axis`. Its performance on NYC Taxi benchmark is worse than of a single threaded Pandas "mean" implementation. Instead a man-reduce approach could be used to better parallelize the calculations.

**Comment by mvashishtha** [comment] 2022-08-16 05:26
Duplicate of #1901

**Closed by mvashishtha** 2022-08-16 05:26 UTC
Labels: Performance 🚀
