### ISSUE TITLE
group by apply on top of a modin data frame

### ISSUE THREAD

**Issue by borisRa** [modin-project/modin#2749] opened 2021-02-17 10:04 UTC
### System information
- **Message : set_of_users_df[:5].apply(lambda x: x[conf_obj.user_id_col],axis=1) #
UserWarning: User-defined function verification is still under development in Modin. The function provided is not verified.**
- **OS Platform and Distribution (e.g., Distributor ID:	Ubuntu Description:	Ubuntu 18.04.4 LTS Release:	18.04 Codename: ionic
)**:
- **Modin version = 0.83** (`modin.__version__`):
- **Python version -  3.6.9 :: Anaconda, Inc.**:
- **set_of_users_df[:5].apply(lambda x: x[conf_obj.user_id_col],axis=1)**:

### Describe the problem
Tried to run apply on top of a data frame  and got at first this warning  :

` set_of_users_df[:5].apply(my_function(),axis=1)`

And even something simple gave the same error : 

` set_of_users_df[:5].apply(lambda x: x[conf_obj.user_id_col],axis=1) 
UserWarning: User-defined function verification is till under development in Modin. The function provided is not verified.`

and then this error :
 `
RayTaskError(AssertionError): ray::deploy_ray_func() (pid=20180, ip=172.17.0.8)
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "/anaconda/lib/python3.6/site-packages/ray/serialization.py", line 242, in deserialize_objects
    assert self.get_outer_object_ref() is None
AssertionError`

Also tried to show 4 first samples ( which did work before the apply)  and got :

`df_input[:4]`

Traceback (most recent call last):

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 44, in get
    return ray.get(self.oid)

  File "/anaconda/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()

RayTaskError(AssertionError): ray::deploy_ray_func() (pid=20180, ip=172.17.0.8)
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "/anaconda/lib/python3.6/site-packages/ray/serialization.py", line 242, in deserialize_objects
    assert self.get_outer_object_ref() is None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/anaconda/lib/python3.6/site-packages/IPython/core/formatters.py", line 702, in __call__
    printer.pretty(obj)

  File "/anaconda/lib/python3.6/site-packages/IPython/lib/pretty.py", line 394, in pretty
    return _repr_pprint(obj, self, cycle)

  File "/anaconda/lib/python3.6/site-packages/IPython/lib/pretty.py", line 700, in _repr_pprint
    output = repr(obj)

  File "/anaconda/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 183, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))

  File "/anaconda/lib/python3.6/site-packages/modin/pandas/base.py", line 168, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()

  File "/anaconda/lib/python3.6/site-packages/modin/backends/pandas/query_compiler.py", line 235, in to_pandas
    return self._modin_frame.to_pandas()

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/data.py", line 2124, in to_pandas
    df = self._frame_mgr_cls.to_pandas(self._partitions)

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in to_pandas
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 92, in to_pandas
    dataframe = self.get()

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 46, in get
    handle_ray_task_error(e)

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/utils.py", line 33, in handle_ray_task_error
    raise getattr(builtins, s.split(":")[0])("".join(s.split(":")[1:]))

AssertionError

Traceback (most recent call last):

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 44, in get
    return ray.get(self.oid)

  File "/anaconda/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()

RayTaskError(AssertionError): ray::deploy_ray_func() (pid=20180, ip=172.17.0.8)
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "/anaconda/lib/python3.6/site-packages/ray/serialization.py", line 242, in deserialize_objects
    assert self.get_outer_object_ref() is None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/anaconda/lib/python3.6/site-packages/IPython/core/formatters.py", line 345, in __call__
    return method()

  File "/anaconda/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 198, in _repr_html_
    result = self._build_repr_df(num_rows, num_cols)._repr_html_()

  File "/anaconda/lib/python3.6/site-packages/modin/pandas/base.py", line 168, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()

  File "/anaconda/lib/python3.6/site-packages/modin/backends/pandas/query_compiler.py", line 235, in to_pandas
    return self._modin_frame.to_pandas()

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/data.py", line 2124, in to_pandas
    df = self._frame_mgr_cls.to_pandas(self._partitions)

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in to_pandas
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 92, in to_pandas
    dataframe = self.get()

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 46, in get
    handle_ray_task_error(e)

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/utils.py", line 33, in handle_ray_task_error
    raise getattr(builtins, s.split(":")[0])("".join(s.split(":")[1:]))

AssertionError
`
`
  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/utils.py", line 33, in handle_ray_task_error
    raise getattr(builtins, s.split(":")[0])("".join(s.split(":")[1:]))`

**Comment by devin-petersohn** [comment] 2021-02-17 15:39
Hi @borisRa thanks for the report!

This warning:

```
UserWarning: User-defined function verification is still under development in Modin. The function provided is not verified.
```

Is letting you know that Modin does not do exhaustive checks on the function before it is applied. It is meant to inform that if there is an issue with the function it will not be detected until execution has begun.

The error might actually be cause just above this line, it looks like the partitions encountered an issue related to Ray deserialization. Can you shared the full script?

**Comment by borisRa** [comment] 2021-02-18 10:53
This simple lambda function raised the same error :
`modin_df.apply(lambda x: x['col_name'],axis=1) `
And after the error can't access the DF at all . For example this is the error that is being raised after `modin_df[:10]` 

And the error is :

`Traceback (most recent call last):

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 44, in get
    return ray.get(self.oid)

  File "/anaconda/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()

RayTaskError(AssertionError): ray::deploy_ray_func() (pid=32167, ip=172.17.0.8)
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "/anaconda/lib/python3.6/site-packages/ray/serialization.py", line 242, in deserialize_objects
    assert self.get_outer_object_ref() is None
AssertionError


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/anaconda/lib/python3.6/site-packages/IPython/core/formatters.py", line 702, in __call__
    printer.pretty(obj)

  File "/anaconda/lib/python3.6/site-packages/IPython/lib/pretty.py", line 394, in pretty
    return _repr_pprint(obj, self, cycle)

  File "/anaconda/lib/python3.6/site-packages/IPython/lib/pretty.py", line 700, in _repr_pprint
    output = repr(obj)

  File "/anaconda/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 183, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))

  File "/anaconda/lib/python3.6/site-packages/modin/pandas/base.py", line 168, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()

  File "/anaconda/lib/python3.6/site-packages/modin/backends/pandas/query_compiler.py", line 235, in to_pandas
    return self._modin_frame.to_pandas()

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/data.py", line 2124, in to_pandas
    df = self._frame_mgr_cls.to_pandas(self._partitions)

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in to_pandas
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 92, in to_pandas
    dataframe = self.get()

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 46, in get
    handle_ray_task_error(e)

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/utils.py", line 33, in handle_ray_task_error
    raise getattr(builtins, s.split(":")[0])("".join(s.split(":")[1:]))

AssertionError

Traceback (most recent call last):

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 44, in get
    return ray.get(self.oid)

  File "/anaconda/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()

RayTaskError(AssertionError): ray::deploy_ray_func() (pid=32167, ip=172.17.0.8)
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "/anaconda/lib/python3.6/site-packages/ray/serialization.py", line 242, in deserialize_objects
    assert self.get_outer_object_ref() is None
AssertionError


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/anaconda/lib/python3.6/site-packages/IPython/core/formatters.py", line 345, in __call__
    return method()

  File "/anaconda/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 198, in _repr_html_
    result = self._build_repr_df(num_rows, num_cols)._repr_html_()

  File "/anaconda/lib/python3.6/site-packages/modin/pandas/base.py", line 168, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()

  File "/anaconda/lib/python3.6/site-packages/modin/backends/pandas/query_compiler.py", line 235, in to_pandas
    return self._modin_frame.to_pandas()

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/data.py", line 2124, in to_pandas
    df = self._frame_mgr_cls.to_pandas(self._partitions)

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in to_pandas
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/base/frame/partition_manager.py", line 531, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 92, in to_pandas
    dataframe = self.get()

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 46, in get
    handle_ray_task_error(e)

  File "/anaconda/lib/python3.6/site-packages/modin/engines/ray/utils.py", line 33, in handle_ray_task_error
    raise getattr(builtins, s.split(":")[0])("".join(s.split(":")[1:]))

AssertionError`

**Comment by devin-petersohn** [comment] 2021-02-18 14:34
How was the dataframe created? Can you share more of the full script?

**Comment by borisRa** [comment] 2021-02-18 15:20
**The data frame was created from pandas :**

modin_data = modin_pd.DataFrame(pandas_df)

Script :

`def train_test_split_stratified_by_time_order(x_input ,negative_ratio, epoch_back_in_time=0, y_column = "rating" ,timestamp_col= "timestamp"\
											  , is_remove_all_samples_after_test_item=False,test_size=0.3) :



	negative_samples = x_input[x_input[y_column]==0].copy()
	positive_samples = x_input[x_input[y_column]>0].copy()
	
	tmp_negative_samples = tmp_negative_samples.sort_values(by=timestamp_col,ascending=False) #Sort from newest for oldest ( high to low)
	

	how_many_positives_to_take_for_validation  = 1
	
	
	negative_samples_test = tmp_negative_samples[0: negative_ratio * how_many_positives_to_take_for_validation ]
	negative_samples_train = tmp_negative_samples[negative_ratio * how_many_positives_to_take_for_validation:]
	
	
	positive_samples = positive_samples.sort_values(by=timestamp_col,ascending=False) #Sort from newest for oldest ( high to low)


	positive_samples_test =positive_samples[0:how_many_positives_to_take_for_validation ]
	positive_samples_train =positive_samples[how_many_positives_to_take_for_validation :]

	#Rbind all together neaitve & postive together
	x_train =  pd.concat([positive_samples_train,negative_samples_train],axis=0)
	x_test  = pd.concat([positive_samples_test,negative_samples_test],axis=0)
	
	#******************************************************************************************************

	train_indices = x_train.index
	test_indices = x_test.index


	return ((train_indices, test_indices))
	
	


def loop_users_in_parallel(user_id):

	user_id_sub_data = df_input[df_input[conf_obj.user_id_col] == user_id].copy()
	

	start_time_11 = datetime.now()
	(train_indices_tmp, test_indices_tmp) = train_test_split__by_time(user_id_sub_data ,conf_obj.negative_ratio,epoch_back_in_time,\
										y_column = conf_obj.rating_col , timestamp_col = conf_obj.timestamp_col, \
										is_remove_all_samples_after_test_item = conf_obj.is_remove_all_samples_after_test_item, test_size = 0.1)
	time_elapsed_11 = datetime.now() - start_time_11 ;	print('my_fun -> Time elapsed (hh:mm:ss.ms) {}'.format(time_elapsed_11))	

	
	#Return train & test indices
	return(train_indices_tmp,test_indices_tmp)



#Start from here
set_of_users_df = pd.DataFrame(set_of_users,columns=[conf_obj.user_id_col])
set_of_users_modin_df = modin_pd.DataFrame(set_of_users_df[:10].copy())
train_and_test_indices =set_of_users_modin_df.swifter.apply(loop_users_in_parallel,axis=1) #axis =1 => per each row
	
	

	`

**Comment by devin-petersohn** [comment] 2021-02-19 14:08
Will you test if the same thing happens if you do not use the `swifter.apply`?

**Comment by pyrito** [comment] 2022-08-23 17:53
@borisRa are you still facing this issue? Could you update the issue with a proper reproducer so that we can investigate? I'm going to close this issue for now, but please feel free to re-open this if you feel it's necessary.

**Closed by pyrito** 2022-08-23 17:53 UTC
Labels: bug 🦗
