### ISSUE TITLE
Spamed UserWarnings till Juputer Notebook kernel dies.

### ISSUE THREAD

**Issue by joelostlund** [modin-project/modin#4693] opened 2022-07-21 00:02 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- MacOSX x86
- **Modin version** (`modin.__version__`):
- 10.15.2
- **Python version**:
- 3.8.13
- **Code we can use to reproduce**:
Trying to modify a large List of dicts in a column in pandas with:

`tmp = pd.DataFrame(training_set_data['descriptors_and_weights'].tolist()).stack().apply(
        pd.Series)`

### Describe the problem

Getting spammed this:

`UserWarning: Distributing <class 'dict'> object. This may take some time.`

Till my Jupyter notebook and kernel crashes. Finds no way to skip this error.

**Comment by mvashishtha** [comment] 2022-07-21 19:22
@joelostlund thank you for reporting your issue.

 If you want the function you're applying in `modin.pandas.Series` to itself return a series, you should return `pandas.Series` instead of `modin.pandas.Series`. This is a bug in Modin mentioned [here](https://github.com/modin-project/modin/issues/4635#issuecomment-1181302269). I think you're getting a warning because you're making a Modin series for every single element in the result of the `stack`. Every time you make a Modin series, you'll get that warning.

So please try:

```python
import pandas

tmp = pd.DataFrame(training_set_data['descriptors_and_weights'].tolist()).stack().apply( pandas.Series)
```

and let me know whether that works.

**Comment by joelostlund** [comment] 2022-07-22 11:31
Thanks for the answer! Still getting another issue though.

`
UserWarning: `Series.tolist` defaulting to pandas implementation.
UserWarning: Distributing <class 'list'> object. This may take some time.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/7k/zky42bzn36q0pn3wgv4f60tw0000gp/T/ipykernel_26668/1348720331.py in <module>
      1 import pandas
      2 
----> 3 tmp = pd.DataFrame(training_set_data['descriptors_and_weights'].tolist()).stack().apply( pandas.Series)

~/.pyenv/versions/3.8.12/envs/delivery-notebooks/lib/python3.8/site-packages/modin/logging/logger_metaclass.py in log_wrap(*args, **kwargs)
     66             logger.info(f"END::PANDAS-API::{class_name}.{method_name}")
     67             return result
---> 68         return method(*args, **kwargs)
     69 
     70     return log_wrap

~/.pyenv/versions/3.8.12/envs/delivery-notebooks/lib/python3.8/site-packages/modin/pandas/series.py in apply(self, func, convert_dtype, args, **kwargs)
    680                 return result
    681         else:
--> 682             result = getattr(sys.modules[self.__module__], return_type)(
    683                 query_compiler=result
    684             )

AttributeError: module 'modin.pandas.series' has no attribute 'DataFrame'
`

**Comment by joelostlund** [comment] 2022-07-25 13:51
@mvashishtha I forgot to tag you so just tagging back on my post above.

**Comment by mvashishtha** [comment] 2022-07-29 16:35
@joelostlund I can reproduce that error on modin 0.15.2 with script:

```python
import modin.pandas as pd
import pandas

pd.Series(1).apply(lambda x: pandas.Series([x, x]))
```

But with the latest Modin source I get a slightly different error. I'm closing this issue in favor #4734, which is dedicated to this bug. Please follow progress there.

**Closed by mvashishtha** 2022-07-29 16:35 UTC
