### ISSUE TITLE
GPU DataFrame support

### ISSUE THREAD

**Issue by simon-mo** [modin-project/modin#150] opened 2018-10-10 17:13 UTC
Support for GPU Dataframe: 
http://rapids.ai/documentation.html

**Comment by devin-petersohn** [comment] 2020-06-01 14:38
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.

**Comment by rohan-gt** [comment] 2020-07-24 17:53
Does modin have GPU support now?

**Comment by devin-petersohn** [comment] 2020-07-24 22:20
@rohan-gt Modin does not have GPU support yet. I believe I closed this in error when I was closing a bunch of stale issues.

**Comment by mvashishtha** [comment] 2022-08-29 17:08
Duplicate of #2538

**Closed by mvashishtha** 2022-08-29 17:08 UTC
Labels: new feature/request 💬, Help Wanted 🌐, P2
