### ISSUE TITLE
Building documentation generates a lot of warnings

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3099] opened 2021-05-28 16:23 UTC
### Describe the problem
Building documentation for read-the-docs at the current master generates a lot of warnings. Commit from which it started: b1c6e75f4c8442195e8551b561ba62479cac75c4
**Reproducer**:
```bash
cd MODIN_ROOT_FOLDER/docs
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
```
<details><summary>Output:</summary>

```
WARNING: autodoc: failed to import module 'spreadsheet.general' from module 'modin'; the following exception was raised:
Please `pip install modin[spreadsheet]` to install the spreadsheet extension
WARNING: autodoc: failed to import module 'spreadsheet.general' from module 'modin'; the following exception was raised:
Please `pip install modin[spreadsheet]` to install the spreadsheet extension
WARNING: autodoc: failed to import module 'grid' from module 'modin_spreadsheet'; the following exception was raised:
No module named 'modin_spreadsheet'
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.clip:17: WARNING: Inline strong start-string without end-string.
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.cummax:11: WARNING: Inline strong start-string without end-string.
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.cummin:11: WARNING: Inline strong start-string without end-string.
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.cumprod:11: WARNING: Inline strong start-string without end-string.
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.cumsum:11: WARNING: Inline strong start-string without end-string.
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.to_latex:92: WARNING: Unexpected section title.

Returns
-------
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.to_sql:68: WARNING: Duplicate explicit target name: "1".
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.to_sql:69: WARNING: Footnote [2] is not referenced.
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.to_pickle:15: WARNING: Duplicate target name, cannot be used as a unique reference: "1".
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.to_sql:3: WARNING: Duplicate target name, cannot be used as a unique reference: "1".
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.dropna:3: WARNING: undefined label: missing_data (if the link has no caption the label must precede a section header)
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.ewm:95: WARNING: undefined label: window.exponentially_weighted (if the link has no caption the label must precede a section header)
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.iloc:22: WARNING: undefined label: indexing.integer (if the link has no caption the label must precede a section header)
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.loc:25: WARNING: undefined label: indexing.label (if the link has no caption the label must precede a section header)
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.mask:50: WARNING: undefined label: indexing.where_mask (if the link has no caption the label must precede a section header)
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.reindex:196: WARNING: undefined label: basics.reindexing (if the link has no caption the label must precede a section header)
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.to_hdf:11: WARNING: undefined label: io.hdf5 (if the link has no caption the label must precede a section header)
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.to_hdf:59: WARNING: undefined label: io.hdf5-query-data-columns (if the link has no caption the label must precede a section header)
modin\modin\pandas\base.py:docstring of modin.pandas.base.BasePandasDataset.to_sql:43: WARNING: undefined label: io.sql.method (if the link has no caption the label must precede a section header)
```

</details>

**Comment by dchigarev** [comment] 2021-06-03 09:35
Most of the warnings generated because of the artifacts of inheritance pandas docstrings by the [`BasePandasDataset`](https://github.com/modin-project/modin/blob/64d6cb064feac23ed5bfa0cba221f35c512c114e/modin/pandas/base.py#L92). 

Here are some examples of those artifacts (not all of them generates building warnings):
1. References to an internal pandas documentation sections that we cannot copy.
```
>>> print(modin.pandas.DataFrame.reindex.__doc__)
...
See the :ref:`user guide <basics.reindexing>` for more.
```
2. `versionadded` and `deprecated` directive points to the pandas versions without any note about it, which may be confusing since the version number appears in modin docs.
```
>>> print(modin.pandas.DataFrame.groupby.__doc__)
...
dropna : bool, default True
    If True, and if group keys contain NA values, NA values together
    with row/column will be dropped.
    If False, NA values will also be treated as the key in groups

    .. versionadded:: 1.1.0 # Means: pandas 1.1.0, not modin 1.1.0
...
```
3. Breaking numpy doc-style, so difficulties with building docs
```
>>> print(modin.pandas.DataFrame.clip.__doc__)
...
*args, **kwargs   # Parameters doesn't have a type
    Additional keywords have no effect but might be accepted
    for compatibility with numpy.
...
```
4. Incorrect indentations, so difficulties with building docs
```
>>> print(modin.pandas.DataFrame.to_latex.__doc__)
...
    .. versionadded:: 1.2.0

        Returns
        -------
        str or None
            If buf is None, returns the result as a string. Otherwise returns
            None.

See Also
--------
...
```

**Comment by Garra1980** [comment] 2021-07-20 15:18
Does this still happen?

**Comment by prutskov** [comment] 2021-08-06 13:30
Should we create an issue/PR with fixes of docstrings in `pandas.DataFrame`? After #3325 is merged, we will have only warnings described in https://github.com/modin-project/modin/issues/3099#issuecomment-853733114, related to incorrect docstrings in `pandas.DataFrame`.

**Comment by YarShev** [comment] 2021-08-10 08:53
Yes, we should create an issue on their side and discuss the changes first at least.

**Comment by YarShev** [comment] 2022-03-09 13:47
It is decided to use the approach we apply for modin.pandas.DataFrame/Series. @amyskov, will you handle this?

**Comment by amyskov** [comment] 2022-03-09 14:06
> It is decided to use the approach we apply for modin.pandas.DataFrame/Series. @amyskov, will you handle this?

Yes, assigned task to me.

**Comment by YarShev** [comment] 2022-03-22 17:09
Reopening because #4333 doesn't fully resolve the issue. The rest part of the warnings will be covered in #4297.

**Comment by mvashishtha** [comment] 2022-10-12 04:30
The reproducer doesn't give me all those warnings at modin 88f7b27d32b099c508e93251cafe503f2908d426 any more.

**Closed by mvashishtha** 2022-10-12 04:30 UTC
Labels: documentation 📜
