### ISSUE TITLE
importing modin result in latest arrow 6.0 hang

### ISSUE THREAD

**Issue by xwu99** [modin-project/modin#3982] opened 2022-01-17 01:58 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04 LTS
Windows 10
- **Modin version** (`modin.__version__`):
0.12.1
- **Python version**:
Python 3.9.1

- **Code we can use to reproduce**:

Install latest modin and arrow with:
```
conda create -n test -c conda-forge modin-all pyarrow=6.0.1
```
Then use the code to reproduce. 

```
# importing modin result in hang for arrow iterator
import modin.pandas as pd
import pyarrow.dataset as ds

dfile = 'veterans_lung_cancer.csv'
data = ds.dataset(dfile, format='csv')
rb_iter = iter(data.to_batches())
next(rb_iter)
```

Also attach the code:

[modin_arrow_hang.tar.gz](https://github.com/modin-project/modin/files/7878514/modin_arrow_hang.tar.gz)

### Describe the problem
The code hang with arrow 6.0, but for arrow 4.0 it's ok. If modin is removed, everything is fine.

**Comment by YarShev** [comment] 2022-01-17 11:53
Hi @xwu99, thanks for the report! I was able to reproduce the issue on Windows, but not on Linux. We will take a look at this more closely.

Also, the following issues were observed on Linux when digging into the problem.

1. When performing `conda create -n test -c conda-forge modin-all pyarrow=6.0.1` Modin 0.11.1 is installed and when performing `conda create -n test -c conda-forge modin-all` Modin 0.11.3 is installed.
2. When updating pyarrow 3.0.0 to pyarrow 6.0.0 in environment-dev.yml I got deps conflict.

cc @devin-petersohn

**Comment by xwu99** [comment] 2022-01-17 12:02
You can also try to mix using conda-forge and pip install to reproduce on Linux. Such as using conda to install pyarrow and pip to install modin or the other way.

**Comment by YarShev** [comment] 2022-01-17 12:12
Yes, @prutskov, did this way and reproduced the issue. However, a common practice is not to mix conda and pip.

**Comment by xwu99** [comment] 2022-01-17 23:26
> Yes, @prutskov, did this way and reproduced the issue. However, a common practice is not to mix conda and pip.

Not intended to mix, but somethings there are some packages not released in both channels.

**Comment by devin-petersohn** [comment] 2022-01-18 14:19
@xwu99 is there a companion issue in arrow? Probably worth opening there since this fix will probably need to be there.

While it is not recommended to mix conda and pip, it sometimes must happen if certain packages are only supported in one or the other as @xwu99 mentions.

Looking into what is causing this. We don't run anything super complicated in the init, so it is unexpected.

**Comment by devin-petersohn** [comment] 2022-01-18 14:37
Ok, I was able to reproduce this without Modin: 

```python
import os
import pyarrow.dataset as ds

os.environ["OMP_NUM_THREADS"] = "1"  # offending line

dfile = 'veterans_lung_cancer.csv'
data = ds.dataset(dfile, format='csv')
rb_iter = iter(data.to_batches())
next(rb_iter)  # hangs
```

This probably needs to be raised in pyarrow because it is not something we could fix in Modin. Thanks @xwu99 for finding/reporting this!

**Comment by xwu99** [comment] 2022-01-18 14:38
I did not submit issue for arrow right now. It looks importing Modin impacts arrow's normal behavior. But we can submit PR if arrow needs to be fixed.

**Comment by xwu99** [comment] 2022-01-18 14:48
> Ok, I was able to reproduce this without Modin: 
> 
> 
> 
> ```python
> 
> import os
> 
> import pyarrow.dataset as ds
> 
> 
> 
> os.environ["OMP_NUM_THREADS"] = "1"  # offending line
> 
> 
> 
> dfile = 'veterans_lung_cancer.csv'
> 
> data = ds.dataset(dfile, format='csv')
> 
> rb_iter = iter(data.to_batches())
> 
> next(rb_iter)  # hangs
> 
> ```
> 
> 
> 
> This probably needs to be raised in pyarrow because it is not something we could fix in Modin. Thanks @xwu99 for finding/reporting this!

Did you change openmp env when importing Modin? It seems to work for earlier versions of pyarrow (4.0)?
I can submit another issue for pyarrow.

**Comment by devin-petersohn** [comment] 2022-01-18 14:54
Yes, we set `os.environ["OMP_NUM_THREADS"] = "1"` on import to avoid running out of threads on the OS. Users can override it if they wish by manually setting `OMP_NUM_THREADS` after import.

Even if we move this setting, it will not solve the problem for pyarrow.

**Comment by devin-petersohn** [comment] 2022-01-18 18:40
I have opened an issue here: https://issues.apache.org/jira/browse/ARROW-15362

**Comment by devin-petersohn** [comment] 2022-01-18 19:58
Ok looks like the issue has been resolved and the fix will be in the next release.

Closing this, but please re-open if there is something we should do/change to help with this.

**Closed by devin-petersohn** 2022-01-18 19:58 UTC

**Comment by Garra1980** [comment] 2022-01-18 20:07
Probably mention this in Troubleshooting?

**Comment by devin-petersohn** [comment] 2022-01-18 21:43
@Garra1980 yes, we can add a note there.
