### ISSUE TITLE
Setting display.max_rows and display.max_columns options to None resets them to defaults

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#2245] opened 2020-10-14 17:11 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.8.1.1+4.gbd8f73a

- **Python version**:

Python 3.8.3

- **Code we can use to reproduce**:

```python
import os
import time
import numpy as np
import modin.pandas as pd

RAND_LOW = 0
RAND_HIGH = 100
NCOLS = 20
NROWS = 100

random_state = np.random.RandomState(seed=42)

data = pd.DataFrame({
        "col{}".format(i): random_state.randint(
            RAND_LOW, RAND_HIGH, size=(NROWS)
        )
        for i in range(NCOLS)
})

pd.set_option("display.max_rows", None, "display.max_columns", None)
print(data)
```

### Describe the problem

Code above is supposed to print a whole dataframe no matter what size it is. Idea is taken from here https://www.kite.com/python/answers/how-to-print-an-entire-pandas-dataframe-in-python
But on Modin setting options to `None` makes them reset to default values `10` https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L161.

**Comment by pyrito** [comment] 2022-08-22 20:40
I am still able to reproduce this on master.

**Comment by mvashishtha** [comment] 2022-08-22 22:04
Duplicate of #4640

**Closed by mvashishtha** 2022-08-22 22:04 UTC
Labels: bug 🦗, pandas concordance 🐼, P3
