### ISSUE TITLE
Pivot Tables errors when using modin with Pandas

### ISSUE THREAD

**Issue by LuisFRoch** [modin-project/modin#1895] opened 2020-08-06 11:13 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac - Catalina
- **Modin version** (`modin.__version__`): 0.8.0
- **Python version**: 3.8.1
- **Code we can use to reproduce**: pd.pivot_table(data, values = ['col1', 'col2'], index = [col3'])

### Describe the problem
 When using pivot tables with modin i get the following error: can not create pivot table with instance of type <class 'pandas.core.frame.DataFrame'>. Pure Pandas works fine when removing "modin" from "import modin.pandas as pd". data is clean of nan, etc.. Any ideas why this might be or is a feature not available?

### Source code / logs

`<!-- ValueError                                Traceback (most recent call last)
<ipython-input-129-7b52ec03c630> in <module>
      1 #data.reset_index(inplace=True)
t = pd.pivot_table(data, values = ['Adj Close', 'Volume'], index = ['Date'])

~/miniconda3/envs/JupLab/lib/python3.8/site-packages/modin/pandas/general.py in pivot_table(data, values, index, columns, aggfunc, fill_value, margins, dropna, margins_name, observed)
    249 ):
    250     if not isinstance(data, DataFrame):
 251         raise ValueError(
    252             "can not create pivot table with instance of type {}".format(type(data))
    253         )

ValueError: can not create pivot table with instance of type <class 'pandas.core.frame.DataFrame'>`

Thanks!

**Comment by devin-petersohn** [comment] 2020-08-06 15:38
Hi @LuisFRoch thanks for the report!

Can you share some more of the code that generated this error? I see that somewhere there is a `pandas.DataFrame` that was created which should not be happening in Modin.

**Comment by LuisFRoch** [comment] 2020-08-06 18:44
> Hi @LuisFRoch thanks for the report!
> 
> Can you share some more of the code that generated this error? I see that somewhere there is a `pandas.DataFrame` that was created which should not be happening in Modin.

Hi @devin-petersohn, thanks for the quick response!

`data = pd.read('../path/data.csv')
data.head(2)
data.reset_index(inplace=True)
t = pd.pivot_table(data, index=['Date'])
Or
t = pd.pivot_table(data, values = ['Adj Close', 'Volume'], index = ['Date'])
`
When I run with modin.pandas I get an error, but when I use pure pandas no error.

**Comment by dchigarev** [comment] 2020-10-15 16:00
Reported error occurs when `modin.pandas.pivot_table` obtain pandas instead of modin frame. If we perform operations under modin DataFrame it always returns modin DataFrame (at least it has to). Following execution flow from [this](https://github.com/modin-project/modin/issues/1895#issuecomment-670123979) message, it seems that only `df.head(2)` could potentially return pandas frame by mistake. However, it strictly depends on the frame data and related code works correct on 0.8.0 (at which version it was reported) and on the current master:
```python
if __name__ == "__main__":
    import modin.pandas as pd
    from modin.pandas.test.test_io import (
        create_test_pandas_dataframe,
        TEST_CSV_FILENAME,
    )

    create_test_pandas_dataframe().to_csv(TEST_CSV_FILENAME)

    df = pd.read_csv(TEST_CSV_FILENAME)
    df = df.head(2)
    df.reset_index(inplace=True)
    res = pd.pivot_table(df, index="col2")
    print(res)
```

@LuisFRoch sorry for the slow response, but if you're still here, could you please share the data that you used to get that error?

**Comment by Apsylem** [comment] 2021-06-14 14:01
this problem percists until today Version: 0.10.0

**Comment by devin-petersohn** [comment] 2021-06-14 15:18
@Apsylem that's helpful to know. Could you share the full traceback for your error?

**Comment by mvashishtha** [comment] 2022-09-14 17:29
Looks like we never got a reproducer and this issue is over a year old. I'm going to close it. @Apsylem @LuisFRoch please comment here if you need more help with this issue.

**Closed by mvashishtha** 2022-09-14 17:29 UTC
Labels: bug 🦗, Needs more information ❔
