### ISSUE TITLE
AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by deeplook** [modin-project/modin#647] opened 2019-06-03 08:52 UTC
I keep getting this error: `AttributeError: type object 'Callable' has no attribute '_abc_registry'` when running `from modin.pandas import pd`. for version 0.5.2 of modin. I see various similar issues being closed like #619 or #540. They seem to suggest uninstalling the `typing` package which is not an option for me.

I'm on macOS 10.14 and Python 3.7.3 and have installed modin via `pip install modin`.

**Comment by devin-petersohn** [comment] 2019-06-03 16:01
Thanks for the report @deeplook!

First, when you run `from modin.pandas import pd` you should be getting an error:
```
ImportError: cannot import name 'pd' from 'modin.pandas' (/Users/DevinPetersohn/software_builds/modin/modin/pandas/__init__.py)
```
It's not the cause of the problem, but it will cause you problems once we get this fixed.

Would you be able to see if the following works for you:

```python
import pandas
import ray
ray.init()

ray.get(ray.put(pandas.DataFrame([1,2,3])))
```

It seems like an issue with the serialization.

**Comment by deeplook** [comment] 2019-06-03 21:01
@devin-petersohn I can run this fine. The `ray.init()` gives some info log message ending with `INFO services.py:1441 -- Starting the Plasma object store with 5.15 GB memory using /tmp` and the `ray.get(...)` returns a simple one-column dataframe...

**Comment by devin-petersohn** [comment] 2019-06-03 21:32
I see, I looked through the traceback of one of the other issues, would you be able to try this:

```python
import ray
ray.init()

@ray.remote
def should_break():
    import pandas
    return pandas.DataFrame([1,2,3])

ray.get([should_break.remote() for _ in range(10)])
```

If it does not break, would you provide the full traceback of the error when it occurs in Modin?

**Comment by deeplook** [comment] 2019-06-04 07:42
It gives a huge traceback ending in this (temporary full gist here: https://gist.github.com/deeplook/14caeca2f5085abfaf80315ce2f28036):

```
2019-06-04 09:35:19,928	ERROR worker.py:1678 -- A worker died or was killed while executing task 00000000c9e378d6a1b4b1cbebf4fd2275ef4e18.
2019-06-04 09:35:19,928	ERROR worker.py:1678 -- A worker died or was killed while executing task 000000005c3022986d5b1bacee9cd2f1ba45e530.

---------------------------------------------------------------------------
RayWorkerError                            Traceback (most recent call last)
<ipython-input-1-bf4fd111b64d> in <module>
      7     return pandas.DataFrame([1,2,3])
      8 
----> 9 ray.get([should_break.remote() for _ in range(10)])

~/nagini_conda3/envs/nagini/lib/python3.7/site-packages/ray/worker.py in get(object_ids)
   2195             if isinstance(value, RayError):
   2196                 last_task_error_raise_time = time.time()
-> 2197                 raise value
   2198 
   2199         # Run post processors.

RayWorkerError: The worker died unexpectedly while executing this task.
```

**Comment by devin-petersohn** [comment] 2019-06-04 15:06
Thank you, this is very helpful. It is an issue with the way that Ray is serializing the pandas library to run the task.

I created an issue on our dependency, Ray: ray-project/ray#4929. It will have to be resolved in Ray for it to be fixed in Modin.

**Comment by deeplook** [comment] 2019-06-06 10:15
I've pip-uninstalled `typing` as I was told elsewhere I don't need that on Python 3.7. Then I get no more errors, but also now speedup for reading 41M of CSV. Anyway, that's likely another topic... ;)

**Comment by devin-petersohn** [comment] 2019-06-06 15:18
I'm glad that we fixed the `typing` issue.

For the CSV performance, would you be willing to open a new issue to track that separately? I am glad to discuss it there.

**Closed** 2019-08-29 19:05 UTC
Labels: dependencies :link:
