### ISSUE TITLE
[omnisci] Incorrect Series.dtype of dataframe column after pandas.concat

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3445] opened 2021-09-17 23:18 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04.1 LTS

- **Modin version** (`modin.__version__`):

0.10.2+26.gda2ad792

- **Python version**:

Python 3.9.7

- **Code we can use to reproduce**:

```python
import numpy as np
import modin.pandas as pd

MULTIPLIER = 5

df = pd.DataFrame({
    "a": [np.float(1)] * MULTIPLIER,
    "s": ["abc"] * MULTIPLIER,
    "i": [10] * MULTIPLIER,
    "t": [pd.to_datetime("2021")] * MULTIPLIER
})

print(df["t"].dtype)
print(type(df["t"].dtype))

df2 = df.copy()
print(df2["t"].dtype)
print(type(df2["t"].dtype))

df3 = pd.concat([df, df2])
print(df3["t"].dtype)
print(type(df3["t"].dtype))
```

### Describe the problem

After `pandas.concat` column's `dtype` values undergo some strange transformation and instead of an object type become `Series` type. This makes statements like `df['column'].dtype == 'object'` raise an exception `ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().` which breaks user's code.

**Comment by dchigarev** [comment] 2022-01-13 09:10
The problem was fixed by #3471 that became a part of the 0.11 release. After this commit I see no problems with the repro:

<details><summary>Reproducer</summary>

```bash

reproducer="
import modin.config as cfg

cfg.IsExperimental.put(True)
cfg.Engine.put('native')
try:
    cfg.StorageFormat.put('omnisci')
except AttributeError:
    # For older modin versions
    cfg.Backend.put('omnisci')

import numpy as np
import modin.pandas as pd

MULTIPLIER = 5

df = pd.DataFrame({
    'a': [np.float(1)] * MULTIPLIER,
    's': ['abc'] * MULTIPLIER,
    'i': [10] * MULTIPLIER,
    't': [pd.to_datetime('2021')] * MULTIPLIER
})

print(df['t'].dtype)
print(type(df['t'].dtype))

df2 = df.copy()
print(df2['t'].dtype)
print(type(df2['t'].dtype))

df3 = pd.concat([df, df2])
print(df3['t'].dtype)
print(type(df3['t'].dtype))
"

git checkout 02a34eb8c89f1966e41be9a5742ce09a7a6628b2 &> /dev/null
echo "Running reproducer after the fix:"
python -c "$reproducer"
git checkout HEAD~1 &> /dev/null
echo "Running reproducer before the fix:"
python -c "$reproducer"

```

</details>

Output:
```
Running reproducer after the fix:
datetime64[ns]
<class 'numpy.dtype[datetime64]'>
datetime64[ns]
<class 'numpy.dtype[datetime64]'>
datetime64[ns]
<class 'numpy.dtype[datetime64]'>

Running reproducer before the fix:
datetime64[ns]
<class 'numpy.dtype[datetime64]'>
datetime64[ns]
<class 'numpy.dtype[datetime64]'>
__index__             int64
t            datetime64[ns]
dtype: object
<class 'pandas.core.series.Series'>
```

**Closed by dchigarev** 2022-01-13 09:10 UTC
Labels: bug 🦗, OmniSci
