### ISSUE TITLE
convert docstrings in high level APIs to numpydoc style

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2197] opened 2020-10-02 09:38 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?

**Comment by devin-petersohn** [comment] 2020-10-12 11:43
Is this a duplicate of #1411

**Comment by anmyachev** [comment] 2020-10-12 11:52
> Is this a duplicate of #1411?

#1411 is about the entire modin project(pydocstyle checks for all subfolders, for example, `modin/experimental`), but #2197 is about pandas public api(mainly for `modin/pandas` folder).

**Closed** 2020-10-14 11:17 UTC
Labels: new feature/request :speech_balloon:
