### ISSUE TITLE
``Series.sample()``, ``Series.repeat()`` and ``Series.empty()`` don`t work correctly at MODIN_STORAGE_FORMAT=omnisci

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#3984] opened 2022-01-17 10:53 UTC
When I run:
```
import modin.pandas as pd
from modin.pandas.test.utils import test_data_values
import modin.config as cfg
cfg.StorageFormat.put('omnisci')

data = test_data_values[0]
modin_series = pd.Series(data)
hasattr(modin_series.sample(n=0, random_state=21019), "index")
```
I have error:
```
KeyError: 'Column F___reduced__ does not exist in schema'
```
Also function ``repeat`` have this problem if run: 
``hasattr(modin_series.repeat(0), "index")``
Also function ``Series.empty`` have this error:
```
modin_series = pd.Series()
modin_series.empty
```

**Comment by vnlitvinov** [comment] 2022-08-29 13:53
@modin-project/modin-omnisci  could someone please check if this still happens?

**Comment by AndreyPavlenko** [comment] 2022-09-21 10:38
Should be fixed by #4910

**Comment by YarShev** [comment] 2022-09-27 18:14
@AndreyPavlenko, #4910 is merged. Should we close this issue?

**Comment by AndreyPavlenko** [comment] 2022-09-27 18:23
The issue is not reproducible after the merge, however, the following warning is printed:
UserWarning: Frame contain columns with unsupported data-types: ['F___reduced__']. All operations with this frame will be default to pandas!

**Comment by YarShev** [comment] 2022-09-27 18:38
Okay, that looks like a separate feature to implement so I am closing this issue.

**Closed by YarShev** 2022-09-27 18:38 UTC
Labels: bug 🦗, pandas concordance 🐼, OmniSci, P3
