### ISSUE TITLE
`corr` and `cov` is slower in Modin

### ISSUE THREAD

**Issue by dorisjlee** [modin-project/modin#4560] opened 2022-06-08 23:46 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOSX
- **Modin version** (`modin.__version__`): 0.15.0
- **Python version**: Python 3.9.9
- **Code we can use to reproduce**:

> Timing code: [cov_corr.ipynb.zip](https://github.com/modin-project/modin/files/8865619/cov_corr.ipynb.zip)
> Data: [synthetic_100_31622.parquet.gz](https://github.com/modin-project/modin/files/8865593/synthetic_100_31622.parquet.gz)

### Describe the problem
`corr` and `cov` take longer in pandas. When I run scalability experiments where the number of rows (up to 1M) is varied, the Modin runtime increases at a faster rate as we increase the number of rows.
<img src="https://user-images.githubusercontent.com/5554675/172734380-702085b3-036f-41f3-bbe7-97c3925c9c1b.png" width=400></img>

**Comment by mvashishtha** [comment] 2022-06-09 19:06
@dorisjlee thanks for reporting this issue. I get similar results on my mac. `corr` on the whole dataframe from your file takes 112 sec on Modin and 16.1 sec on pandas. Here's a self-contained reproducer where the corr takes 78 sec in modin and 12 sec in pandas.

```python
import modin.pandas as pd
import numpy as np
from modin.config import BenchmarkMode
import pandas
import time

BenchmarkMode.put(True)

np.random.seed(0)
pdf = pandas.DataFrame(np.random.randint(0, 100, size=(2**19, 100)))
start = time.time()
pdf.corr()
end = time.time()
print(f'pandas corr took {end - start}')
df = pd.DataFrame(pdf)
start = time.time()
df.corr()
end = time.time()
print(f'modin corr took {end - start}')

```

`cov` is similar: 5.2 sec on modin and 1.6 sec on pandas.

I dug into the performance with `ray timeline` (corr and cov timelines for the reproducer attached here). It looks like Modin is slow because the distributed full-axis tasks are way too slow, e.g. 76 sec for each of the 3 larger (32 column as opposed to 4 column) column partitions for `corr`. That function for both `cov` and `corr` is [here](https://github.com/modin-project/modin/blob/bd3f3719c46a0f133e0abd8a9be4a4f7adab3724/modin/core/storage_formats/pandas/query_compiler.py#L1658).

@YarShev I see that you implemented the initial version of that function in #2130. Did you do any performance testing then? How could we speed up the remote tasks? Is there any way to use the pandas `corr` and `cov` implementation?

[ray timelines](https://github.com/modin-project/modin/files/8873169/Archive.zip)

**System Specs**
- macOSMonterey 12.2.1
- MacBook Pro (16-inch, 2019)
- 2.3 GHz 8-Core Intel Core i9
- 16 GB 2667 MHz DDR4

**Comment by YarShev** [comment] 2022-06-09 19:55
This is a duplicate of #2399. The initial version of the corr/cov was implemented in #2130. We didn't benchmark it well then but IIRC, the performance was near the same as in pandas by using some big dataset, but I am not sure of the exact shape. Still, yes, we definitely need to improve the corr/cov operations. There was an attempt for this as part of #2400 where we introduced a new Modin dataframe's operator but decided not to add it because of its doubtful performance. There is a number of ways we can go with but probably not limited to.

1. Sharpen the new operator introduced in #2400 to see if it is beneficial for all/most cases.
2. Try to transpose self in the remote tasks.
3. 2 + broadcast right/other dataframe to the left row partitions in order to transform it to a numpy array in the remote tasks instead of doing this in the main thread.

@mvashishtha, would you be willing to tackle this? If any question arises, feel free to ask me.

**Comment by mvashishtha** [comment] 2022-06-10 19:58
@YarShev thank you, that's very helpful. I'll mark #2399 as a duplicate of this issue because this issue has so many details now.

> @mvashishtha, would you be willing to tackle this? If any question arises, feel free to ask me.

Unfortunately, I can't take this on for now.

**Closed** 2023-06-06 18:57 UTC
Labels: Performance 🚀, P2

**Comment by dchigarev** [comment] 2023-06-08 11:38
#6193 only fixed the perf for `.corr()` method. Here's a separate issue for `.cov()`: #6248
