### ISSUE TITLE
Verify dtypes equality in tests

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#5956] opened 2023-04-07 15:14 UTC
We currently don't do so

--
Note: this issue is a part of an epic https://github.com/modin-project/modin/issues/3804

**Comment by mvashishtha** [comment] 2023-04-10 22:15
Is this a duplicate of #3804?

**Comment by dchigarev** [comment] 2023-04-11 08:28
Right, thanks for the catch!

Thus closing this one as duplicated

**Comment by dchigarev** [comment] 2023-04-11 14:41
Although, let's reopen it and just put it as a child task of the #3804 epic

**Closed** 2023-04-13 14:05 UTC
Labels: bug 🦗, Testing 📈, P1
