### ISSUE TITLE
Paralell read_sql

### ISSUE THREAD

**Issue by rd5802** [modin-project/modin#418] opened 2019-01-17 23:07 UTC
Hello,

do you plan to implement parallel execution for pandas.read_sql ?

Dask has parallel access to databases but API is cumbersome and limited to queries written with sqlalchemy expressions.

I think pointing partitions would be an extra as a read_sql parameter (also number of threads/sessions to DB).

Regards,
RD

**Comment by rd5802** [comment] 2019-01-18 14:16
Thank very much !! :)

**Comment by igorborgest** [comment] 2019-01-28 20:56
Hey @devin-petersohn @rd5802

This feature seems to be one of the most used. I would like to try help here, besides I have some bias to want improve that as well.

I messed around with some alternatives here, and I think that the best way to be followed is made the API like the [pyspark.sql.DataFrameReader.jdbc](https://spark.apache.org/docs/2.4.0/api/python/pyspark.sql.html#pyspark.sql.DataFrameReader.jdbc) interface.

Unfortunately distributed SQL interface is something very hard to abstract. Later we could try do something that craw the primary key and automatically get the bounders values. But for now, I think that we could start like the Spark JDBC API and request the _Partition Column_ and the _bounders values_ in the arguments.

So the interface to distribute the queries will be a little different from the conventional pandas interface, but I can made it on a way that we can fallback to the original implementation.

Anyway, a snippet of code says more than a thousand of words, so I will submit a premature PR here and we can discuss the implementation.

After we agree to an approach, I can go back to my branch and implement all the good practices I've overlooked.

**Comment by igorborgest** [comment] 2019-01-28 21:02
Example:

```python
import modin.pandas as pd

string_uri = "sqlite:///test.db"
table = "tbl1"
query = "select * from tbl1;"

df = pd.read_sql(table, string_uri)  # fallback
df = pd.read_sql(query, string_uri)  # fallback
df = pd.read_sql(table, string_uri, partition_column="id", lower_bound=0, upper_bound=13)  # distributed
df = pd.read_sql(query, string_uri, partition_column="id", lower_bound=0, upper_bound=13)  # distributed
```

**Comment by rd5802** [comment] 2019-02-03 02:39
HI @igorborgest 

Looks like a good trail to follow Spark. 
Do you think of a `query` as really  arbitrary, including the where statement? `pyspark.sql.DataFrameReader.jdbc` has `predicates` to filter data.

I would consider number of maximum threads as a parameter. DBMS`s instances often have limitations on users which may make trouble while loading data, or you just want it to leave to modin number of processors parameter?

**Comment by devin-petersohn** [comment] 2019-02-03 04:20
Hey @rd5802, we have an experimental API that was merged as a part of #436. 

After you `pip install git+https://github.com/modin-project/modin` (current master branch) you can try it with this:

```python
import modin.experimental.pandas as pd 
import pandas 
import sqlite3 
import numpy as np 
filename = "test_from_sql.db" 
conn = sqlite3.connect(filename) 
table = "test_from_sql"
frame_data = np.random.randint(0, 100, size=(100, 100)) 
pandas.DataFrame(frame_data).add_prefix("col").to_sql(table, conn)
db_uri = "sqlite:///" + filename 
df = pd.read_sql("select * from {}".format(table), db_uri, partition_column="[index]", lower_bound=0, upper_bound=100)
```

For this case, `query` can be an arbitrary query, so something like `predicates` shouldn't be necessary. You raise a very good point about process number, that is something we will have to look into. Right now it is defaulting to the number of cores on the machine, but that could be problematic on larger machines. Each process creates its own connection, so we may have to force limit the parallelism on the Modin side.

We could add a parameter for number of connections/processes in the `experimental` API. Would you prefer a parameter?

**Comment by rd5802** [comment] 2019-02-03 12:34
Hey @devin-petersohn,

Yes, I want a parameter !!!  E.g.  **max_connections**, **connections** or **parallelism** .

**Comment by rd5802** [comment] 2019-02-04 20:53
Hi @devin-petersohn,
I run the cone after `pip install`, it says `ModuleNotFoundError: No module named 'modin.experimantal'`

> Hey @rd5802, we have an experimental API that was merged as a part of #436.
> 
> After you `pip install git+https://github.com/modin-project/modin` (current master branch) you can try it with this:
> 
> ```python
> import modin.experimental.pandas as pd 
> import pandas 
> import sqlite3 
> import numpy as np 
> filename = "test_from_sql.db" 
> conn = sqlite3.connect(filename) 
> table = "test_from_sql"
> frame_data = np.random.randint(0, 100, size=(100, 100)) 
> pandas.DataFrame(frame_data).add_prefix("col").to_sql(table, conn)
> db_uri = "sqlite:///" + filename 
> df = pd.read_sql("select * from {}".format(table), db_uri, partition_column="[index]", lower_bound=0, upper_bound=100)
> ```
> 
> For this case, `query` can be an arbitrary query, so something like `predicates` shouldn't be necessary. You raise a very good point about process number, that is something we will have to look into. Right now it is defaulting to the number of cores on the machine, but that could be problematic on larger machines. Each process creates its own connection, so we may have to force limit the parallelism on the Modin side.
> 
> We could add a parameter for number of connections/processes in the `experimental` API. Would you prefer a parameter?

**Comment by rd5802** [comment] 2019-02-04 21:11
Hi @devin-petersohn,
I run the cone after `pip install`, it says `ModuleNotFoundError: No module named 'modin.experimantal'`

Regards,

RD

> Hey @rd5802, we have an experimental API that was merged as a part of #436.
> 
> After you `pip install git+https://github.com/modin-project/modin` (current master branch) you can try it with this:
> 
> ```python
> import modin.experimental.pandas as pd 
> import pandas 
> import sqlite3 
> import numpy as np 
> filename = "test_from_sql.db" 
> conn = sqlite3.connect(filename) 
> table = "test_from_sql"
> frame_data = np.random.randint(0, 100, size=(100, 100)) 
> pandas.DataFrame(frame_data).add_prefix("col").to_sql(table, conn)
> db_uri = "sqlite:///" + filename 
> df = pd.read_sql("select * from {}".format(table), db_uri, partition_column="[index]", lower_bound=0, upper_bound=100)
> ```
> 
> For this case, `query` can be an arbitrary query, so something like `predicates` shouldn't be necessary. You raise a very good point about process number, that is something we will have to look into. Right now it is defaulting to the number of cores on the machine, but that could be problematic on larger machines. Each process creates its own connection, so we may have to force limit the parallelism on the Modin side.
> 
> We could add a parameter for number of connections/processes in the `experimental` API. Would you prefer a parameter?

**Comment by rd5802** [comment] 2019-02-13 20:42
Works like a charm.


> Were you able to install from master? We haven't released a version with this to pypi so you have to pip install with the specific command for `git`.


> 
> Docs:
> https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch

**Comment by Shellcat-Zero** [comment] 2019-04-17 21:54
Not sure if this is relevant, but for anyone interested in reading about how parallel read queries are currently accomplished with SQLalchemy and Dask, their discussion on the issue is located at https://github.com/dask/dask/issues/2604.

**Comment by devin-petersohn** [comment] 2019-04-17 22:18
Thanks @Shellcat-Zero, We do have a way to do this already, merged in #499. Feel free to try it out!

There is also an experimental API that uses hints similar to the Spark SQL API #436.

**Comment by Shellcat-Zero** [comment] 2019-04-17 22:48
Thanks @devin-petersohn.  Most generally I think a common use case with Dask at least is to apply dataframe or machine learning operations across a cluster, and their implementation (discussed in the link provided) I believe will distribute partitions of the query across the cluster nodes, whereas my understanding of this implementation with Modin is that it is doing a parallel read into the partitions of a dataframe on a single machine.  

As a new user to Modin, I haven't found much documentation yet on clustering as one might do with Dask, or if that is a desired feature for Modin. If that is a currently supported, I was wondering if you could point me to the relevant documentation.

**Comment by Shellcat-Zero** [comment] 2019-04-17 23:02
Sorry for the noise, I believe I found what I was looking for: https://modin.readthedocs.io/en/latest/using_modin.html#using-modin-on-a-cluster

**Comment by devin-petersohn** [comment] 2019-04-21 01:45
I am going to close this issue as it has been implemented.

@Shellcat-Zero if you have a question on cluster usage, I am happy to discuss in a new issue.

**Closed by devin-petersohn** 2019-04-21 01:45 UTC
Labels: Help Wanted :globe_with_meridians:, new feature/request :speech_balloon:
