### ISSUE TITLE
Crash when read file which is not csv format

### ISSUE THREAD

**Issue by RexHuang** [modin-project/modin#4400] opened 2022-04-20 10:14 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.14.0
- **Python version**: 3.8.12
- **Exact command to reproduce**:

%time data=pd.read_csv("/mnt/somefile1", header=None)
the file size is 9.3G, with 46M lines, it's not csv format, but long line data (200 chars).
scheduler_ui shows it's not using dask workers.

Read file with csv format is ok.

### Describe the problem

notebook popup error message:
Kernel Restarting
The kernel for myKernel/modin_sample1.ipynb appears to have died. It will restart automatically.

k8s events:
System OOM encountered, victim process: python, pid: 31549

### Source code / logs

> 

---------------------
import os
os.environ["MODIN_ENGINE"] = "dask"

import modin.config as cfg
cfg.Engine.put('dask')
cfg.StorageFormat.put('pandas')

from dask.distributed import Client, config
client = Client()
%time data=pd.read_csv("/mnt/somefile1", header=None)

**Comment by mvashishtha** [comment] 2022-04-20 15:27
@RexHuang thank you for reporting the issue. What you mean by "long line data"? Are you able to share the file you're trying to read, or a sample from that file? It would be very helpful if you could give us any file that reproduces the bug with the script you've given.

**Comment by RexHuang** [comment] 2022-04-21 01:39
@mvashishtha just some text, the following is one line of data:
233793597118133617852155338099        464943416450946331823          23169092895151763944945757  0853455.648                    923.613294.006000      5896.4257 3635099975704339913919795200812200

**Comment by mvashishtha** [comment] 2022-04-21 16:28
@RexHuang I can't reproduce the error with a file containing just the URL-decoded version of that line. Both modin-on-dask and pandas give me

```
Empty DataFrame
Columns: [233793597118133617852155338099        464943416450946331823          23169092895151763944945757  0853455.648                    923.613294.006000      5896.4257 3635099975704339913919795200812200]
Index: []
```

It looks like this bug might only apply to sufficiently large datasets. How long does the `read_csv` take in the regular CSV version of your file?

**Comment by mvashishtha** [comment] 2022-09-22 03:01
@RexHuang because we don't have the answers to my questions from 5 months ago and this issue still doesn't have a reproducer, I'm going to close this issue. If you can provide more information or you have more questions, please post here. The Modin contributors are always happy to help.

**Closed by mvashishtha** 2022-09-22 03:01 UTC
Labels: Needs more information ❔, pandas.io, P3
