### ISSUE TITLE
[ASV] performance regression in sort_values operation

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2927] opened 2021-03-25 11:18 UTC
Pandas_on_ray engine - 44 cpus

Benchmark | Commit | Factor | Before | After
-- | -- | -- | -- | --
benchmarks.TimeSortValues.time_sort_values((5000, 5000), 1, True) | 7c46bddc | 1.23x | 2.389s | 2.930s
benchmarks.TimeSortValues.time_sort_values((5000, 5000), 1, False) | 7c46bddc | 1.23x | 2.384s | 2.932s

**Comment by anmyachev** [comment] 2021-03-25 11:49
Feel free to reassign.

**Comment by RehanSD** [comment] 2022-10-12 01:28
Duplicate of #3535

**Closed** 2022-10-12 01:28 UTC
Labels: Performance 🚀, Regression ↩️
