### ISSUE TITLE
Bunch of issues with arrow format in omnisci engine

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1704] opened 2020-07-09 14:57 UTC
- test_truediv_list
- test_floordiv_list
- test_insert

**Comment by fexolm** [comment] 2020-07-10 13:57
The problem is because arrow supports only decimal128 type, and omnisci supports decimal16, decimal32 and decimal64 types. In FSI we do a conversion from arrow's decimals to omnisci's. But arrowConverter does not provide such functionality. 
The workaround could be just converting decimal columns to double before materialization. 
I've created an issue in arrow repository https://issues.apache.org/jira/browse/ARROW-9404 to decide which way we act when we implement proper solution for this.

**Comment by ienkovich** [comment] 2020-07-15 11:49
In our tests we don't use decimal types right now, so decimal formats shouldn't be the issue.

**Comment by ienkovich** [comment] 2020-07-15 11:50
test_insert is fixed by intel-go/modin#59

**Closed** 2020-07-24 15:13 UTC
Labels: OmniSci
