### ISSUE TITLE
RayTaskError: ray_worker

### ISSUE THREAD

**Issue by 4pygmalion** [modin-project/modin#851] opened 2019-11-01 00:07 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu-18.04-bionic
- **Modin installed from (source or binary)**: using pip
- **Modin version**: '0.6.2'
- **Python version**: 3.6.8
- **Exact command to reproduce**:
import modin.pandas as pd
modin_csv_data = pd.read_csv('/home/user/jupyter/Hoheon/Noom/Global/Data/wtLogsUS.csv')

### Describe the problem

I have tried to read my CSV file using modin. however, this error occurs.
how do I handle this error? and why this error occurs?

### Source code / logs

ayTaskError                              Traceback (most recent call last)
<ipython-input-20-d07a4d232530> in <module>()
      1 # %%time
      2 import modin.pandas as pd
----> 3 modin_csv_data = pd.read_csv('/home/user/jupyter/Hoheon/Noom/Global/Data/wtLogsUS.csv')

~/.local/lib/python3.6/site-packages/modin/pandas/io.py in parser_func(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
     95         if not kwargs.get("sep", sep):
     96             kwargs["sep"] = "\t"
---> 97         return _read(**kwargs)
     98 
     99     return parser_func

~/.local/lib/python3.6/site-packages/modin/pandas/io.py in _read(**kwargs)
    108         kwargs: Keyword arguments in pandas.read_csv
    109     """
--> 110     pd_obj = BaseFactory.read_csv(**kwargs)
    111     # This happens when `read_csv` returns a TextFileReader object for iterating through
    112     if isinstance(pd_obj, pandas.io.parsers.TextFileReader):

~/.local/lib/python3.6/site-packages/modin/data_management/factories.py in read_csv(cls, **kwargs)
     50     @classmethod
     51     def read_csv(cls, **kwargs):
---> 52         return cls._determine_engine()._read_csv(**kwargs)
     53 
     54     @classmethod

~/.local/lib/python3.6/site-packages/modin/data_management/factories.py in _read_csv(cls, **kwargs)
     54     @classmethod
     55     def _read_csv(cls, **kwargs):
---> 56         return cls.io_cls.read_csv(**kwargs)
     57 
     58     @classmethod

~/.local/lib/python3.6/site-packages/modin/engines/ray/generic/io.py in read_csv(cls, filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    680         if cls.read_csv_remote_task is None:
    681             return super(RayIO, cls).read_csv(**kwargs)
--> 682         return cls._read(**kwargs)
    683 
    684     @classmethod

~/.local/lib/python3.6/site-packages/modin/engines/ray/generic/io.py in _read(cls, filepath_or_buffer, **kwargs)
    766             return cls._read_csv_from_pandas(filepath_or_buffer, filtered_kwargs)
    767         else:
--> 768             return cls._read_csv_from_file_ray(filepath_or_buffer, filtered_kwargs)
    769 
    770     @classmethod

~/.local/lib/python3.6/site-packages/modin/engines/ray/generic/io.py in _read_csv_from_file_ray(cls, filepath, kwargs)
    490         # or based on the column(s) that were requested.
    491         if index_col is None:
--> 492             row_lengths = ray.get(index_ids)
    493             new_index = pandas.RangeIndex(sum(row_lengths))
    494         else:

~/.local/lib/python3.6/site-packages/ray/worker.py in get(object_ids)
   2245             if isinstance(value, RayError):
   2246                 last_task_error_raise_time = time.time()
-> 2247                 raise value
   2248 
   2249         # Run post processors.

RayTaskError: ray_worker (pid=54253, host=ubuntu1804)
TypeError: f() takes 0 positional arguments but 6 were given

**Comment by devin-petersohn** [comment] 2019-11-01 00:46
Hi @4pygmalion, thanks for posting!

Would you run the following and paste the output?

```python
import ray
ray.init()
import modin.pandas as pd
modin_csv_data = pd.read_csv('/home/user/jupyter/Hoheon/Noom/Global/Data/wtLogsUS.csv')
```

Thanks for the detail! I am hoping ray will provide more information with the default settings.

**Comment by 4pygmalion** [comment] 2019-11-01 01:06
Thank you for your quick reply.

I have run your code. however, exception error occurred. 

-------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-8-8f730b448cf3> in <module>()
      1 import ray
      2 # ray.shutdown()
----> 3 ray.init()
      4 import modin.pandas as pd
      5 

~/.local/lib/python3.6/site-packages/ray/worker.py in init(redis_address, num_cpus, num_gpus, resources, object_store_memory, redis_max_memory, log_to_driver, node_ip_address, object_id_seed, local_mode, redirect_worker_output, redirect_output, ignore_reinit_error, num_redis_shards, redis_max_clients, redis_password, plasma_directory, huge_pages, include_webui, job_id, configure_logging, logging_level, logging_format, plasma_store_socket_name, raylet_socket_name, temp_dir, load_code_from_local, _internal_config)
   1381             return
   1382         else:
-> 1383             raise Exception("Perhaps you called ray.init twice by accident? "
   1384                             "This error can be suppressed by passing in "
   1385                             "'ignore_reinit_error=True' or by calling "

Exception: Perhaps you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.


--------------------------------------------------------------------

So, i tried to pass argument such as ignore_reinit_error=True in ray.init() and called 'ray.shutdown()' prior to 'ray.init()'. but, long repated error was printed.. ;; 


2019-11-01 10:05:39,284	WARNING worker.py:1373 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
2019-11-01 10:05:39,286	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-11-01_10-05-39_286072_10699/logs.
2019-11-01 10:05:39,394	WARNING services.py:766 -- Redis failed to start, retrying now.
2019-11-01 10:05:39,501	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:39351 to respond...
2019-11-01 10:05:39,610	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:11274 to respond...
2019-11-01 10:05:39,612	INFO services.py:809 -- Starting Redis shard with 10.0 GB max memory.
2019-11-01 10:05:39,625	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-11-01_10-05-39_286072_10699/logs.
2019-11-01 10:05:39,626	WARNING services.py:1301 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2019-11-01 10:05:39,627	INFO services.py:1475 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
2019-11-01 10:05:40,850	ERROR worker.py:1714 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_csv_with_offset_pandas_on_ray' with function ID 26ac71d4188b72b6baa1ad33b41fd1e4a03cbf11. Traceback:
Traceback (most recent call last):
  File "/home/hoheon/.local/lib/python3.6/site-packages/ray/function_manager.py", line 424, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
  File "/home/hoheon/.local/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/io.py", line 8, in <module>
    from modin.engines.ray.pandas_on_ray.frame.data import PandasOnRayFrame
  File "/home/hoheon/.local/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/frame/data.py", line 5, in <module>
    from modin.engines.base.frame.data import BasePandasFrame
  File "/home/hoheon/.local/lib/python3.6/site-packages/modin/engines/base/frame/data.py", line 6, in <module>
    from pandas.core.index import ensure_index
ImportError: cannot import name 'ensure_index'


RayTaskError                              Traceback (most recent call last)
<ipython-input-9-5fd6eaddf60e> in <module>()
      4 import modin.pandas as pd
      5 
----> 6 modin_csv_data = pd.read_csv('/home/user/jupyter/Hoheon/Noom/Global/Data/wtLogsUS.csv')

~/.local/lib/python3.6/site-packages/modin/pandas/io.py in parser_func(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
     95         if not kwargs.get("sep", sep):
     96             kwargs["sep"] = "\t"
---> 97         return _read(**kwargs)
     98 
     99     return parser_func

~/.local/lib/python3.6/site-packages/modin/pandas/io.py in _read(**kwargs)
    108         kwargs: Keyword arguments in pandas.read_csv
    109     """
--> 110     pd_obj = BaseFactory.read_csv(**kwargs)
    111     # This happens when `read_csv` returns a TextFileReader object for iterating through
    112     if isinstance(pd_obj, pandas.io.parsers.TextFileReader):

~/.local/lib/python3.6/site-packages/modin/data_management/factories.py in read_csv(cls, **kwargs)
     50     @classmethod
     51     def read_csv(cls, **kwargs):
---> 52         return cls._determine_engine()._read_csv(**kwargs)
     53 
     54     @classmethod

~/.local/lib/python3.6/site-packages/modin/data_management/factories.py in _read_csv(cls, **kwargs)
     54     @classmethod
     55     def _read_csv(cls, **kwargs):
---> 56         return cls.io_cls.read_csv(**kwargs)
     57 
     58     @classmethod

~/.local/lib/python3.6/site-packages/modin/engines/ray/generic/io.py in read_csv(cls, filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    680         if cls.read_csv_remote_task is None:
    681             return super(RayIO, cls).read_csv(**kwargs)
--> 682         return cls._read(**kwargs)
    683 
    684     @classmethod

~/.local/lib/python3.6/site-packages/modin/engines/ray/generic/io.py in _read(cls, filepath_or_buffer, **kwargs)
    766             return cls._read_csv_from_pandas(filepath_or_buffer, filtered_kwargs)
    767         else:
--> 768             return cls._read_csv_from_file_ray(filepath_or_buffer, filtered_kwargs)
    769 
    770     @classmethod

~/.local/lib/python3.6/site-packages/modin/engines/ray/generic/io.py in _read_csv_from_file_ray(cls, filepath, kwargs)
    490         # or based on the column(s) that were requested.
    491         if index_col is None:
--> 492             row_lengths = ray.get(index_ids)
    493             new_index = pandas.RangeIndex(sum(row_lengths))
    494         else:

~/.local/lib/python3.6/site-packages/ray/worker.py in get(object_ids)
   2245             if isinstance(value, RayError):
   2246                 last_task_error_raise_time = time.time()
-> 2247                 raise value
   2248 
   2249         # Run post processors.

RayTaskError: ray_worker (pid=13373, host=ubuntu1804)
TypeError: f() takes 0 positional arguments but 6 were given

**Comment by devin-petersohn** [comment] 2019-11-01 01:17
Could you restart the interpreter/kernel and try again?

**Comment by devin-petersohn** [comment] 2019-11-01 20:32
Hi @4pygmalion, just want to make sure we don't lose track of this.

If you have the chance, please restart the interpreter or notebook kernel and re-run the code so that we can force Ray to give a more descriptive output. Thanks!

**Comment by devin-petersohn** [comment] 2022-03-21 19:08
Closing as we are unable to reproduce the issue. Please feel free to reopen if you have a way that we can reproduce this.

**Closed by devin-petersohn** 2022-03-21 19:08 UTC
Labels: Needs more information ❔
