### ISSUE TITLE
Pandas-esque groupby apply

### ISSUE THREAD

**Issue by timothylunaxj4s** [modin-project/modin#4165] opened 2022-02-04 21:18 UTC
I would like to perform arbitrary groupby apply, similarly to a Pandas operation; that's not currently possible with the following example (most likely due to partitioning).

If I have multiple groups in my data (say I have a population composed of Squorks and Sqeebs) I am interested in applying *arbitrary* functionality to them.

As an example, let's investigate the how the Squorks and Sqeebs do for the following academic subjects, dependent on their hair color. Yes, it's silly and it can be changed, but it helps to illustrate the issue.

```python
>>> import pandas as pd
>>> from numpy.random import default_rng
>>> rng = default_rng(0)

>>> silly_example = pd.DataFrame({
...     'GROUP': ['SQUORK'] * 50 + ['SQUEEB'] * 50,
...     'CLASS': rng.choice(['ECON', 'CALC', 'FOODSKILLS'], size=100, p = [.1, .2, .7]),
...     'HAIRCOLOR': rng.choice(['BLUE', 'RED', 'GREEN'], size=100),
...     'GRADE': rng.uniform(low=.7, high=1., size=100)
... })

>>> def agg_func(dataset: pd.DataFrame) -> pd.DataFrame:
...     """Compute arbitrary function on dataset.
... 
...     Parameters
...     ----------
...     dataset: pd.DataFrame
...         This is a Pandas API compliant DataFrame
... 
...     Returns
...     -------
...     arbitrarily_modified_data: pd.DataFrame
...         This is a Pandas API compliant DataFrame
...     """
...     # If thise are Blue Haired Squorks we return nothing.
...     if dataset.GROUP.unique() == np.array(['SQUORK']):
...         _dataset = dataset.query('HAIRCOLOR != "BLUE"')
...     else:
...         _dataset = dataset
...     if _dataset.empty:
...         # Strip the schema information.
...         return pd.DataFrame()
...     # Now we are going to aggregate this dataset.
...     return _dataset.groupby(['CLASS', 'HAIRCOLOR']).agg({'GRADE': 'mean'})

>>> silly_example.groupby('GROUP').apply(agg_func)
                                GRADE
GROUP  CLASS      HAIRCOLOR          
SQUEEB CALC       BLUE       0.882189
                  GREEN      0.829878
                  RED        0.816420
       ECON       BLUE       0.923229
                  GREEN      0.805892
       FOODSKILLS BLUE       0.846946
                  GREEN      0.835343
                  RED        0.888975
SQUORK CALC       GREEN      0.833141
                  RED        0.903995
       ECON       GREEN      0.993480
                  RED        0.910935
       FOODSKILLS GREEN      0.892069
                  RED        0.819142
```

This is obviously a highly contrived example, but in this example the groupby function expects to have access to the entire schema of the dataset (all columns, regardless of the 'vertical partition') but there is no expectation of an environmental scope outside of the vertical partition.

Modin breaks when it attempts to do this for particular schema when it happens to map them across different horizontal partitions.

Being able to groupby apply, especially if it was distributed computation 'out of the box' would be pretty handy. [I've started an MR](https://github.com/StateFarmIns/modin/tree/groupbyapply-parallel) where I'll be contributing towards this as I am able.

**Comment by devin-petersohn** [comment] 2022-02-14 22:07
Hi @timothylunaxj4s thanks for posting!

We have some work on the ability to split/shuffle in progress and the groupby algebraic operator is here: https://github.com/modin-project/modin/blob/b7027597985a442734a57949d72e3fa0625b4d43/modin/core/dataframe/pandas/dataframe/dataframe.py#L2540-L2580

It takes an `op`, which could be any other algebraic operation, including `map`, `reduce` or `mask` (these are the algebraic operator names.

**Comment by devin-petersohn** [comment] 2022-02-28 21:43
@timothylunaxj4s Yes! @RehanSD has been thinking about this problem and can probably have a better suggestion than I would.

**Comment by mvashishtha** [comment] 2022-07-12 04:33
Duplicate of #3435

**Closed by mvashishtha** 2022-07-12 04:33 UTC
Labels: pandas.groupby
