### ISSUE TITLE
Modin on OmniSci constructs incorrect frame when 'dtype=datetime'

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1968] opened 2020-08-27 11:24 UTC
### System information
- **OmniSci branch**: [intel-go/omniscidb/gal/fix_pytests](https://github.com/intel-go/omniscidb/tree/gal/fix_pytests)
- **Modin branch**: [intel-go/modin/omnisci-on-ray](https://github.com/intel-go/modin/tree/omnisci-on-ray)
- **Code we can use to reproduce**:
```python
import os

os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_ENGINE"] = "ray"
os.environ["MODIN_BACKEND"] = "omnisci"

if __name__ == "__main__":
    import modin.pandas as pd
    import pandas

    data = pd.date_range("2016-12-31", periods=128, freq="D", tz="Europe/Berlin")
    modin_series = pd.Series(data)
    pandas_series = pandas.Series(data)
    print(f"{len(pandas_series)} != {len(modin_series)}") # Output: 128 != 32

    print("pandas_series:\n", pandas_series, sep="")
    print("modin_series:\n", modin_series, sep="")

```

<details><summary>Output</summary>

```
128 != 32
pandas_series:
0     2016-12-31 00:00:00+01:00
1     2017-01-01 00:00:00+01:00
2     2017-01-02 00:00:00+01:00
3     2017-01-03 00:00:00+01:00
4     2017-01-04 00:00:00+01:00
                 ...
123   2017-05-03 00:00:00+02:00
124   2017-05-04 00:00:00+02:00
125   2017-05-05 00:00:00+02:00
126   2017-05-06 00:00:00+02:00
127   2017-05-07 00:00:00+02:00
Length: 128, dtype: datetime64[ns, Europe/Berlin]
modin_series:
0    2016-12-30 23:00:00
1    2016-12-31 23:00:00
2    2017-01-01 23:00:00
3    2017-01-02 23:00:00
4    2017-01-03 23:00:00
5    2017-01-04 23:00:00
6    2017-01-05 23:00:00
7    2017-01-06 23:00:00
8    2017-01-07 23:00:00
9    2017-01-08 23:00:00
10   2017-01-09 23:00:00
11   2017-01-10 23:00:00
12   2017-01-11 23:00:00
13   2017-01-12 23:00:00
14   2017-01-13 23:00:00
15   2017-01-14 23:00:00
16   2017-01-15 23:00:00
17   2017-01-16 23:00:00
18   2017-01-17 23:00:00
19   2017-01-18 23:00:00
20   2017-01-19 23:00:00
21   2017-01-20 23:00:00
22   2017-01-21 23:00:00
23   2017-01-22 23:00:00
24   2017-01-23 23:00:00
25   2017-01-24 23:00:00
26   2017-01-25 23:00:00
27   2017-01-26 23:00:00
28   2017-01-27 23:00:00
29   2017-01-28 23:00:00
30   2017-01-29 23:00:00
31   2017-01-30 23:00:00
dtype: datetime64[ns]
```

</details>

### Describe the problem
Resulted frame has incorrect length

**Comment by ienkovich** [comment] 2020-09-01 14:40
Something wrong happens with the frame on the way to the OmniSci partition. If I try to print it in `OmnisciOnRayFramePartition.put` it looks like it has 128 rows, but if I try to call `DataFrame.to_csv` for this frame then I get
```
IndexError: index 32 is out of bounds for axis 0 with size 32
```
I'll look further.

**Comment by ienkovich** [comment] 2020-09-01 15:20
Looks like the problem is in Pandas itself triggered in `BaseFrameManager.from_pandas`. Here we compute `row_chunksize` and `col_chunksize` which seem to be at least 32 by default. Then we perform `df.iloc[0 : 128, 0 : 32]` for the frame with a single column and the result is a broken frame. Here is a reproducer on Pandas:
```
import pandas
data = pd.date_range("2016-12-31", periods=128, freq="D", tz="Europe/Berlin")
df = pandas.DataFrame(data)
df = df.iloc[0 : 128, 0 : 32]
print(df)
```
The output is:
```
                            0
0   2016-12-31 00:00:00+01:00
1   2017-01-01 00:00:00+01:00
2   2017-01-02 00:00:00+01:00
3   2017-01-03 00:00:00+01:00
4   2017-01-04 00:00:00+01:00
..                        ...
123 2017-01-27 00:00:00+01:00
124 2017-01-28 00:00:00+01:00
125 2017-01-29 00:00:00+01:00
126 2017-01-30 00:00:00+01:00
127 2017-01-31 00:00:00+01:00

[128 rows x 1 columns]
```
Here index seems to have 128 elements but the last row is the 32nd row of the original frame. Attempt to dump this frame into CSV would cause an error:
```
IndexError: index 32 is out of bounds for axis 0 with size 32
```
According to Pandas's doc slice indexers allow out-of-bounds indexing, so problem is in Pandas.

**Comment by ienkovich** [comment] 2020-09-01 15:20
This issue is resolved in Pandas 1.1.1

**Comment by ienkovich** [comment] 2020-09-01 15:24
I saw the work for Pandas 1.1 support is in progress. Are we going to fully migrate to the latest Pandas version? Do we need to support Pandas 1.0.5 and avoid out-of-bounds indexing in partitioner? @devin-petersohn @Garra1980

**Comment by Garra1980** [comment] 2020-09-04 13:55
I suppose we wait Pandas 1.1 support

**Comment by devin-petersohn** [comment] 2020-09-04 17:54
Yes #1840 is in progress.

**Comment by YarShev** [comment] 2020-09-21 06:10
#1840 is closed. Now we are on pandas==1.1.2.

**Comment by ienkovich** [comment] 2020-09-21 17:23
The series length is correct now for this case.

**Closed by ienkovich** 2020-09-21 17:23 UTC
Labels: OmniSci, bug :bug:
