### ISSUE TITLE
BUG: unable to read partitioned parquet

### ISSUE THREAD

**Issue by kukushking** [modin-project/modin#5159] opened 2022-10-26 16:10 UTC
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
df = pd.DataFrame({"c0": [1.1, 2.2], "par": ["a", "b"]})
path = "s3://..."
df.to_parquet(path, partition_cols=["par"])
dfr = pd.read_parquet(path)

...

  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/error_message.py", line 80, in catch_bugs_and_request_email
    raise Exception(
Exception: Internal Error. Please visit https://github.com/modin-project/modin/issues to file an issue with the traceback and the command that caused this error. If you can't file a GitHub issue, please email bug_reports@modin.org.
Internal and external indices on axis 1 do not match.
```

### Issue Description

Hi folks, reading partitioned parquet raises "Exception: Internal Error... Internal and external indices on axis 1 do not match.". 
Confirmed this is an issue in main, version: `'0.16.0+24.g11ba481'`.

### Expected Behavior

Pandas 1.5.1: 
```
import pandas as pd
df = pd.DataFrame({"c0": [1.1, 2.2], "par": ["a", "b"]})
path = "s3://.../df.parquet"
df.to_parquet(path, partition_cols=["par"])
dfr = pd.read_parquet(path)
dfr
Out[8]: 
    c0 par
0  1.1   a
1  2.2   b
```

### Error Logs

<details>

```python-traceback

dfr = pd.read_parquet(path)
Traceback (most recent call last):
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-ad364b2ce2e2>", line 1, in <cell line: 1>
    dfr = pd.read_parquet(path)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/_compat/pandas_api/latest/io.py", line 291, in read_parquet
    query_compiler=FactoryDispatcher.read_parquet(
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/core/execution/dispatching/factories/dispatcher.py", line 180, in read_parquet
    return cls.__factory._read_parquet(**kwargs)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/core/execution/dispatching/factories/factories.py", line 207, in _read_parquet
    return cls.io_cls.read_parquet(**kwargs)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/core/io/file_dispatcher.py", line 164, in read
    if hasattr(query_compiler, "dtypes") and any(
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py", line 310, in dtypes
    return self._modin_frame.dtypes
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 311, in dtypes
    self._dtypes = self._compute_dtypes()
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 330, in _compute_dtypes
    self.tree_reduce(0, lambda df: df.dtypes, dtype_builder)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 124, in run_f_on_minimally_updated_metadata
    result = f(self, *args, **kwargs)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py", line 3057, in to_pandas
    ErrorMessage.catch_bugs_and_request_email(
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/.../lib/python3.9/site-packages/modin/error_message.py", line 80, in catch_bugs_and_request_email
    raise Exception(
Exception: Internal Error. Please visit https://github.com/modin-project/modin/issues to file an issue with the traceback and the command that caused this error. If you can't file a GitHub issue, please email bug_reports@modin.org.
Internal and external indices on axis 1 do not match.
```

</details>

### Installed Versions

<details>

------------------
commit           : 3f01114dd9c8b09376ea77bae2f11d9abef99490
python           : 3.9.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_GB.UTF-8
Modin dependencies
------------------
modin            : 0.16.2
ray              : 2.0.1
dask             : None
distributed      : None
hdk              : None
pandas dependencies
-------------------
pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.5
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 21.3.1
Cython           : None
pytest           : 7.1.3
hypothesis       : None
sphinx           : 5.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.1.2
IPython          : 7.34.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.10.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by mvashishtha** [comment] 2022-10-26 17:38
@kukushking thanks for reporting this issue. I can reproduce it at Modin commit 11ba4811e6db11740e11fd33d3cdfba8ce5bec54 by writing the dataset as you specified to `s3://mahesh-vashishtha/modin_bug_5159_parquet/df.parquet` in my publicly readable bucket.

There are two problems here:

1) We try to default to pandas for any kind of partitioned parquet directories, but we don't detect partitioned parquet directories on s3 properly (#4636)
2) Without the default to pandas, I think we're using pandas to `read_parquet` each partition file, so each partition has the `c0` column but not a `par` column, because we completely ignore the `par=` parts. We get the internal error you showed because we've used some kind of parquet dataset metadata to find the columns. Solving this bug for our new `read_parquet` implementation, which parallelizes across both rows and columns, will take some more work.

I think we should fix #4636 for now so we can at least read without error, and then solve (2) separately in #5160.

I'm closing this bug in favor of #4636 for the bug fix and #5160 for the feature of reading partitioned directories.

P.S. Note also even our code for detecting column partitioning in local filesystems is buggy-- see #4637.

**Closed by mvashishtha** 2022-10-26 17:39 UTC
Labels: bug 🦗, pandas.io, P1
