### ISSUE TITLE
Task exception was never retrieved - freeze_support() 

### ISSUE THREAD

**Issue by gfelot** [modin-project/modin#1082] opened 2020-02-18 14:06 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin installed from (source or binary)**: `pip install modin[dask]` in a conda env
- **Modin version**: 0.70
- **Python version**: 3.7
- **Exact command to reproduce**: Change all my pandas import to a modin import in a working ETL/ML script

### Describe the problem
Script is blocked with an error

### Source code / logs
```
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: The Dask Engine for Modin is experimental.
UserWarning: The Dask Engine for Modin is experimental.
[...]
```

Then the same number of time this error
```
Traceback (most recent call last):
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\asyncio\tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\site-packages\distributed\nanny.py", line 243, in start
    response = await self.instantiate()
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\site-packages\distributed\nanny.py", line 326, in instantiate
    result = await self.process.start()
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\site-packages\distributed\nanny.py", line 514, in start
    await self.process.start()
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\site-packages\distributed\process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\site-packages\distributed\process.py", line 202, in _start
    process.start()
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\gfelot\.conda\envs\categorisation_incidents\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Comment by devin-petersohn** [comment] 2020-02-18 16:54
@gfelot thanks for reporting! This is a duplicate of #843. There should be a fix in that issue. If you have further questions/comments feel free to add them in #843.

**Closed by devin-petersohn** 2020-02-18 16:54 UTC
Labels: duplicate :recycle:
