### ISSUE TITLE
is possible to add DataFrame.to_excel function?

### ISSUE THREAD

**Issue by PeterPirog** [modin-project/modin#3269] opened 2021-07-22 21:35 UTC
Hello
I suggest to add DataFrame.to_excel function in modin.

Peter

**Comment by GeorgeAzaru** [comment] 2022-01-12 10:55
We definitely need this. Should get prioritized.

**Comment by YarShev** [comment] 2022-01-12 11:21
cc @devin-petersohn

**Comment by devin-petersohn** [comment] 2022-01-13 18:00
We will look into this. Excel as a format is not very conducive to distribution access, let alone distributed writes.

I have put an exploration on the roadmap for after this next release.

**Comment by RehanSD** [comment] 2022-10-12 03:02
Duplicate of #2565

**Closed by RehanSD** 2022-10-12 03:02 UTC
Labels: new feature/request 💬
