### ISSUE TITLE
Hi How to convert a pandas df to modin df

### ISSUE THREAD

**Issue by coolsubbu** [modin-project/modin#2574] opened 2020-12-30 09:18 UTC
This may be a trivial question. But I didnt find a method to convert a pandas dataframe to Modin dataframe.

**Comment by devin-petersohn** [comment] 2020-12-30 15:03
Hi @coolsubbu thanks for the question!

It is as simple as passing the pandas dataframe to the Modin dataframe constructor.

```python
import modin.pandas as pd

pandas_df = ...
modin_df = pd.DataFrame(pandas_df)
```

We do not document this because it is not recommended to run the two alongside each other. This is because pandas cannot accept Modin dataframe objects as input and it can be difficult to keep track of what type the objects are.

Thanks again for the question!

**Comment by yazeedhasan97** [comment] 2022-06-07 10:15
Hi @devin-petersohn 
I am trying to do something as follows. However, I think the module is missing my point

`
WORDS = mpd.DataFrame(df.reset_index())
tmp = WORDS.source.apply(lambda x: pd.value_counts(x.split())).sum(axis = 0)
tmp
`

this is the error message I get
`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [24], in <cell line: 4>()
      2 # WORDS = pd.concat(stream(np.array_split(df.source.astype(str), PROCESSORS_COUNT)).mpmap(r.unique_words_frequances)).sum(axis = 0)
      3 WORDS = mpd.DataFrame(df.reset_index())
----> 4 tmp = WORDS.source.apply(lambda x: pd.value_counts(x.split())).sum(axis = 0)
      5 tmp

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\modin\pandas\series.py:681, in Series.apply(self, func, convert_dtype, args, **kwargs)
    679         return result
    680 else:
--> 681     result = getattr(sys.modules[self.__module__], return_type)(
    682         query_compiler=result
    683     )
    684     if result.name == self.index[0]:
    685         result.name = None

AttributeError: module 'modin.pandas.series' has no attribute 'DataFrame'
`

**Comment by mvashishtha** [comment] 2022-06-07 15:10
@yazeedhasan97 it looks like you were able to initialize the Modin dataframe from the pandas dataframe, but you hit an error when applying a function that converts each element in a series to a pandas series. That looks like a separate bug that I can reproduce on Modin version dcee13d57ebf9a006460deedb734c15791acae7a on Python 3.9.12 and on macOS Monterey 12.2.1. Here's the reproducing script:

```python
import pandas
import modin.pandas as pd

s = pd.Series([1])
print(s.apply(lambda s: pandas.Series([1])))
```

whereas if I replace `import modin.pandas as pd` with `import pandas as pd` I get the expected dataframe:

```
   0
0  1
```

Could you please file a bug report with this reproduction script and the rest of the fields in the bug report form (e.g. modin and pandas version) at https://github.com/modin-project/modin/issues/new? Modin users and contributors can then track updates to the new bug.

I will close this question because @devin-petersohn 's answer should suffice.

**Closed by mvashishtha** 2022-06-07 15:10 UTC
Labels: question ❓
