### ISSUE TITLE
to_sql fails (PostgreSQL 10.0)

### ISSUE THREAD

**Issue by StefanVitor** [modin-project/modin#1421] opened 2020-05-04 09:23 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Modin version** (`modin.__version__`): 0.7.3.
- **Python version**: 3.6.9
- **PostgreSQL version**: 10.0
- **Code we can use to reproduce**:

```
from sqlalchemy import create_engine
import modin.pandas as pd
v_engine = create_engine('postgresql://test:test123@localhost:5432/testdb')
v_sequ = 11
df_test_example = pd.read_sql_query('select "interval_ema" from "cry061" where sequ = %(sequ)s', params={'sequ':v_sequ} , con=v_engine)
df_test_example['interval_ema'] = 1
df_test_example.to_sql('test_stefan',  con=v_engine, if_exists='append')
```

### Describe the problem
Running the above code produces the following error:

`TypeError: can't pickle _thread._local objects`

### Source code / logs

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    df_test_example.to_sql('test_stefan',  con=v_engine, if_exists='append')
  File "/usr/local/lib/python3.6/dist-packages/modin/pandas/base.py", line 3074, in to_sql
    method=method,
  File "/usr/local/lib/python3.6/dist-packages/modin/data_management/factories.py", line 193, in to_sql
    return cls._determine_engine()._to_sql(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/modin/data_management/factories.py", line 197, in _to_sql
    return cls.io_cls.to_sql(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/modin/engines/ray/generic/io.py", line 44, in to_sql
    result = qc._modin_frame._fold_reduce(1, func)
  File "/usr/local/lib/python3.6/dist-packages/modin/engines/base/frame/data.py", line 722, in _fold_reduce
    axis, self._partitions, func
  File "/usr/local/lib/python3.6/dist-packages/modin/engines/base/frame/partition_manager.py", line 181, in map_axis_partitions
    preprocessed_map_func = cls.preprocess_func(map_func)
  File "/usr/local/lib/python3.6/dist-packages/modin/engines/base/frame/partition_manager.py", line 50, in preprocess_func
    return cls._partition_class.preprocess_func(map_func)
  File "/usr/local/lib/python3.6/dist-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 156, in preprocess_func
    return ray.put(func)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1547, in put
    object_id = worker.put_object(value, pin_object=not weakref)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 267, in put_object
    serialized_value = self.get_serialization_context().serialize(value)
  File "/usr/local/lib/python3.6/dist-packages/ray/serialization.py", line 378, in serialize
    raise e
  File "/usr/local/lib/python3.6/dist-packages/ray/serialization.py", line 375, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread._local objects
```

**Comment by devin-petersohn** [comment] 2020-05-09 19:42
Hi @StefanVitor, thanks for the report!

I see where this is happening, we will get this fixed. As a temporary workaround, you can allow Modin to create the engine and distributed connection by changing the connection code:

```python
from sqlalchemy import create_engine
import modin.pandas as pd
# v_engine = create_engine('postgresql://test:test123@localhost:5432/testdb')
v_engine = 'postgresql://test:test123@localhost:5432/testdb'
v_sequ = 11
df_test_example = pd.read_sql_query('select "interval_ema" from "cry061" where sequ = %(sequ)s', params={'sequ':v_sequ} , con=v_engine)
df_test_example['interval_ema'] = 1
df_test_example.to_sql('test_stefan',  con=v_engine, if_exists='append')
```

**Comment by mvashishtha** [comment] 2022-09-07 22:55
Duplicate of #4048

**Closed by mvashishtha** 2022-09-07 22:55 UTC
Labels: bug 🦗
