### ISSUE TITLE
 df = df['param'] == paramset ; TypeError: Cannot do operation non-numeric dtypes

### ISSUE THREAD

**Issue by Tvix22** [modin-project/modin#603] opened 2019-05-01 07:39 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian Strech
- **Modin installed from (source or binary)**: pip install --pre 
- **Modin version**: 0.5.0rc1
- **Python version**: 3.5 
- **Exact command to reproduce**:
for file in range(len(files)):
    usefile = files[file]
    df = pd.read_csv(mainpath + "/" + str(usefile),parse_dates=True)
    df = df['UnderlyingSymbol'] == Symbol
    datos[usefile] = df

### Describe the problem
When i use df = df['UnderlyingSymbol'] == Symbol , show that error.

### Source code / logs
TypeError                                 Traceback (most recent call last)
<ipython-input-3-7dde15b669b6> in <module>
     11     print("Valor Numero :" + str(contador) + " de un total de " + str((len(files))) + " archivos")
     12     df = pd.read_csv(mainpath + "/" + str(usefile),parse_dates=True)
---> 13     df = df['UnderlyingSymbol'] == Symbol
     14     datos[usefile] = df
     15 

~/lab1/lab1/lib/python3.5/site-packages/modin/pandas/base.py in __eq__(self, other)
   3138 
   3139     def __eq__(self, other):
-> 3140         return self.eq(other)
   3141 
   3142     def __finalize__(self, other, method=None, **kwargs):

~/lab1/lab1/lib/python3.5/site-packages/modin/pandas/series.py in eq(self, other, level, fill_value, axis)
    487     def eq(self, other, level=None, fill_value=None, axis=0):
    488         new_self, new_other = self._prepare_inter_op(other)
--> 489         return super(Series, new_self).eq(new_other, level=level, axis=axis)
    490 
    491     def equals(self, other):

~/lab1/lab1/lib/python3.5/site-packages/modin/pandas/base.py in eq(self, other, axis, level)
   1017             A new DataFrame filled with Booleans.
   1018         """
-> 1019         return self._binary_op("eq", other, axis=axis, level=level)
   1020 
   1021     def ewm(

~/lab1/lab1/lib/python3.5/site-packages/modin/pandas/base.py in _binary_op(self, op, other, axis, **kwargs)
    173                 getattr(getattr(pandas, self.__name__), op), other, axis=axis, **kwargs
    174             )
--> 175         other = self._validate_other(other, axis, numeric_or_object_only=True)
    176         new_query_compiler = self._query_compiler.binary_op(
    177             op, other=other, axis=axis, **kwargs

~/lab1/lab1/lib/python3.5/site-packages/modin/pandas/base.py in _validate_other(self, other, axis, numeric_only, numeric_or_time_only, numeric_or_object_only, comparison_dtypes_only)
    137                 for self_dtype, other_dtype in zip(self._get_dtypes(), other_dtypes)
    138             ):
--> 139                 raise TypeError("Cannot do operation non-numeric dtypes")
    140         elif comparison_dtypes_only:
    141             if not all(

TypeError: Cannot do operation non-numeric dtype

**Comment by devin-petersohn** [comment] 2019-05-01 15:15
Hi @Tvix22 thanks for trying out the pre-release and thanks for posting!

What type is `Symbol`? It looks like it could be that our error checking is too aggressive for `__eq__`.

**Comment by Tvix22** [comment] 2019-05-02 10:04
Hello Devin, thanks for your work!!!! its a pleasure work with modin!
The code is working perfect in pandas ( but. slowly obv)

`data.dtypes
data.dtypes
UnderlyingSymbol     object
UnderlyingPrice     float64
Exchange             object
OptionSymbol         object
OptionExt           float64
Type                 object
Expiration           object
DataDate             object
Strike              float64
Last                float64
Bid                 float64
Ask                 float64
Volume                int64
OpenInterest          int64
IV                  float64
Delta               float64
Gamma               float64
Theta               float64
Vega                float64
AKA                  object
dtype: object`

**Comment by williamma12** [comment] 2019-05-03 18:22
Hi @Tvix22, I tried to reproduce the error with the following
```
import modin.pandas as pd
modin_df = pd.DataFrame({"col1": ['a','b','c'], "col2": [4,5,6], "col3": [7, 8, 9]})
modin_series = pd.Series(['a','a','c'])
df = modin_df['col1'] == modin_series
df
```
and was unable to reproduce the error. Could you provide a sample dataset of df or what the `Symbol` object is?

**Comment by devin-petersohn** [comment] 2019-05-04 16:33
@Tvix22 thanks for the response! I had @williamma12 reproduce the error, it should be resolved in #604. Please reopen if you run into an issue. You can try it by installing directly from the GitHub repo:
`pip install git+https://github.com/modin-project/modin`

**Closed by devin-petersohn** 2019-05-04 16:33 UTC

**Comment by Tvix22** [comment] 2019-05-08 23:18
Hello, i try with de github repo, and show a new error.

when i use this:

files = os.listdir(mainpath)
datos={}
contador = 0
for file in range(len(files)):
    usefile = files[file] 
    df = pd.read_csv(mainpath + "/" + str(usefile), parse_dates=True, index_col=['quotedate'])
    datos[usefile] = df
data = pd.concat(datos.values(), keys=datos.keys(), axis=1, sort='True')

when i use pd.concat, it shows: (its running perfect on pandas, if you need some data sample, please say me.

Greetings from Spain!

---------------------------------------------------------------------------
RayTaskError                              Traceback (most recent call last)
~/lab1/lab1/lib/python3.5/site-packages/modin/engines/ray/generic/frame/partition_manager.py in block_lengths(self)
     36                     ray.get([obj.length().oid for obj in self._partitions_cache.T[0]])
---> 37                     if len(self._partitions_cache.T) > 0
     38                     else []

~/lab1/lab1/lib/python3.5/site-packages/ray/worker.py in get(object_ids)
   2183                     last_task_error_raise_time = time.time()
-> 2184                     raise value
   2185             return values

RayTaskError: ray_worker:modin.engines.ray.pandas_on_ray.frame.partition.deploy_ray_func() (pid=9413, host=s144688)
ray.exceptions.RayTaskError: ray_worker:modin.engines.ray.pandas_on_ray.frame.axis_partition.deploy_ray_func() (pid=9418, host=s144688)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/modin/engines/ray/pandas_on_ray/frame/axis_partition.py", line 84, in deploy_ray_func
    return func(*args)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/modin/engines/base/frame/axis_partition.py", line 187, in deploy_axis_func
    result = func(dataframe, **kwargs)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/modin/backends/pandas/query_compiler.py", line 160, in helper
    return pandas_func(df, **kwargs)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/modin/backends/pandas/query_compiler.py", line 432, in reindex_partition
    new_df = df.reindex(index=joined_index)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/pandas/util/_decorators.py", line 197, in wrapper
    return func(*args, **kwargs)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/pandas/core/frame.py", line 3809, in reindex
    return super(DataFrame, self).reindex(**kwargs)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/pandas/core/generic.py", line 4356, in reindex
    fill_value, copy).__finalize__(self)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/pandas/core/frame.py", line 3741, in _reindex_axes
    fill_value, limit, tolerance)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/pandas/core/frame.py", line 3752, in _reindex_index
    allow_dups=False)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/pandas/core/generic.py", line 4490, in _reindex_with_indexers
    copy=copy)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/pandas/core/internals/managers.py", line 1224, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/home/py/lab1/lab1/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 3087, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis



During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-9-dfe840ed09e8> in <module>
----> 1 data = pd.concat(datos.values(), keys=datos.keys(), axis=1, sort='True')

~/lab1/lab1/lib/python3.5/site-packages/modin/pandas/concat.py in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    110         verify_integrity=False,
    111         copy=True,
--> 112         sort=sort,
    113     )
    114     result_df = DataFrame(query_compiler=new_query_compiler)

~/lab1/lab1/lib/python3.5/site-packages/modin/backends/pandas/query_compiler.py in concat(self, axis, other, **kwargs)
    317             Concatenated objects.
    318         """
--> 319         return self._append_list_of_managers(other, axis, **kwargs)
    320 
    321     def _append_list_of_managers(self, others, axis, **kwargs):

~/lab1/lab1/lib/python3.5/site-packages/modin/backends/pandas/query_compiler.py in _append_list_of_managers(self, others, axis, **kwargs)
    330         ignore_index = kwargs.get("ignore_index", False)
    331         new_self, to_append, joined_axis = self.copartition(
--> 332             axis ^ 1, others, join, sort, force_repartition=True
    333         )
    334         new_data = new_self.concat(axis, to_append)

~/lab1/lab1/lib/python3.5/site-packages/modin/backends/pandas/query_compiler.py in copartition(self, axis, other, how_to_join, sort, force_repartition)
    456 
    457             reindexed_self, reindexed_other = reindexed_self.copartition_datasets(
--> 458                 axis, other[i].data, reindex_left, reindex_right
    459             )
    460             reindexed_other_list.append(reindexed_other)

~/lab1/lab1/lib/python3.5/site-packages/modin/engines/base/frame/partition_manager.py in copartition_datasets(self, axis, other, left_func, right_func)
    271                 axis,
    272                 right_func,
--> 273                 new_self.block_lengths if axis == 0 else new_self.block_widths,
    274             )
    275         return new_self, new_other

~/lab1/lab1/lib/python3.5/site-packages/modin/engines/ray/generic/frame/partition_manager.py in block_lengths(self)
     39                 )
     40             except RayTaskError as e:
---> 41                 handle_ray_task_error(e)
     42         return self._lengths_cache
     43 

~/lab1/lab1/lib/python3.5/site-packages/modin/engines/ray/utils.py in handle_ray_task_error(e)
     11         if "Error" in s or "Exception" in s:
     12             try:
---> 13                 raise getattr(builtins, s.split(":")[0])("".join(s.split(":")[1:]))
     14             except AttributeError:
     15                 break

ValueError:  cannot reindex from a duplicate axis

time: 2.14 s

**Comment by devin-petersohn** [comment] 2019-05-09 15:38
Hi @Tvix22, thanks for the follow-up!

Would you be able to open a new issue for this? I wasn't able to reproduce the error, so a data sample would be great!
