### ISSUE TITLE
BUG: KeyError occuring in `__getitem_bool` if dataframe has only one row

### ISSUE THREAD

**Issue by pyrito** [modin-project/modin#4845] opened 2022-08-19 13:54 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 12.2.1
- **Modin version** (`modin.__version__`): 0.15.2
- **Python version**: 3.9.12
- **Code we can use to reproduce**:
```python
import os
import regex as re
import modin.pandas as pd

# Where server.log has simple arbitrary strings
fp = "server.log"
data_lines = []

with open(fp, "rt", encoding="utf8") as file:
    lines = file.readlines()
    # data_lines += [
    #     line for line in lines
    #     if "POST" in line
    # ]
    data_lines += lines

# Processing
df = pd.DataFrame({"src": data_lines})
df.src = df.src.astype("string")

# This appears to fail
df = df[df.src.str.contains("POST")]
print(df)
```

### Describe the problem
I got this error while trying to reproduce: https://stackoverflow.com/questions/73395456/string-methods-fail-with-modin-but-same-work-with-pandas, which, funnily enough, is facing a different error.

### Source code / logs
<details>
<summary>Error logs</summary>

```python
File ~/opt/anaconda3/envs/modin/lib/python3.9/site-packages/IPython/core/formatters.py:707, in PlainTextFormatter.__call__(self, obj)
    700 stream = StringIO()
    701 printer = pretty.RepresentationPrinter(stream, self.verbose,
    702     self.max_width, self.newline,
    703     max_seq_length=self.max_seq_length,
    704     singleton_pprinters=self.singleton_printers,
    705     type_pprinters=self.type_printers,
    706     deferred_pprinters=self.deferred_printers)
--> 707 printer.pretty(obj)
    708 printer.flush()
    709 return stream.getvalue()

File ~/opt/anaconda3/envs/modin/lib/python3.9/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File ~/opt/anaconda3/envs/modin/lib/python3.9/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

File ~/Documents/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115 
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/Documents/modin/modin/pandas/dataframe.py:223, in DataFrame.__repr__(self)
    220         i -= 1
    222     num_cols += len(self.columns) - i
--> 223 result = repr(self._build_repr_df(num_rows, num_cols))
    224 if len(self.index) > num_rows or len(self.columns) > num_cols:
    225     # The split here is so that we don't repr pandas row lengths.
    226     return result.rsplit("\n\n", 1)[0] + "\n\n[{0} rows x {1} columns]".format(
    227         len(self.index), len(self.columns)
    228     )

File ~/Documents/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115 
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/Documents/modin/modin/pandas/base.py:152, in BasePandasDataset._build_repr_df(self, num_rows, num_cols)
    130 """
    131 Build pandas DataFrame for string representation.
    132 
   (...)
    149     A pandas dataset with `num_rows` or fewer rows and `num_cols` or fewer columns.
    150 """
    151 # Fast track for empty dataframe.
--> 152 if len(self.index) == 0 or (
    153     hasattr(self, "columns") and len(self.columns) == 0
    154 ):
    155     return pandas.DataFrame(
    156         index=self.index,
    157         columns=self.columns if hasattr(self, "columns") else None,
    158     )
    159 if len(self.index) <= num_rows:

File ~/Documents/modin/modin/pandas/base.py:3410, in BasePandasDataset.__getattribute__(self, item)
   3396 @disable_logging
   3397 def __getattribute__(self, item):
   3398     """
   3399     Return item from the `BasePandasDataset`.
   3400 
   (...)
   3408     Any
   3409     """
-> 3410     attr = super().__getattribute__(item)
   3411     if item not in _DEFAULT_BEHAVIOUR and not self._query_compiler.lazy_execution:
   3412         # We default to pandas on empty DataFrames. This avoids a large amount of
   3413         # pain in underlying implementation and returns a result immediately rather
   3414         # than dealing with the edge cases that empty DataFrames have.
   3415         if callable(attr) and self.empty and hasattr(self._pandas_class, item):

File ~/Documents/modin/modin/pandas/base.py:543, in BasePandasDataset._get_index(self)
    534 def _get_index(self):
    535     """
    536     Get the index for this DataFrame.
    537 
   (...)
    541         The union of all indexes across the partitions.
    542     """
--> 543     return self._query_compiler.index

File ~/Documents/modin/modin/core/storage_formats/pandas/query_compiler.py:76, in _get_axis.<locals>.<lambda>(self)
     63 """
     64 Build index labels getter of the specified axis.
     65 
   (...)
     73 callable(PandasQueryCompiler) -> pandas.Index
     74 """
     75 if axis == 0:
---> 76     return lambda self: self._modin_frame.index
     77 else:
     78     return lambda self: self._modin_frame.columns

File ~/Documents/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:370, in PandasDataframe._get_index(self)
    361 """
    362 Get the index from the cache object.
    363 
   (...)
    367     An index object containing the row labels.
    368 """
    369 if self._index_cache is None:
--> 370     self._index_cache, row_lengths = self._compute_axis_labels_and_lengths(0)
    371     if self._row_lengths_cache is None:
    372         self._row_lengths_cache = row_lengths

File ~/Documents/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115 
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/Documents/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:462, in PandasDataframe._compute_axis_labels_and_lengths(self, axis, partitions)
    460 if partitions is None:
    461     partitions = self._partitions
--> 462 new_index, internal_idx = self._partition_mgr_cls.get_indices(axis, partitions)
    463 return new_index, list(map(len, internal_idx))

File ~/Documents/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115 
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/Documents/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py:866, in PandasDataframePartitionManager.get_indices(cls, axis, partitions, index_func)
    864 target = partitions.T if axis == 0 else partitions
    865 new_idx = [idx.apply(func) for idx in target[0]] if len(target) else []
--> 866 new_idx = cls.get_objects_from_partitions(new_idx)
    867 # TODO FIX INFORMATION LEAK!!!!1!!1!!
    868 total_idx = new_idx[0].append(new_idx[1:]) if new_idx else new_idx

File ~/Documents/modin/modin/logging/logger_decorator.py:128, in enable_logging.<locals>.decorator.<locals>.run_and_log(*args, **kwargs)
    113 """
    114 Compute function with logging if Modin logging is enabled.
    115 
   (...)
    125 Any
    126 """
    127 if LogMode.get() == "disable":
--> 128     return obj(*args, **kwargs)
    130 logger = get_logger()
    131 logger_level = getattr(logger, log_level)

File ~/Documents/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py:110, in PandasOnRayDataframePartitionManager.get_objects_from_partitions(cls, partitions)
     95 @classmethod
     96 def get_objects_from_partitions(cls, partitions):
     97     """
     98     Get the objects wrapped by `partitions` in parallel.
     99 
   (...)
    108         The objects wrapped by `partitions`.
    109     """
--> 110     return ray.get([partition._data for partition in partitions])

File ~/opt/anaconda3/envs/modin/lib/python3.9/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/opt/anaconda3/envs/modin/lib/python3.9/site-packages/ray/worker.py:1809, in get(object_refs, timeout)
   1807     worker.core_worker.dump_object_store_memory_usage()
   1808 if isinstance(value, RayTaskError):
-> 1809     raise value.as_instanceof_cause()
   1810 else:
   1811     raise value

RayTaskError(KeyError): ray::_apply_func() (pid=50435, ip=127.0.0.1)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: False

The above exception was the direct cause of the following exception:

ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "/Users/kvelayutham/Documents/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py", line 428, in _apply_list_of_funcs
    partition = func(partition, *args, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 371, in map_func
    return apply_func(df, **{other_name: other})
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/algebra/binary.py", line 89, in <lambda>
    lambda l, r: func(l, r.squeeze(), *args, **kwargs),
  File "/Users/kvelayutham/Documents/modin/modin/core/storage_formats/pandas/query_compiler.py", line 2154, in <lambda>
    lambda df, r: df[r], join_type="left", labels="drop"
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: False

In [11]: 2022-08-19 08:49:14,844	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: False

The above exception was the direct cause of the following exception:

ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "/Users/kvelayutham/Documents/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py", line 428, in _apply_list_of_funcs
    partition = func(partition, *args, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 371, in map_func
    return apply_func(df, **{other_name: other})
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/algebra/binary.py", line 89, in <lambda>
    lambda l, r: func(l, r.squeeze(), *args, **kwargs),
  File "/Users/kvelayutham/Documents/modin/modin/core/storage_formats/pandas/query_compiler.py", line 2154, in <lambda>
    lambda df, r: df[r], join_type="left", labels="drop"
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: False
2022-08-19 08:49:14,844	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: False

The above exception was the direct cause of the following exception:

ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "/Users/kvelayutham/Documents/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py", line 428, in _apply_list_of_funcs
    partition = func(partition, *args, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 371, in map_func
    return apply_func(df, **{other_name: other})
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/algebra/binary.py", line 89, in <lambda>
    lambda l, r: func(l, r.squeeze(), *args, **kwargs),
  File "/Users/kvelayutham/Documents/modin/modin/core/storage_formats/pandas/query_compiler.py", line 2154, in <lambda>
    lambda df, r: df[r], join_type="left", labels="drop"
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: False
2022-08-19 08:49:14,844	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: False

The above exception was the direct cause of the following exception:

ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "/Users/kvelayutham/Documents/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py", line 428, in _apply_list_of_funcs
    partition = func(partition, *args, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 371, in map_func
    return apply_func(df, **{other_name: other})
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/algebra/binary.py", line 89, in <lambda>
    lambda l, r: func(l, r.squeeze(), *args, **kwargs),
  File "/Users/kvelayutham/Documents/modin/modin/core/storage_formats/pandas/query_compiler.py", line 2154, in <lambda>
    lambda df, r: df[r], join_type="left", labels="drop"
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: False
2022-08-19 08:49:16,843	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_apply_func() (pid=50435, ip=127.0.0.1)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: False

The above exception was the direct cause of the following exception:

ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "/Users/kvelayutham/Documents/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py", line 428, in _apply_list_of_funcs
    partition = func(partition, *args, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 371, in map_func
    return apply_func(df, **{other_name: other})
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/algebra/binary.py", line 89, in <lambda>
    lambda l, r: func(l, r.squeeze(), *args, **kwargs),
  File "/Users/kvelayutham/Documents/modin/modin/core/storage_formats/pandas/query_compiler.py", line 2154, in <lambda>
    lambda df, r: df[r], join_type="left", labels="drop"
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: False
2022-08-19 08:49:16,844	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_apply_func() (pid=50435, ip=127.0.0.1)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: False

The above exception was the direct cause of the following exception:

ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "/Users/kvelayutham/Documents/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py", line 428, in _apply_list_of_funcs
    partition = func(partition, *args, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 371, in map_func
    return apply_func(df, **{other_name: other})
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/algebra/binary.py", line 89, in <lambda>
    lambda l, r: func(l, r.squeeze(), *args, **kwargs),
  File "/Users/kvelayutham/Documents/modin/modin/core/storage_formats/pandas/query_compiler.py", line 2154, in <lambda>
    lambda df, r: df[r], join_type="left", labels="drop"
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: False
2022-08-19 08:49:16,845	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_apply_func() (pid=50435, ip=127.0.0.1)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: False

The above exception was the direct cause of the following exception:

ray::_apply_list_of_funcs() (pid=50435, ip=127.0.0.1)
  File "/Users/kvelayutham/Documents/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py", line 428, in _apply_list_of_funcs
    partition = func(partition, *args, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 371, in map_func
    return apply_func(df, **{other_name: other})
  File "/Users/kvelayutham/Documents/modin/modin/core/dataframe/algebra/binary.py", line 89, in <lambda>
    lambda l, r: func(l, r.squeeze(), *args, **kwargs),
  File "/Users/kvelayutham/Documents/modin/modin/core/storage_formats/pandas/query_compiler.py", line 2154, in <lambda>
    lambda df, r: df[r], join_type="left", labels="drop"
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: False

```

</details>

**Comment by pyrito** [comment] 2022-08-19 13:55
@vnlitvinov could you take a look at this? I was able to trace down the error to `__getitem_bool` but I don't know exactly what else is causing the failure here.

**Comment by vnlitvinov** [comment] 2022-08-19 15:56
@pyrito I wonder if you can attach some minimal working `server.log`, I cannot repro on my end using some random text file.

**Comment by Billy2551** [comment] 2022-09-01 07:14
When running the line `df[df.src.str.contains("POST")]`, `df` is being indexed using the Series `df.src.str.contains("POST")`. This calls on the function `__getitem_bool`. `__getitem_bool` accepts a dataframe `df` and indexes it using boolean values provided in `r`.

```
__getitem_bool = Binary.register(
    lambda df, r: df[r], join_type="left", labels="drop"
)
```

Before it does this, however, `__getitem_bool` applies the function `squeeze()` onto `r`, converting all 1 dimensional axis objects into scalars.
```
lambda l, r: func(l, r.squeeze(), *args, **kwargs)
```

Since `df.src.str.contains("POST")` results in a Series with only 1 item, applying `squeeze()` to this Series converts it to a single boolean. Whereas when there is more than one row, `df.src.str.contains("POST")` results in a Series with more than 1 item. Applying `squeeze()` to a Series with multiple items returns the original Series. This explains why there is no error with more than 1 rows.

The KeyError is caused by trying to execute
```
df[False]
```
instead of
```
df[[False]] # or some other iterable
```

While this problem specifically could be solved by removing the call on `squeeze()`, this change affects other use cases of the binary operator, resulting in the wrong output of
```
    src
0  <NA>
```
instead of the expected output
```
   src
0  foo
```

**Comment by anmyachev** [comment] 2023-08-22 10:36
Fixed in https://github.com/modin-project/modin/pull/4917.

**Closed by anmyachev** 2023-08-22 10:36 UTC
Labels: bug 🦗, pandas concordance 🐼, P2
