### ISSUE TITLE
Internal and external indices on axis 0 do not match

### ISSUE THREAD

**Issue by yarimiz** [modin-project/modin#4453] opened 2022-05-11 08:13 UTC
### System information
- Ubuntu 18.04.6 LTS
- **Modin version** (`modin.__version__`): 0.14.1
- **Python version**: 3.9.6
- **Code we can use to reproduce**:

import modin.pandas as pd
pd.read_parquet(a local parquet file)

### Describe the problem
It seems that for an unknown reason, when modin tried to display a specific local parquet file, it fails.
Reading the file into a variable works, but once I try to access the variable, the following exception raises

Pandas is able to read and work on this file correctly.

Basically, the file structure is
|index|date|
|---|---|
|1|pd.timestamp|
|2|pd.timestamp|
|3|pd.timestamp|

### Source code / logs
```Exception                                 Traceback (most recent call last)
File ~/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py:707, in PlainTextFormatter.__call__(self, obj)
    [700](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=699) stream = StringIO()
    [701](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=700) printer = pretty.RepresentationPrinter(stream, self.verbose,
    [702](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=701)     self.max_width, self.newline,
    [703](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=702)     max_seq_length=self.max_seq_length,
    [704](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=703)     singleton_pprinters=self.singleton_printers,
    [705](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=704)     type_pprinters=self.type_printers,
    [706](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=705)     deferred_pprinters=self.deferred_printers)
--> [707](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=706) printer.pretty(obj)
    [708](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=707) printer.flush()
    [709](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=708) return stream.getvalue()

File ~/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    [407](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=406)                         return meth(obj, self, cycle)
    [408](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=407)                 if cls is not object \
    [409](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=408)                         and callable(cls.__dict__.get('__repr__')):
--> [410](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=409)                     return _repr_pprint(obj, self, cycle)
    [412](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=411)     return _default_pprint(obj, self, cycle)
    [413](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=412) finally:

File ~/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    [776](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=775) """A pprint that just redirects to the normal repr function."""
    [777](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=776) # Find newlines and replace them with p.break_()
--> [778](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=777) output = repr(obj)
    [779](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=778) lines = output.splitlines()
    [780](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/lib/pretty.py?line=779) with p.group():

File ~/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py:214, in DataFrame.__repr__(self)
    [211](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=210)         i -= 1
    [213](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=212)     num_cols += len(self.columns) - i
--> [214](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=213) result = repr(self._build_repr_df(num_rows, num_cols))
    [215](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=214) if len(self.index) > num_rows or len(self.columns) > num_cols:
    [216](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=215)     # The split here is so that we don't repr pandas row lengths.
    [217](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=216)     return result.rsplit("\n\n", 1)[0] + "\n\n[{0} rows x {1} columns]".format(
    [218](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=217)         len(self.index), len(self.columns)
    [219](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=218)     )

File ~/git/my-project/env/lib/python3.9/site-packages/modin/pandas/base.py:201, in BasePandasDataset._build_repr_df(self, num_rows, num_cols)
    [199](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/base.py?line=198) else:
    [200](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/base.py?line=199)     indexer = row_indexer
--> [201](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/base.py?line=200) return self.iloc[indexer]._query_compiler.to_pandas()

File ~/git/my-project/env/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py:258, in PandasQueryCompiler.to_pandas(self)
    [257](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py?line=256) def to_pandas(self):
--> [258](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py?line=257)     return self._modin_frame.to_pandas()

File ~/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:114, in lazy_metadata_decorator.<locals>.decorator.<locals>.run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    [112](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=111)     elif apply_axis == "rows":
    [113](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=112)         obj._propagate_index_objs(axis=0)
--> [114](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=113) result = f(self, *args, **kwargs)
    [115](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=114) if apply_axis is None and not transpose:
    [116](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=115)     result._deferred_index = self._deferred_index

File ~/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:2776, in PandasDataframe.to_pandas(self)
   [2774](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2773) else:
   [2775](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2774)     for axis in [0, 1]:
-> [2776](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2775)         ErrorMessage.catch_bugs_and_request_email(
   [2777](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2776)             not df.axes[axis].equals(self.axes[axis]),
   [2778](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2777)             f"Internal and external indices on axis {axis} do not match.",
   [2779](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2778)         )
   [2780](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2779)     df.index = self.index
   [2781](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2780)     df.columns = self.columns

File ~/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py:60, in ErrorMessage.catch_bugs_and_request_email(cls, failure_condition, extra_log)
     [57](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=56) @classmethod
     [58](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=57) def catch_bugs_and_request_email(cls, failure_condition, extra_log=""):
     [59](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=58)     if failure_condition:
---> [60](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=59)         raise Exception(
     [61](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=60)             "Internal Error. "
     [62](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=61)             + "Please email bug_reports@modin.org with the traceback and command that"
     [63](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=62)             + f" caused this error.\n{extra_log}"
     [64](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=63)         )

Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
Internal and external indices on axis 0 do not match.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
File ~/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py:343, in BaseFormatter.__call__(self, obj)
    [341](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=340)     method = get_real_method(obj, self.print_method)
    [342](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=341)     if method is not None:
--> [343](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=342)         return method()
    [344](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=343)     return None
    [345](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/IPython/core/formatters.py?line=344) else:

File ~/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py:236, in DataFrame._repr_html_(self)
    [232](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=231) num_cols = pandas.get_option("display.max_columns") or 20
    [234](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=233) # We use pandas _repr_html_ to get a string of the HTML representation
    [235](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=234) # of the dataframe.
--> [236](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=235) result = self._build_repr_df(num_rows, num_cols)._repr_html_()
    [237](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=236) if len(self.index) > num_rows or len(self.columns) > num_cols:
    [238](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=237)     # We split so that we insert our correct dataframe dimensions.
    [239](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=238)     return result.split("<p>")[
    [240](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=239)         0
    [241](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=240)     ] + "<p>{0} rows x {1} columns</p>\n</div>".format(
    [242](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=241)         len(self.index), len(self.columns)
    [243](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/dataframe.py?line=242)     )

File ~/git/my-project/env/lib/python3.9/site-packages/modin/pandas/base.py:201, in BasePandasDataset._build_repr_df(self, num_rows, num_cols)
    [199](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/base.py?line=198) else:
    [200](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/base.py?line=199)     indexer = row_indexer
--> [201](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/pandas/base.py?line=200) return self.iloc[indexer]._query_compiler.to_pandas()

File ~/git/my-project/env/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py:258, in PandasQueryCompiler.to_pandas(self)
    [257](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py?line=256) def to_pandas(self):
--> [258](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/storage_formats/pandas/query_compiler.py?line=257)     return self._modin_frame.to_pandas()

File ~/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:114, in lazy_metadata_decorator.<locals>.decorator.<locals>.run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    [112](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=111)     elif apply_axis == "rows":
    [113](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=112)         obj._propagate_index_objs(axis=0)
--> [114](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=113) result = f(self, *args, **kwargs)
    [115](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=114) if apply_axis is None and not transpose:
    [116](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=115)     result._deferred_index = self._deferred_index

File ~/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py:2776, in PandasDataframe.to_pandas(self)
   [2774](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2773) else:
   [2775](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2774)     for axis in [0, 1]:
-> [2776](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2775)         ErrorMessage.catch_bugs_and_request_email(
   [2777](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2776)             not df.axes[axis].equals(self.axes[axis]),
   [2778](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2777)             f"Internal and external indices on axis {axis} do not match.",
   [2779](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2778)         )
   [2780](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2779)     df.index = self.index
   [2781](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py?line=2780)     df.columns = self.columns

File ~/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py:60, in ErrorMessage.catch_bugs_and_request_email(cls, failure_condition, extra_log)
     [57](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=56) @classmethod
     [58](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=57) def catch_bugs_and_request_email(cls, failure_condition, extra_log=""):
     [59](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=58)     if failure_condition:
---> [60](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=59)         raise Exception(
     [61](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=60)             "Internal Error. "
     [62](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=61)             + "Please email bug_reports@modin.org with the traceback and command that"
     [63](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=62)             + f" caused this error.\n{extra_log}"
     [64](file:///home/ubuntu/git/my-project/env/lib/python3.9/site-packages/modin/error_message.py?line=63)         )

Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
Internal and external indices on axis 0 do not match.```

**Comment by mvashishtha** [comment] 2022-05-12 13:48
@yarimiz thank you very much for reporting this! Here's a complete script to reproduce the bug on Modin version .14.0+29.g270fd697:

```python
import pandas
import modin.pandas as pd

df = pandas.DataFrame(
    [
        [pandas.Timestamp("2017-01-01T12")],
        [pandas.Timestamp("2017-01-02T12")],
        [pandas.Timestamp("2017-01-03T12")],
    ],
    columns=pandas.Index(["time"], dtype="string"),
)

df.to_parquet("/tmp/three_rows_of_timestamps.parquet")
pd.read_parquet("/tmp/three_rows_of_timestamps.parquet")
```

<details>
<summary>Show stack trace</summary>

```
Exception                                 Traceback (most recent call last)
File /usr/local/lib/python3.9/site-packages/IPython/core/formatters.py:707, in PlainTextFormatter.__call__(self, obj)
    700 stream = StringIO()
    701 printer = pretty.RepresentationPrinter(stream, self.verbose,
    702     self.max_width, self.newline,
    703     max_seq_length=self.max_seq_length,
    704     singleton_pprinters=self.singleton_printers,
    705     type_pprinters=self.type_printers,
    706     deferred_pprinters=self.deferred_printers)
--> 707 printer.pretty(obj)
    708 printer.flush()
    709 return stream.getvalue()

File /usr/local/lib/python3.9/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File /usr/local/lib/python3.9/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

File ~/software_sources/modin/modin/pandas/dataframe.py:214, in DataFrame.__repr__(self)
    211         i -= 1
    213     num_cols += len(self.columns) - i
--> 214 result = repr(self._build_repr_df(num_rows, num_cols))
    215 if len(self.index) > num_rows or len(self.columns) > num_cols:
    216     # The split here is so that we don't repr pandas row lengths.
    217     return result.rsplit("\n\n", 1)[0] + "\n\n[{0} rows x {1} columns]".format(
    218         len(self.index), len(self.columns)
    219     )

File ~/software_sources/modin/modin/pandas/base.py:201, in BasePandasDataset._build_repr_df(self, num_rows, num_cols)
    199 else:
    200     indexer = row_indexer
--> 201 return self.iloc[indexer]._query_compiler.to_pandas()

File ~/software_sources/modin/modin/core/storage_formats/pandas/query_compiler.py:258, in PandasQueryCompiler.to_pandas(self)
    257 def to_pandas(self):
--> 258     return self._modin_frame.to_pandas()

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:114, in lazy_metadata_decorator.<locals>.decorator.<locals>.run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    112     elif apply_axis == "rows":
    113         obj._propagate_index_objs(axis=0)
--> 114 result = f(self, *args, **kwargs)
    115 if apply_axis is None and not transpose:
    116     result._deferred_index = self._deferred_index

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:2776, in PandasDataframe.to_pandas(self)
   2774 else:
   2775     for axis in [0, 1]:
-> 2776         ErrorMessage.catch_bugs_and_request_email(
   2777             not df.axes[axis].equals(self.axes[axis]),
   2778             f"Internal and external indices on axis {axis} do not match.",
   2779         )
   2780     df.index = self.index
   2781     df.columns = self.columns

File ~/software_sources/modin/modin/error_message.py:60, in ErrorMessage.catch_bugs_and_request_email(cls, failure_condition, extra_log)
     57 @classmethod
     58 def catch_bugs_and_request_email(cls, failure_condition, extra_log=""):
     59     if failure_condition:
---> 60         raise Exception(
     61             "Internal Error. "
     62             + "Please email bug_reports@modin.org with the traceback and command that"
     63             + f" caused this error.\n{extra_log}"
     64         )

Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
Internal and external indices on axis 1 do not match.

In [64]: df = pandas.DataFrame(
    ...:     [
    ...:         [pandas.Timestamp("2017-01-01T12")],
    ...:         [pandas.Timestamp("2017-01-02T12")],
    ...:         [pandas.Timestamp("2017-01-03T12")],
    ...:     ],
    ...:     columns=pandas.Index(["time"], dtype="string"),
    ...: )

In [65]: df.to_parquet("three_rows_of_timestamps.parquet")

In [66]: pd.read_parquet("three_rows_of_timestamps.parquet")
Out[66]: ---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
File /usr/local/lib/python3.9/site-packages/IPython/core/formatters.py:707, in PlainTextFormatter.__call__(self, obj)
    700 stream = StringIO()
    701 printer = pretty.RepresentationPrinter(stream, self.verbose,
    702     self.max_width, self.newline,
    703     max_seq_length=self.max_seq_length,
    704     singleton_pprinters=self.singleton_printers,
    705     type_pprinters=self.type_printers,
    706     deferred_pprinters=self.deferred_printers)
--> 707 printer.pretty(obj)
    708 printer.flush()
    709 return stream.getvalue()

File /usr/local/lib/python3.9/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File /usr/local/lib/python3.9/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

File ~/software_sources/modin/modin/pandas/dataframe.py:214, in DataFrame.__repr__(self)
    211         i -= 1
    213     num_cols += len(self.columns) - i
--> 214 result = repr(self._build_repr_df(num_rows, num_cols))
    215 if len(self.index) > num_rows or len(self.columns) > num_cols:
    216     # The split here is so that we don't repr pandas row lengths.
    217     return result.rsplit("\n\n", 1)[0] + "\n\n[{0} rows x {1} columns]".format(
    218         len(self.index), len(self.columns)
    219     )

File ~/software_sources/modin/modin/pandas/base.py:201, in BasePandasDataset._build_repr_df(self, num_rows, num_cols)
    199 else:
    200     indexer = row_indexer
--> 201 return self.iloc[indexer]._query_compiler.to_pandas()

File ~/software_sources/modin/modin/core/storage_formats/pandas/query_compiler.py:258, in PandasQueryCompiler.to_pandas(self)
    257 def to_pandas(self):
--> 258     return self._modin_frame.to_pandas()

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:114, in lazy_metadata_decorator.<locals>.decorator.<locals>.run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    112     elif apply_axis == "rows":
    113         obj._propagate_index_objs(axis=0)
--> 114 result = f(self, *args, **kwargs)
    115 if apply_axis is None and not transpose:
    116     result._deferred_index = self._deferred_index

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:2776, in PandasDataframe.to_pandas(self)
   2774 else:
   2775     for axis in [0, 1]:
-> 2776         ErrorMessage.catch_bugs_and_request_email(
   2777             not df.axes[axis].equals(self.axes[axis]),
   2778             f"Internal and external indices on axis {axis} do not match.",
   2779         )
   2780     df.index = self.index
   2781     df.columns = self.columns

File ~/software_sources/modin/modin/error_message.py:60, in ErrorMessage.catch_bugs_and_request_email(cls, failure_condition, extra_log)
     57 @classmethod
     58 def catch_bugs_and_request_email(cls, failure_condition, extra_log=""):
     59     if failure_condition:
---> 60         raise Exception(
     61             "Internal Error. "
     62             + "Please email bug_reports@modin.org with the traceback and command that"
     63             + f" caused this error.\n{extra_log}"
     64         )

Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
Internal and external indices on axis 1 do not match.
```
</details>

The bug occurs when the columns have dtype `'string'` so the columns are `Index(['time'], dtype='string')`. If I make the dtype 'str' so the columns are `Index(['time'], dtype='object')`, I no longer get the bug. My guess is that Modin is assuming that the columns for the overall frame are the wrong dtype.

I'll see if I can make a quick fix today. Otherwise, another Modin contributor can take this issue.

**Comment by mvashishtha** [comment] 2022-09-22 02:59
@yarimiz because you haven't replied in over 4 months and we still don't have a reproducible example, I'm going to close this issue. If you can provide more information or would like to ask more questions, please comment here or open a new issue. The modin contributors are happy to help.

**Closed by mvashishtha** 2022-09-22 02:59 UTC
Labels: Needs more information ❔, P3
