### ISSUE TITLE
Dask scalability issue

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3121] opened 2021-06-03 13:24 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: 64d6cb064feac23ed5bfa0cba221f35c512c114e
- **Python version**: 3.7.10
- **Code we can use to reproduce**:
```
import os
from timeit import default_timer as timer

import modin.config

modin.config.Engine.put("Dask")

import modin.pandas as pd

data_file = "test_data.csv"

columns_names = [
    "trip_id",
    "vendor_id",
    "pickup_datetime",
    "dropoff_datetime",
    "store_and_fwd_flag",
    "rate_code_id",
    "pickup_longitude",
    "pickup_latitude",
    "dropoff_longitude",
    "dropoff_latitude",
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "ehail_fee",
    "improvement_surcharge",
    "total_amount",
    "payment_type",
    "trip_type",
    "pickup",
    "dropoff",
    "cab_type",
    "precipitation",
    "snow_depth",
    "snowfall",
    "max_temperature",
    "min_temperature",
    "average_wind_speed",
    "pickup_nyct2010_gid",
    "pickup_ctlabel",
    "pickup_borocode",
    "pickup_boroname",
    "pickup_ct2010",
    "pickup_boroct2010",
    "pickup_cdeligibil",
    "pickup_ntacode",
    "pickup_ntaname",
    "pickup_puma",
    "dropoff_nyct2010_gid",
    "dropoff_ctlabel",
    "dropoff_borocode",
    "dropoff_boroname",
    "dropoff_ct2010",
    "dropoff_boroct2010",
    "dropoff_cdeligibil",
    "dropoff_ntacode",
    "dropoff_ntaname",
    "dropoff_puma",
]

kwargs = dict(
    names=columns_names,
    header=None,
    nrows=None,
    parse_dates=["pickup_datetime", "dropoff_datetime"],
)

partitions = [1, 2, 4, 8, 16, 32, 64, 112]
iters = 3

def get_data():
    if not os.path.exists(data_file):
        df = pd.read_csv('https://modin-datasets.s3.amazonaws.com/trips_data.csv')
        new_df = pd.concat([df]*100, ignore_index=True)
        new_df.to_csv(data_file, index=False)
    else:
        print("Using previously created data file")

def meas(iters, func, *args, **kwargs):
    t_res = float("inf")
    for _ in range(iters):
        t0 = timer()
        ans = func(*args, **kwargs)
        t = timer() - t0
        t_res = t if t < t_res else t
    
    return ans, t_res

def func_read_csv(data_file, **kwargs):
    return pd.read_csv(data_file, **kwargs)

def func_q1(df):
    return df.groupby("cab_type").size()

if __name__ == '__main__':
    # get_data()
    data_file = "/localdisk/amyskov/benchmark_datasets/taxi/trips_xaa.csv"
    for part in partitions:
        modin.config.NPartitions.put(part)

        df, t_read_csv = meas(iters, func_read_csv, data_file, **kwargs)
        _, t_q1 = meas(iters, func_q1, df)

        
        print(f"NPartitions {part}: t_read_csv = {t_read_csv}, t_q1 = {t_q1}")
```

### Describe the problem

After some threshold, partitions number increasing using Dask causes performance degradation.

### Source code / logs

Using `Dask` engine:
```
NPartitions 1: t_read_csv = 11.393041238887236, t_q1 = 1.1005668009165674
NPartitions 2: t_read_csv = 6.31416412582621, t_q1 = 0.5710716750472784
NPartitions 4: t_read_csv = 4.047089623985812, t_q1 = 0.5451194541528821
NPartitions 8: t_read_csv = 2.7962855999358, t_q1 = 0.6558004750404507
NPartitions 16: t_read_csv = 2.23113769502379, t_q1 = 0.9809432020410895
NPartitions 32: t_read_csv = 2.945883085951209, t_q1 = 1.4824977009557188
NPartitions 64: t_read_csv = 6.381267024902627, t_q1 = 2.4221810521557927
NPartitions 112: t_read_csv = 10.344957336084917, t_q1 = 4.014988245908171
```

Using `Ray` engine:
```
NPartitions 1: t_read_csv = 11.100145738106221, t_q1 = 2.5809421001467854
NPartitions 2: t_read_csv = 5.8055718711111695, t_q1 = 0.7596940419171005
NPartitions 4: t_read_csv = 3.418055210961029, t_q1 = 0.4094508239068091
NPartitions 8: t_read_csv = 2.130840379977599, t_q1 = 0.2652973970398307
NPartitions 16: t_read_csv = 1.2922572700772434, t_q1 = 0.22306963219307363
NPartitions 32: t_read_csv = 1.0537066240794957, t_q1 = 0.2509973889682442
NPartitions 64: t_read_csv = 0.9454989689402282, t_q1 = 0.3319866650272161
NPartitions 112: t_read_csv = 0.8996511569712311, t_q1 = 0.5486591379158199
```

**Comment by RehanSD** [comment] 2022-10-12 02:26
This issue is closely related to #4771 - @vnlitvinov I know you're looking into Dask performance - is there an issue you'd like me to mark this as duplicate of? @amyskov are these performance regressions still appearing on master?

**Comment by anmyachev** [comment] 2024-02-12 18:56
@YarShev maybe performance is better for Dask after https://github.com/modin-project/modin/pull/6923?

**Comment by YarShev** [comment] 2024-02-13 12:17
I was not able to reproduce the timings that could be close to the ones @amyskov got. The results on my side are the following.

**Ray**

| n_parts | t_read_csv | t_q1 |
| - | - | - |
| 1 | 225.494053557049 | 0.0104466099292039 |
| 2 | 116.171911476994 | 0.0125042090658098 |
| 4 | 65.0786247149808 | 0.0171610959805548 |
| 8 | 42.3449094820534 | 0.018581029959023 |
| 16 | 29.19051441201 | 0.0236598890041932 |
| 32 | 23.9421438339632 | 0.0402906810631975 |
| 64 | 23.055262812064 | 0.091434470959939 |
| 112 | 21.3282443480566 | 0.161457304959185 |

**Dask**

| n_parts | t_read_csv | t_q1 |
| - | - | - |
| 1 | 206.391317273024 | 0.603845763020217 |
| 2 | 113.745626520947 | 0.395694517996162 |
| 4 | 70.2301639990182 | 0.220194590045139 |
| 8 | 43.994167040917 | 0.413239429006353 |
| 16 | 31.7900107440073 | 0.415865643997676 |
| 32 | 29.7193668789695 | 0.317177049000747 |
| 64 | 27.9015994661021 | 0.926613126997835 |
| 112 | 30.3219884240534 | 1.17596448003314 |

Ran with MODIN_CPUS=112. To get Dask working I had to adjust memory limit per Dask worker because it wasn't working with the default value. I think the results are pretty good and explain the scalability. @anmyachev, any concerns on closing this issue?

**Comment by YarShev** [comment] 2024-02-13 14:11
If Memory config is not set, we use "auto" for memory limit per Dask worker. In some cases (changing n_parts) I saw warnings like this.

```bash
WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 16.69 GiB -- Worker memory limit: 20.83 GiB
```

Dask set memory limit per worker to ~20GB. It wasn't sufficient to perform the whole script and it failed eventually. This is why I had to adjust the memory limit per worker.

**Closed by YarShev** 2024-02-13 14:11 UTC
Labels: Performance 🚀, Needs more information ❔, Dask ⚡, P1

**Comment by anmyachev** [comment] 2024-02-13 14:34
> If Memory config is not set, we use "auto" for memory limit per Dask worker. In some cases (changing n_parts) I saw warnings like this.
> 
> ```shell
> WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 16.69 GiB -- Worker memory limit: 20.83 GiB
> ```
> 
> Dask set memory limit per worker to ~20GB. It wasn't sufficient to perform the whole script and it failed eventually. This is why I had to adjust the memory limit per worker.

Should we change default memory limit in that case?

**Comment by YarShev** [comment] 2024-02-13 15:33
I don't think so because it works for most cases. I saw the warnings when n_parts is much less than n_workers. As a rule, it is supposed to use n_parts equals to n_workers.
