### ISSUE TITLE
BUG: df['col'] fails to return column as a Series

### ISSUE THREAD

**Issue by labanyamukhopadhyay** [modin-project/modin#5623] opened 2023-02-03 21:33 UTC
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.pandas as pd
d = {'a': [1, 2, 3], 'b': [1, 2, 3], 'c': [1, 2, 3]}
df = pd.DataFrame(data=d)
df['a']
```

### Issue Description

Returning a column from a df as a Series returns `TypeError: data type 'category' not understood` due to   
https://github.com/modin-project/modin/blob/0df5fbf7a66663110878633467e4488ad37b0337/modin/pandas/series.py#L411

### Expected Behavior

<img width="461" alt="Screen Shot 2023-02-03 at 1 16 17 PM" src="https://user-images.githubusercontent.com/17665008/216712295-144701dd-1056-4084-a429-4ca6c88baef3.png">

### Error Logs

<details>

```python-traceback

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/opt/anaconda3/lib/python3.9/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/opt/anaconda3/lib/python3.9/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/opt/anaconda3/lib/python3.9/site-packages/modin/logging/logger_decorator.py in run_and_log(*args, **kwargs)
    126             """
    127             if LogMode.get() == "disable":
--> 128                 return obj(*args, **kwargs)
    129 
    130             logger = get_logger()

~/opt/anaconda3/lib/python3.9/site-packages/modin/pandas/series.py in __repr__(self)
    409             isinstance(temp_df, pandas.Series)
    410             and temp_df.name is not None
--> 411             and temp_df.dtype == "category"
    412         ):
    413             maxsplit = 2

TypeError: data type 'category' not understood

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 9068fbcfd7d4c169018ae706d6c96edea6db0cd1
python           : 3.9.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.18.1
ray              : 2.2.0
dask             : 2021.10.0
distributed      : 2021.10.0
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.3
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 58.0.4
pip              : 21.2.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
brotli           : 
fastparquet      : None
fsspec           : 2021.08.1
gcsfs            : None
matplotlib       : 3.6.3
numba            : 0.54.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
snappy           : None
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None
tzdata           : None

</details>

**Comment by mvashishtha** [comment] 2023-02-03 21:40
@labanyamukhopadhyay thank you for reporting this issue. I can't reproduce it at commit 9068fbcfd7d4c169018ae706d6c96edea6db0cd1.

@modin-project/modin-contributors @modin-project/modin-core can someone help here? I'm not sure what I'm missing. I tried:

1) check out 9068fbcfd7d4c169018ae706d6c96edea6db0cd1
1) `pip install -e .[all]`

And the snippet @labanyamukhopadhyay provided works.

**Comment by mvashishtha** [comment] 2023-02-03 21:44
Trying again with:

1) `conda create --name=modin-5623-repro python=3.9.7`
1) `conda activate modin-5623-repro`
1) `pip install ipython`
1) `pip install modin[ray]==0.18.1`
`) in ipython, run the reproducer

and I get the output I want.

@labanyamukhopadhyay can you double check that this is exactly the code that reproduces the issue? Are you on modin 0.18.1 and python 3.9.7?

My system:

- macOS Monterey
- Version 12.4
- MacBook Pro (16-inch, 2019)
- Processor: 2.3 GHz 8-core intel core i9

**Comment by labanyamukhopadhyay** [comment] 2023-02-03 22:25
> 

@mvashishtha I tried the above in ipython in terminal and I got the output that I wanted. However, I run the following in jupyter notebook and the same TypeError is returned.
<img width="1093" alt="Screen Shot 2023-02-03 at 2 22 33 PM" src="https://user-images.githubusercontent.com/17665008/216722478-e1aa59b1-da04-42ea-b8d1-fbc9492bc145.png">

pd.show_versions() returns:

INSTALLED VERSIONS
------------------
commit           : 9068fbcfd7d4c169018ae706d6c96edea6db0cd1
python           : 3.9.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

Modin dependencies
------------------
modin            : 0.18.1
ray              : 2.2.0
dask             : 2021.10.0
distributed      : 2021.10.0
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.3
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 58.0.4
pip              : 21.2.4
...

**Comment by mvashishtha** [comment] 2023-02-06 15:17
@labanyamukhopadhyay I was able to reproduce that bug by changing numpy to 1.20.3. For now can you try upgrading to 1.23.2? For the longer term fix I have filed #5627.

**Comment by labanyamukhopadhyay** [comment] 2023-02-07 21:50
> 

@mvashishtha Yes upgrading numpy version resolves the error!

**Comment by mvashishtha** [comment] 2023-02-07 21:51
@labanyamukhopadhyay great! I will close this issue and we'll leave #5627 open for the modin fix.

**Closed by mvashishtha** 2023-02-07 21:51 UTC
Labels: bug 🦗, Needs more information ❔, P1
