### ISSUE TITLE
got an error when loading pickle file

### ISSUE THREAD

**Issue by joseberlines** [modin-project/modin#2994] opened 2021-04-20 09:03 UTC
# reading the DF with modin
```
tic = datetime.now()
size = os.path.getsize(outputFile)
print(f'OUTPUT_DATA.pkl is {str(round(size / (1024 * 1024), 3))} Megabytes')
OUTPUT_DATA_df = pd.read_pickle(outputFile)
print(f'{outputFile} was loaded as DataFrame')
print(f'There are {len(OUTPUT_DATA_df)} lines')
toc = datetime.now()
print(f'time= {toc-tic} seconds')
```

OUTPUT_DATA.pkl is 18030.622 Megabytes

```
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
---------------------------------------------------------------------------
StreamClosedError                         Traceback (most recent call last)
/opt/conda/lib/python3.8/site-packages/distributed/comm/tcp.py in read(self, deserializers)
    186         try:
--> 187             n_frames = await stream.read_bytes(8)
    188             n_frames = struct.unpack("Q", n_frames)[0]

StreamClosedError: Stream is closed
```
and at the end of the error change:
`CommClosedError: in <closed TCP>: Stream is closed`

I am reading a pickle file that pandas reads ok, but modin have problems with.
Should I read it with pandas and rather save under other format for later on re-read it

**Comment by mvashishtha** [comment] 2022-10-12 04:36
@joseberlines I'm closing this issue as it's hard to reproduce without the pickle file, and it's been well over a year since you opened this issue. I'm very sorry none of the Modin contributors commented here. Please comment here if you can give a complete reproducer, or if you have any other concerns.

**Closed by mvashishtha** 2022-10-12 04:36 UTC
Labels: question ❓
