### ISSUE TITLE
read_csv with Ray engine fails with some combinations of `Column and Index Locations and Names` parameters

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2312] opened 2020-10-26 13:18 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Modin version** (`modin.__version__`): 0.8.1.1+34.ga571e10
- **Python version**: 3.8.6
- **Code we can use to reproduce**:
```
import os

os.environ["MODIN_ENGINE"] = "ray"

import pandas
import modin.pandas as pd
from modin.pandas.test.utils import df_equals

test_filename = "test.csv"
kwargs = {
    "filepath_or_buffer": test_filename,
    "index_col": "col1",
    "usecols": ["col1"],
}
str_two_cols = """col1,col2
0,1
2,3
"""

try :
    with open(test_filename, "w") as f:
        f.write(str_two_cols)

    df_pandas = pandas.read_csv(**kwargs)
    print(df_pandas)
    df_pd = pd.read_csv(**kwargs)
    print(df_pd)
    df_equals(df_pd, df_pandas)
finally:
    os.remove(test_filename)
```

### Source code / logs

```
Empty DataFrame
Columns: []
Index: [0, 2]
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    df_pd = pd.read_csv(**kwargs)
  File "/localdisk/amyskov/modin/modin/pandas/io.py", line 109, in parser_func
    return _read(**kwargs)
  File "/localdisk/amyskov/modin/modin/pandas/io.py", line 127, in _read
    pd_obj = EngineDispatcher.read_csv(**kwargs)
  File "/localdisk/amyskov/modin/modin/data_management/factories/dispatcher.py", line 104, in read_csv
    return cls.__engine._read_csv(**kwargs)
  File "/localdisk/amyskov/modin/modin/data_management/factories/factories.py", line 87, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "/localdisk/amyskov/modin/modin/engines/base/io/file_reader.py", line 29, in read
    query_compiler = cls._read(*args, **kwargs)
  File "/localdisk/amyskov/modin/modin/engines/base/io/text/csv_reader.py", line 142, in _read
    column_chunksize = compute_chunksize(empty_pd_df, num_splits, axis=1)
  File "/localdisk/amyskov/modin/modin/data_management/utils.py", line 54, in compute_chunksize
    col_chunksize = get_default_chunksize(len(df.columns), num_splits)
  File "/localdisk/amyskov/modin/modin/data_management/utils.py", line 29, in get_default_chunksize
    length // num_splits if length % num_splits == 0 else length // num_splits + 1
ZeroDivisionError: integer division or modulo by zero
```

**Comment by amyskov** [comment] 2020-10-26 14:13
Since Modin `read_csv` fails with several combinations of `Column and Index Locations and Names` parameters (with `ray` engine), the scope of this issue will be expanded to cover issues with all `Column and Index Locations and Names` parameters.

**Comment by amyskov** [comment] 2020-10-26 14:21
Reproducer of incorrect output with `header`, `prefix` and `usecols` parameters provided:
```
import os

os.environ["MODIN_ENGINE"] = "ray"

import pandas
import modin.pandas as pd
from modin.pandas.test.utils import df_equals

test_filename = "test.csv"
kwargs = {
    "filepath_or_buffer": test_filename,
    "header": None,
    "prefix": "col",
    "usecols": ["col1"],
}
str_two_cols = """col1,col2
0,1
2,3
"""

try:
    with open(test_filename, "w") as f:
        f.write(str_two_cols)

    df_pandas = pandas.read_csv(**kwargs)
    print(df_pandas)
    df_pd = pd.read_csv(**kwargs)
    print(df_pd)
    df_equals(df_pd, df_pandas)
finally:
    os.remove(test_filename)
```
Output:
```
Empty DataFrame
Columns: [col1]
Index: []
   col1
0  col2
1     1
2     3
Traceback (most recent call last):
  File "test.py", line 61, in <module>
    df_equals(df_pd, df_pandas)
  File "/localdisk/amyskov/modin/modin/pandas/test/utils.py", line 500, in df_equals
    assert False, "One of the passed frames is empty, when other isn't"
AssertionError: One of the passed frames is empty, when other isn't
```

**Comment by ymoslem** [comment] 2021-07-12 21:43
Hello! Thanks for your efforts! Any coming fix or current workaround for this please? I have several files that I cannot open due to this bug. Thanks! @amyskov

**Comment by ymoslem** [comment] 2021-07-13 18:39
@amyskov Yes, sure.

Here are the steps to reproduce this issue:

1. Download and unzip this file ([link](https://object.pouta.csc.fi/OPUS-ELRA-W0309/v1/moses/en-fr.txt.zip)).
2. Run the following code:
```

import modin.pandas as pd
import ray
import os
os.environ["MODIN_ENGINE"] = "ray"
ray.init()

file_name = "ELRA-W0309.en-fr.en"
df = pd.read_csv(file_name, names=['English'], sep="\n")
```
3. This gives an error:
> ZeroDivisionError: integer division or modulo by zero

I have also other files where everything works fine, like [this one](https://object.pouta.csc.fi/OPUS-ELRA-W0301/v1/moses/en-fr.txt.zip).

Thanks!

**Comment by amyskov** [comment] 2021-07-14 10:58
@ymoslem, temporally this bug can be avoided by adding `index_col=False` option to the `read_csv` function, see example below:
```
import modin.pandas as pd
import pandas
import ray
import os
os.environ["MODIN_ENGINE"] = "ray"
ray.init()

from modin.pandas.test.utils import df_equals

file_name = "ELRA-W0309.en-fr.en"

df_pandas = pandas.read_csv(file_name, names=['English'], sep="\n")
df_pd = pd.read_csv(file_name, names=['English'], sep="\n", index_col=False)
df_pd.reset_index(drop=True, inplace=True) # indexes aligning between pandas and Modin

df_equals(df_pandas, df_pd) # df_pd and df_pandas are equal!
```
Hope this helps!

**Comment by ymoslem** [comment] 2021-07-16 20:04
Adding the `index_col=False` option solved it. Thanks a lot! @amyskov 
```
df = pd.read_csv(file_name, names=['English'], sep="\n", index_col=False)
```

**Comment by pyrito** [comment] 2022-08-22 20:57
I am not able to reproduce this bug on master, so I'll go ahead and close this issue. Please re-open if needed!

**Closed by pyrito** 2022-08-22 20:57 UTC
Labels: bug 🦗, Epic
