### ISSUE TITLE
Bad Performance on List Comprehension Operations compared to Pandas

### ISSUE THREAD

**Issue by benaurelschill** [modin-project/modin#4938] opened 2022-09-06 23:17 UTC
### System information
- Linux Red Hat Enterprise Linux 9.0
- Modin Version 0.15.2
- Python 3.9.10 

Currently, i am trying to optimize our data cleaning with modin. We have some list comprehension tasks we want to perform on our dataframe. Our csv for reading in the data is around 1.5gb. 
The linux virtual machine has 32 gb of ram and 8 cores and i am running jupyter labs with ray as modins backend.
I want to perform a list comprehension on a modin dataframe: 

`df['UsedN'] = [0 if y == 0 else (x / y * 100) for x,y in zip(df['Used'],df['Capacity'])]`

With pandas this operation takes around 2 seconds but with modin it takes **37 seconds**. 
The dataframe has around 70k rows.
I understand that this dataset is not the biggest and I will certainly see the performance gain when I use bigger datasets but I find it odd that it performs this much worse compared to pandas.  I also tried it with my local mac and got similar results. 
Any ideas why this could happen or is it expected behaviour?

**Comment by mvashishtha** [comment] 2022-09-06 23:42
@benaurelschill thanks for reporting your issue. I see you are iterating over every element in the series`df['Used']` and `df['Capacity']`. It's best to avoid iteration in pandas, but in Modin iteration tends to be [extra slow](https://modin.readthedocs.io/en/stable/usage_guide/optimization_notes/index.html#avoid-iterating-over-modin-dataframe). Is it possible to rewrite your code so it uses `apply` as follows:

```python
def row_func(row):
  if row['Capacity'] == 0:
    return 0
  else:
    return row['Used'] / row['Capacity'] * 100

df['UsedN'] = df.apply(row_func, axis=1)
```

Please let me know whether that helps. If it doesn't, please try to provide a reproducer that demonstrates the slowness here.

**Comment by benaurelschill** [comment] 2022-09-07 00:17
@mvashishtha thanks for pointing this issue out. I was able to get the processing time down to 13 seconds, however still takes 10 seconds longer than pandas which is a little bit disappointing. I would have to try out if it will outperform pandas on datasets > 2gb.

**Comment by pyrito** [comment] 2022-09-09 20:22
Hi @benaurelschill do you have any updates on this issue?

**Comment by mvashishtha** [comment] 2022-09-21 20:57
@benaurelschill because you haven't posted updates in over two weeks, I'm going to close this issue. The modin contributors would really like to help. Please comment again if you still have questions or concerns.

**Closed by mvashishtha** 2022-09-21 20:57 UTC
Labels: bug 🦗, Performance 🚀, question ❓, Needs more information ❔, P1
