### ISSUE TITLE
A Bug has found when DataFrame object was used in a python MultiProcess Pool's target Methond

### ISSUE THREAD

**Issue by crystalxiaoou** [modin-project/modin#910] opened 2019-12-15 14:40 UTC
### System information
- **OS Platform and Distribution **: MacOS Mojave 10.14.5
- **Modin installed from (source or binary)**: binary (by pip install modin[ray])
- **Modin version**: 0.6.3
- **Python version**: 3.7.5
- **Exact command to reproduce**:

### Describe the problem
A Bug has found when DataFrame object was used in a python MultiProcess Pool's apply_async().
when I passed the dataframe object to a Sub-Process in my Program as a parameter, then I called query() and pivot_table(), group_by() method in the sub-process, 
A Error was happend in my program:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 1898, in __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'DataFrame' object has no attribute '_query_compiler'

The same thing occured in My Program  when  DataFrame object was used in a python MultiProcess  .

### Source code / logs
def test(recv_params,month_data_fram):
       
    data_frame = pd.pivot_table(init_data_frame, index=arr_index, columns=["a", "b"], values=arr_value,
                                aggfunc=sum, fill_value=0)
     data_frame.sort_index(axis=1, inplace=True)
    data_frame.reset_index(drop=False, inplace=True)
    

month_data_frame = pd.read_csv('test.csv', header=None  )
 pool = Pool(5)
 pool.apply_async(func=test, args=(recv_params, month_data_frame,))
pool.apply_async(func=test, args=(recv_params, month_data_frame,))
pool.apply_async(func=test, args=(recv_params,  month_data_frame,))
pool.apply_async(func=test, args=(recv_params, month_data_frame,))
pool.apply_async(func=test, args=(recv_params, month_data_frame,))

pool.close()
pool.join()

### The Error Result logs

2019-12-15 22:11:50,645	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-12-15_22-11-50_645359_95325/logs.
2019-12-15 22:11:50,755	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:19545 to respond...
2019-12-15 22:11:50,885	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:37359 to respond...
2019-12-15 22:11:50,887	INFO services.py:809 -- Starting Redis shard with 3.44 GB max memory.
2019-12-15 22:11:50,899	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-12-15_22-11-50_645359_95325/logs.
2019-12-15 22:11:50,900	INFO services.py:1475 -- Starting the Plasma object store with 2.0 GB memory using /tmp.
 * Running on http://127.0.0.1:5555/ (Press CTRL+C to quit)
get one month data frame 9.5367431640625e-07
read total csv 0.2861649990081787
UserWarning: User-defined function verification is still under development in Modin. The function provided is not verified.
UserWarning: Distributing <class 'NoneType'> object. This may take some time.
query productId AND reportType 0.2645399570465088
UserWarning: `DataFrame.__getstate__` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
UserWarning: `DataFrame.__getstate__` defaulting to pandas implementation.
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 1898, in __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'DataFrame' object has no attribute '_query_compiler'

During handling of the above exception, another exception occurred:

n occurred:

=
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 1898, in __getattr__
    return object.__getattribute__(self, key)
AttributeError: 'DataFrame' object has no attribute '_query_compiler'

During handling of the above exception, another exception occurred:

packages/modin/pandas/dataframe.py", line 1900, in __getattr__
    if key in self.columns:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/modin/pandas/base.py", line 3444, in __getattribute__
    return object.__getattribute__(self, item)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 132, in _get_columns
    return self._query_compiler.columns
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 1900, in __getattr__
    if key in self.columns:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/modin/pandas/base.py", line 3444, in __getattribute__
    return object.__getattribute__(self, item)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 132, in _get_columns
    return self._query_compiler.columns
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by devin-petersohn** [comment] 2019-12-17 19:48
Hi @crystalxiaoou, thanks for posting! This is a duplicate of question #550. Please feel free to continue the conversation there!

**Closed by devin-petersohn** 2019-12-17 19:48 UTC
Labels: duplicate :recycle:

**Comment by crystalxiaoou** [comment] 2019-12-23 02:14
I don't understand what do you mean in question #550 .  I want to know if I passed the modin DataFrame object to a MultiProcess func's args, how to Make it work.

**Comment by devin-petersohn** [comment] 2019-12-23 18:00
In the issue it says that Modin DataFrames are not serializable and therefore cannot be used with MultiProcessing yet.
