### ISSUE TITLE
[DOCS] Warning in dataframe_supported: unknown target name

### ISSUE THREAD

**Issue by vfdev-5** [modin-project/modin#2432] opened 2020-11-14 23:31 UTC
### Describe the problem

When building docs I see the following warnings:
```
/modin/docs/supported_apis/dataframe_supported.rst:82: WARNING: Unknown target name: "compare".
/modin/docs/supported_apis/dataframe_supported.rst:444: WARNING: Unknown target name: "value_counts".
```

**Comment by devin-petersohn** [comment] 2020-11-15 23:38
Closing as duplicate of #2428

**Closed by devin-petersohn** 2020-11-15 23:38 UTC
Labels: duplicate :recycle:
