### ISSUE TITLE
import modin.pandas as pd followed by import ray segfaults

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4678] opened 2022-07-15 19:55 UTC
This is with modin and ray pip-installed but not yet modin[ray].    Switching the order of the imports gets rid of the segfault and replaces it with a much more useful "ImportError: Please `pip install modin[ray]` to install compatible Ray version (>=1.4.0,<1.13.0)."

Mac, py39

**Comment by mvashishtha** [comment] 2022-07-15 22:06
@jbrockmendel could you give some more details about the steps you took? I tried to replicate what you described, but I didn't get the same error. I'm on:

- MacBook Pro (16-inch, 2019) with macOS Monterey.
- python 3.9.12

I created and activated a new conda environment, then did:

`pip install modin ray`

Then in ipython did:

```python
import modin.pandas as pd
import ray

pd.DataFrame()
```

and I didn't get a dataframe.

**Comment by mvashishtha** [comment] 2022-07-18 20:25
@jbrockmendel I do get an exception ending in `ImportError: Please `pip install modin[ray]` to install compatible Ray version (>=1.4.0,<1.13.0).` on my Mac when:

1) I leave my virtualenv
2) I uninstall modin and ray
3) I install modin and ray separately with `pip install modin ray`
4) I run in ipython:

```python
import modin.pandas as pd
import  ray

pd.DataFrame()
```

and I get the same error when I switch the order of the imports. So I can't reproduce the segfault. Could you please share more information about the segfault?

<details>
<summary>Stack trace from code above</summary>

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /usr/local/lib/python3.9/site-packages/modin/config/pubsub.py:253, in Parameter.get(cls)
    252 try:
--> 253     raw = cls._get_raw_from_config()
    254 except KeyError:

File /usr/local/lib/python3.9/site-packages/modin/config/envvars.py:46, in EnvironmentVariable._get_raw_from_config(cls)
     33 """
     34 Read the value from environment variable.
     35
   (...)
     44     If value is absent.
     45 """
---> 46 return os.environ[cls.varname]

File /usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py:679, in _Environ.__getitem__(self, key)
    677 except KeyError:
    678     # raise KeyError with the original key value
--> 679     raise KeyError(key) from None
    680 return self.decodevalue(value)

KeyError: 'MODIN_ENGINE'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Input In [3], in <module>
----> 1 pd.DataFrame()

File /usr/local/lib/python3.9/site-packages/modin/logging/logger_metaclass.py:68, in logger_class_wrapper.<locals>.log_wrap(*args, **kwargs)
     66     logger.info(f"END::PANDAS-API::{class_name}.{method_name}")
     67     return result
---> 68 return method(*args, **kwargs)

File /usr/local/lib/python3.9/site-packages/modin/pandas/dataframe.py:114, in DataFrame.__init__(self, data, index, columns, dtype, copy, query_compiler)
    102 def __init__(
    103     self,
    104     data=None,
   (...)
    111     # Siblings are other dataframes that share the same query compiler. We
    112     # use this list to update inplace when there is a shallow copy.
    113     self._siblings = []
--> 114     Engine.subscribe(_update_engine)
    115     if isinstance(data, (DataFrame, Series)):
    116         self._query_compiler = data._query_compiler.copy()

File /usr/local/lib/python3.9/site-packages/modin/config/pubsub.py:213, in Parameter.subscribe(cls, callback)
    204 """
    205 Add `callback` to the `_subs` list and then execute it.
    206
   (...)
    210     Callable to execute.
    211 """
    212 cls._subs.append(callback)
--> 213 callback(cls)

File /usr/local/lib/python3.9/site-packages/modin/pandas/__init__.py:114, in _update_engine(publisher)
    111     publisher.put("Native")
    112     IsExperimental.put(True)
    113 if (
--> 114     publisher.get() == "Native"
    115     and StorageFormat.get_value_source() == ValueSource.DEFAULT
    116 ):
    117     StorageFormat.put("Omnisci")
    118     IsExperimental.put(True)

File /usr/local/lib/python3.9/site-packages/modin/config/pubsub.py:255, in Parameter.get(cls)
    253     raw = cls._get_raw_from_config()
    254 except KeyError:
--> 255     cls._value = cls._get_default()
    256     cls._value_source = ValueSource.DEFAULT
    257 else:

File /usr/local/lib/python3.9/site-packages/modin/config/envvars.py:102, in Engine._get_default(cls)
     97 else:
     98     if (
     99         version.parse(ray.__version__) < MIN_RAY_VERSION
    100         or version.parse(ray.__version__) >= MAX_RAY_VERSION_EXCLUSIVE
    101     ):
--> 102         raise ImportError(
    103             "Please `pip install modin[ray]` to install compatible Ray "
    104             + "version "
    105             + f"(>={MIN_RAY_VERSION},<{MAX_RAY_VERSION_EXCLUSIVE})."
    106         )
    107     return "Ray"
    108 try:

ImportError: Please `pip install modin[ray]` to install compatible Ray version (>=1.4.0,<1.13.0).
```
</details>

**Comment by jbrockmendel** [comment] 2022-07-22 23:40
Another one: running pytest modin/pandas/test_io.py segfaults at the `import ray` line.  In `ray.__init__` i can track it down to the `import ray._raylet` line.

importing ray on its own works fine; seems like this may be the only test file that directly imports ray?

**Comment by pyrito** [comment] 2022-08-31 21:08
@jbrockmendel are you still dealing with this issue?

**Comment by jbrockmendel** [comment] 2022-08-31 21:14
havent seen it for a bit

**Comment by pyrito** [comment] 2022-08-31 21:25
@jbrockmendel I'm going to go ahead and close this issue for now. If it persists please do open another issue!

**Closed by pyrito** 2022-08-31 21:25 UTC
Labels: Needs more information ❔
