### ISSUE TITLE
dropna returning  ValueError but works in Pandas

### ISSUE THREAD

**Issue by Jflick58** [modin-project/modin#541] opened 2019-04-10 23:17 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14 Mojave
- **Modin installed from (source or binary)**: binary
- **Modin version**: Latest
- **Python version**: Anaconda 2018.12 (Python3.7)
- **Exact command to reproduce**: df.dropna(subset=[col_a, col_b])

### Describe the problem
dropna call works if I run it in Pandas, but if I run it with Modin it throws a ValueError:  Length of Values does not match length of index

### Source code / logs

Traceback (most recent call last):
  File "file.py", line 551, in <module>
    cProfile.run("test()")
  File "/anaconda3/lib/python3.7/cProfile.py", line 16, in run
    return _pyprofile._Utils(Profile).run(statement, filename, sort)
  File "/anaconda3/lib/python3.7/profile.py", line 53, in run
    prof.run(statement)
  File "/anaconda3/lib/python3.7/cProfile.py", line 95, in run
    return self.runctx(cmd, dict, dict)
  File "/anaconda3/lib/python3.7/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "file.py", line 547, in test
    dw.process_data()
  File "file.py", line 86, in process_data
    self.pipeline(chunk)
  File "filepy", line 133, in pipeline
    chunk.dropna(subset=["COL_A", "COL_B"], inplace=True) #drop rows that have either a null COL_A or null COL_C
  File "/anaconda3/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 542, in dropna
    axis=axis, how=how, thresh=thresh, subset=subset
  File "/anaconda3/lib/python3.7/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py", line 1804, in dropna
    compute_na = self.getitem_column_array(subset)
  File "/anaconda3/lib/python3.7/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py", line 2290, in getitem_column_array
    0, getitem, numeric_indices, keep_remaining=False
  File "/anaconda3/lib/python3.7/site-packages/modin/engines/base/block_partitions.py", line 705, in apply_func_to_select_indices
    if self.partitions.size == 0:
  File "/anaconda3/lib/python3.7/site-packages/modin/engines/base/block_partitions.py", line 68, in _get_partitions
    for i in range(len(self._partitions_cache))
  File "/anaconda3/lib/python3.7/site-packages/modin/engines/base/block_partitions.py", line 68, in <listcomp>
    for i in range(len(self._partitions_cache))
  File "/anaconda3/lib/python3.7/site-packages/modin/engines/base/block_partitions.py", line 66, in <listcomp>
    if self.block_lengths[i] != 0 and self.block_widths[j] != 0
  File "/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/block_partitions.py", line 41, in block_lengths
    if len(self._partitions_cache.T) > 0
  File "/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 2202, in get
    raise value
ray.worker.RayTaskError: ray_worker (pid=26375, host=Macbook-10401.local)
ray.worker.RayTaskError: ray_worker (pid=26370, host=Macbook-10401.local)
  File "/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/axis_partition.py", line 84, in deploy_ray_func
    return func(*args)
  File "/anaconda3/lib/python3.7/site-packages/modin/engines/base/axis_partition.py", line 187, in deploy_axis_func
    result = func(dataframe, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py", line 172, in helper
    return pandas_func(df, internal_indices=internal_indices, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py", line 2334, in setitem
    df[df.columns[internal_indices[0]]] = value
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3370, in __setitem__
    self._set_item(key, value)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3445, in _set_item
    value = self._sanitize_column(key, value)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3630, in _sanitize_column
    value = sanitize_index(value, self.index, copy=False)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 519, in sanitize_index
    raise ValueError('Length of values does not match length of index')
ValueError: Length of values does not match length of index

**Comment by devin-petersohn** [comment] 2019-04-10 23:26
Thanks @Jflick58! 
What was the line run above this? It looks like it may have originated before this. Are you using `df["COL_A"] = ...` or something to that effect? That may be where the bug is originating.

**Comment by Jflick58** [comment] 2019-04-10 23:37
The previous lines are:

`df["COL_C"] = self.col_c #type int`
`df["COL_B"] = df["COL_B"].replace(r"(%20)", np.nan, regex=True)`
`df["COL_A"] = df["COL_A"].str.extract(r"(\d{4,16})", expand=True)`

**Comment by devin-petersohn** [comment] 2019-04-11 01:13
Thanks @Jflick58, I will dig into this. At a first glance, it appears that the `expand` on the `extract` call is creating a 1-column DataFrame, and Modin is failing to apply that column to the series. This should be a relatively straight-forward fix, thanks for the report!

**Comment by Jflick58** [comment] 2019-04-11 17:59
@devin-petersohn  thanks for being so responsive. I'm looking forward trying Modin once this is fixed.

**Comment by wuisawesome** [comment] 2019-04-12 18:21
Btw I think a minimal reproduction of this bug is 

```
df = pd.DataFrame({'A': list(range(10))})
df['A'] = pd.DataFrame(df['A'])
str(df)
```

**Comment by devin-petersohn** [comment] 2019-04-26 13:54
Closing #541 via #545.

**Closed by devin-petersohn** 2019-04-26 13:54 UTC
Labels: bug :bug:
