### ISSUE TITLE
groupby(as_index=False) loses the grouping column

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1049] opened 2020-02-04 21:12 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 19.10
- **Modin installed from (source or binary)**:
Source
- **Modin version**:
0.7.0+3.g7528bf3
- **Python version**:
Python 3.7.5
- **Exact command to reproduce**:

### Describe the problem

When `groupby` is called with `as_index=False` parameter, column which data is being grouped on is absent from the result.

### Source code / logs

Reproducer code looks like this
```python
#import pandas as pd
import ray
ray.init(huge_pages=True, plasma_directory="/mnt/hugepages")
import modin.pandas as pd

df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                  index=[1, 2, 3],
                  columns=['max_speed', 'shield'])
print(df)

df1 = df.groupby('max_speed', as_index=False).mean()
print(df1)
```

When I run the following reproducer code on Pandas I get the following output (nothing changes)
```
   max_speed  shield
1          1       2
2          4       5
3          7       8
   max_speed  shield
0          1       2
1          4       5
2          7       8
```

when I do the same on modin, I don't see `max_speed` column any more
```
   max_speed  shield
1          1       2
2          4       5
3          7       8
   shield
0       2
1       5
2       8
```

**Comment by devin-petersohn** [comment] 2020-02-04 21:47
Hi @gshimansky, this is a duplicate of #1033 and there's a fix in progress with #1041.

Closing as duplicate, feel free to continue the conversation on #1033.

**Closed by devin-petersohn** 2020-02-04 21:47 UTC
Labels: duplicate :recycle:
