### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'core'

### ISSUE THREAD

**Issue by palash247** [modin-project/modin#3014] opened 2021-04-26 06:37 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04 WSL
- **Modin version** (`modin.__version__`):0.9.1 and master
- **Python version**:3.7.7
- **Ray version**: 1.1.0, 1.2.0 and nightly
- **Code we can use to reproduce**: I replaced `import pandas as pd` with `import modin.pandas as pd` in a very complex piece of code. Currently, I can not really pinpoint where exactly the code is breaking but this seems to be a problem with ray's deserialization and imports (Probably related ray issues [#1175](https://github.com/modin-project/modin/issues/1175)). I'll update the issue as soon as I can reproduce it with a concise code.

### Describe the problem

After replacing the pandas import with modin, I am currently getting two exceptions. `AttributeError: module 'pandas' has no attribute 'core'` and `AttributeError: 'int' object has no attribute 'columns'`. I can execute the sample code in the documentation. My end goal is to run the code on the ray cluster on k8s (Experimenting), but this error I am getting locally. Traceback is as follows. 

**Comes some time**:
```
2021-04-25 23:13:26,637 ERROR worker.py:78 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::deploy_ray_func() (pid=194, ip=172.17.0.2)
  File "python/ray/_raylet.pyx", line 506, in ray._raylet.execute_task
  File "/home/ray/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/axis_partition.py", line 114, in deploy_ray_func
    result = func(*args)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py", line 294, in deploy_axis_func
    if sum(lengths) != len(result.columns):
AttributeError: 'int' object has no attribute 'columns'
```
**This one is regular**:
```
(pid=1043) 2021-04-25 23:14:02,598      ERROR serialization.py:250 -- module 'pandas' has no attribute 'core'
(pid=1043) Traceback (most recent call last):
(pid=1043)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 248, in deserialize_objects
(pid=1043)     obj = self._deserialize_object(data, metadata, object_ref)
(pid=1043)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 190, in _deserialize_object
(pid=1043)     return self._deserialize_msgpack_data(data, metadata_fields)
(pid=1043)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 168, in _deserialize_msgpack_data
(pid=1043)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(pid=1043)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 156, in _deserialize_pickle5_data
(pid=1043)     obj = pickle.loads(in_band, buffers=buffers)
(pid=1043)   File "/home/ray/anaconda3/lib/python3.7/site-packages/pandas/__init__.py", line 179, in <module>
(pid=1043)     import pandas.testing
(pid=1043)   File "/home/ray/anaconda3/lib/python3.7/site-packages/pandas/testing.py", line 5, in <module>
(pid=1043)     from pandas._testing import (
(pid=1043)   File "/home/ray/anaconda3/lib/python3.7/site-packages/pandas/_testing.py", line 3054, in <module>
(pid=1043)     cython_table = pd.core.base.SelectionMixin._cython_table.items()
(pid=1043) AttributeError: module 'pandas' has no attribute 'core'
````

**Comment by devin-petersohn** [comment] 2021-04-26 21:45
Hi @palash247 thanks for posting! This does look like a Ray serialization issue.

What is the pandas version on the k8s cluster? Is Modin also installed there?

cc @modin-project/modin-ray

**Comment by palash247** [comment] 2021-04-27 03:05
Thank you for responding @devin-petersohn. pandas got installed with modin 0.9.1, so it is 1.2.3. Also, I can see this error on the local system also (Ubuntu 20.04 wsl) while running in a docker container.

**Comment by palash247** [comment] 2021-04-27 16:24
@devin-petersohn @anmyachev I can reproduce one of the exceptions related to the `int` type object. 
```
import modin.pandas as pd
import ray
ray.init()
import numpy as np
data = np.random.randint(0,100,(2**8,2**8))
df = pd.DataFrame(data)
df.to_csv('/tmp/test.csv')
```
**Resulting logs**:
```
2021-04-27 21:25:09,427	INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.
2021-04-27 21:25:14,874	ERROR worker.py:980 -- Possible unhandled error from worker: ray::deploy_ray_func() (pid=4823, ip=192.168.31.208)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "/home/pratik/miniconda3/lib/python3.8/site-packages/modin/engines/ray/pandas_on_ray/frame/axis_partition.py", line 114, in deploy_ray_func
    result = func(*args)
  File "/home/pratik/miniconda3/lib/python3.8/site-packages/modin/engines/base/frame/axis_partition.py", line 294, in deploy_axis_func
    if sum(lengths) != len(result.columns):
AttributeError: 'int' object has no attribute 'columns'
```
This is coming from `to_csv` implementation from https://github.com/modin-project/modin/blob/8fe4be960440e2bac952491685c9e86c64715b78/modin/engines/ray/generic/io.py#L131 
The returning object is int type but the following code expects it to be dataframe type https://github.com/modin-project/modin/blob/8fe4be960440e2bac952491685c9e86c64715b78/modin/engines/base/frame/axis_partition.py#L294 Not sure if it's really a problem though, as I can see the resulting csv file.

**Comment by anmyachev** [comment] 2021-04-27 16:33
@palash247 thanks! Nice research! I will look at this.

**Comment by wuisawesome** [comment] 2021-04-27 16:37
@palash247 , so to confirm, other than the fact that this exception is being printed, the program seems to be functioning correctly right?

**Comment by palash247** [comment] 2021-04-27 16:43
Yes @wuisawesome, the csv file is generated. And the `ray.__hash__` is `8744196536248`.

**Comment by wuisawesome** [comment] 2021-04-27 16:49
@palash247 whoops, sorry, I meant `ray.__commit__` 😅

**Comment by palash247** [comment] 2021-04-27 16:54
> @palash247 whoops, sorry, I meant `ray.__commit__` sweat_smile

NP It's `c8f8a8e51005cb3aab64a9e98f6e709b4976c03b`.

**Comment by wuisawesome** [comment] 2021-04-27 16:58
Ah it looks like you're on a very old nightly (we stabilized the nightly url to 2.0.0.dev0 in january I think). Can you do `pip install ray==1.3; ray install-nightly` then try again? 

Because the rest of the program seems to be functioning correctly, I suspect we're seeing https://github.com/ray-project/ray/issues/12018 which is a bug that only affects logging when an exception occurs.

**Comment by palash247** [comment] 2021-04-27 17:14
> Ah it looks like you're on a very old nightly (we stabilized the nightly url to 2.0.0.dev0 in january I think). Can you do `pip install ray==1.3; ray install-nightly` then try again?
> 
> Because the rest of the program seems to be functioning correctly, I suspect we're seeing [ray-project/ray#12018](https://github.com/ray-project/ray/issues/12018) which is a bug that only affects logging when an exception occurs.

I tried ray-nightly and the issue persists.

**Comment by anmyachev** [comment] 2021-04-27 17:15
@palash247 I was actually able to reproduce the problem.

The interesting thing is that with manual initialization, the problem is shown, but with automatic initialization of ray, it is not.

The quick fix - change return value from `0` to `pandas.DataFrame()`
https://github.com/modin-project/modin/blob/8fe4be960440e2bac952491685c9e86c64715b78/modin/engines/ray/generic/io.py#L131

**Comment by palash247** [comment] 2021-04-27 18:21
@anmyachev Thank you for the quick fix. I can now use `to_csv` method without any error. I also tested it with my original pandas code. The occurrence of `AttributeError: module 'pandas' has no attribute 'core'` is now reduced somehow. In fact my existing pandas code got executed once without any error. But this behavior is not consistent. I'll try to drill down more.

**Comment by devin-petersohn** [comment] 2021-04-27 18:52
@anmyachev Will you open a new issue to track the `to_csv` bug? Since it's a one line fix it should be quick to get in.

**Comment by devin-petersohn** [comment] 2021-04-27 18:58
@palash247 Could the issue be from all the workers not being alive at the start? After importing modin and before any dataframe operations can you run the following?

```python
import ray
import modin.pandas as pd

ray.init()  # with your args

def _import_pandas(*args):
    import pandas  # noqa F401

ray.worker.global_worker.run_function_on_all_workers(_import_pandas)

# everything else
```

We have had race conditions in the past with Ray and importing libraries, since libraries are imported in a separate thread in Ray. We added this in Modin when we initialize Ray ([here](https://github.com/modin-project/modin/blob/8fe4be960440e2bac952491685c9e86c64715b78/modin/engines/ray/utils.py#L184)) maybe we should always do this @wuisawesome?

**Comment by anmyachev** [comment] 2021-04-27 19:23
> @anmyachev Will you open a new issue to track the `to_csv` bug? Since it's a one line fix it should be quick to get in.
yes, #3025

**Comment by palash247** [comment] 2021-04-27 19:29
> @palash247 Could the issue be from all the workers not being alive at the start? After importing modin and before any dataframe operations can you run the following?
> 
> ```python
> import ray
> import modin.pandas as pd
> 
> ray.init()  # with your args
> 
> def _import_pandas(*args):
>     import pandas  # noqa F401
> 
> ray.worker.global_worker.run_function_on_all_workers(_import_pandas)
> 
> # everything else
> ```
> 
> We have had race conditions in the past with Ray and importing libraries, since libraries are imported in a separate thread in Ray. We added this in Modin when we initialize Ray ([here](https://github.com/modin-project/modin/blob/8fe4be960440e2bac952491685c9e86c64715b78/modin/engines/ray/utils.py#L184)) maybe we should always do this @wuisawesome?

This seems to work. I had 10 consecutive successful execution on the local machine. As my code is packaged, I added `ray.worker.global_worker.run_function_on_all_workers(_import_pandas)` in the `__init__.py`. Will try to execute this on Kubernetes and update the results. Thank you.

**Comment by wuisawesome** [comment] 2021-04-27 23:26
@devin-petersohn Is this a problem with function deserialization? or the import thread? (btw lemme know if you prefer to move this discussion into a ray issue).

**Comment by devin-petersohn** [comment] 2021-04-28 00:44
@wuisawesome This is a problem with the import thread. There was an issue in Ray for this: https://github.com/ray-project/ray/issues/7879

I think we should re-open it (or open a new one) because this is a hacky solution. Ideally we wouldn't need to do it.

**Comment by devin-petersohn** [comment] 2021-10-03 15:17
Closing as this is reported in Ray. We have a solution (though not one I am super happy about).

**Closed by devin-petersohn** 2021-10-03 15:17 UTC
Labels: bug :bug:
