### ISSUE TITLE
Series argument values are not properly serialized in `Series.isin` for Dask engine

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#4432] opened 2022-04-28 19:28 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version** (`modin.__version__`): 8adf28f62c09d49ebb677cf14ad54a3361329b22
- **Python version**: 3.8.10
- **Code we can use to reproduce**:
```python
import modin.config as cfg
cfg.Engine.put("Dask")

import modin.pandas as pd

if __name__ == "__main__":
    sr = pd.Series([1, 2, 3, 4])
    arg = pd.Series([1, 20])

    result = sr.isin(arg)
    print(result)
```

<details><summary>Output</summary>

```
RuntimeWarning: coroutine 'PooledRPCCall.__getattr__.<locals>.send_recv_from_rpc' was never awaited
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\core.py", line 111, in loads
    return msgpack.loads(
  File "msgpack\_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\core.py", line 103, in _decode_default
    return merge_and_deserialize(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\serialize.py", line 488, in merge_and_deserialize
    return deserialize(header, merged_frames, deserializers=deserializers)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\serialize.py", line 417, in deserialize
    return loads(header, frames)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\serialize.py", line 96, in pickle_loads
    return pickle.loads(x, buffers=new)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\pickle.py", line 75, in loads
    return pickle.loads(x)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\pandas\series.py", line 2497, in _inflate_light
    return cls(query_compiler=query_compiler, name=name)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\pandas\series.py", line 88, in __init__
    Engine.subscribe(_update_engine)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\config\pubsub.py", line 213, in subscribe
    callback(cls)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\pandas\__init__.py", line 138, in _update_engine
    initialize_dask()
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\core\execution\dask\common\utils.py", line 43, in initialize_dask
    num_cpus = len(client.ncores())
TypeError: object of type 'coroutine' has no len()
distributed.core - ERROR - Exception while reading from tcp://127.0.0.1:55382
Traceback (most recent call last):
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\core.py", line 451, in handle_comm
    msg = await comm.read()
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\comm\tcp.py", line 232, in read
    msg = await from_frames(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\comm\utils.py", line 78, in from_frames
    res = _from_frames()
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\comm\utils.py", line 61, in _from_frames
    return protocol.loads(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\core.py", line 111, in loads
    return msgpack.loads(
  File "msgpack\_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\core.py", line 103, in _decode_default
    return merge_and_deserialize(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\serialize.py", line 488, in merge_and_deserialize
    return deserialize(header, merged_frames, deserializers=deserializers)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\serialize.py", line 417, in deserialize
    return loads(header, frames)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\serialize.py", line 96, in pickle_loads
    return pickle.loads(x, buffers=new)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\protocol\pickle.py", line 75, in loads
    return pickle.loads(x)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\pandas\series.py", line 2497, in _inflate_light
    return cls(query_compiler=query_compiler, name=name)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\pandas\series.py", line 88, in __init__
    Engine.subscribe(_update_engine)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\config\pubsub.py", line 213, in subscribe
    callback(cls)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\pandas\__init__.py", line 138, in _update_engine
    initialize_dask()
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\core\execution\dask\common\utils.py", line 43, in initialize_dask
    num_cpus = len(client.ncores())
TypeError: object of type 'coroutine' has no len()
distributed.core - ERROR - Exception while handling op scatter
Traceback (most recent call last):
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\core.py", line 520, in handle_comm
    result = await result
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\scheduler.py", line 5839, in scatter
    keys, who_has, nbytes = await scatter_to_workers(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\utils_comm.py", line 145, in scatter_to_workers
    out = await All(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\utils.py", line 207, in All
    result = await tasks.next()
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\core.py", line 900, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\core.py", line 695, in send_recv
    raise Exception(response["exception_text"])
Exception: TypeError("object of type 'coroutine' has no len()")
Traceback (most recent call last):
  File "t2.py", line 10, in <module>
    result = sr.isin(arg)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\pandas\base.py", line 1716, in isin
    query_compiler=self._query_compiler.isin(values=values)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\core\dataframe\algebra\map.py", line 47, in caller
    query_compiler._modin_frame.map(
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\core\dataframe\pandas\dataframe\dataframe.py", line 114, in run_f_on_minimally_updated_metadata
    result = f(self, *args, **kwargs)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\core\dataframe\pandas\dataframe\dataframe.py", line 1536, in map
    new_partitions = self._partition_mgr_cls.map_partitions(self._partitions, func)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\core\dataframe\pandas\partitioning\partition_manager.py", line 487, in map_partitions
    preprocessed_map_func = cls.preprocess_func(map_func)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\core\dataframe\pandas\partitioning\partition_manager.py", line 114, in preprocess_func
    return cls._partition_class.preprocess_func(map_func)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\core\execution\dask\implementations\pandas_on_dask\partitioning\partition.py", line 240, in preprocess_func
    return DaskWrapper.put(func, hash=False, broadcast=True)
  File "C:\Users\rp-re\OneDrive\Desktop\rep\modin\modin\core\execution\dask\common\engine_wrapper.py", line 89, in put
    return client.scatter(data, **kwargs)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\client.py", line 2354, in scatter
    return self.sync(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\utils.py", line 309, in sync
    return sync(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\utils.py", line 363, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\utils.py", line 348, in f
    result[0] = yield future
  File "C:\Users\rp-re\miniconda3\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\client.py", line 2239, in _scatter
    await self.scheduler.scatter(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\core.py", line 900, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\core.py", line 693, in send_recv
    raise exc.with_traceback(tb)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\core.py", line 520, in handle_comm
m.py", line 145, in scatter_to_workers
    out = await All(
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\utils.py", line 207, in All
    result = await tasks.next()
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\core.py", line 900, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "C:\Users\rp-re\miniconda3\lib\site-packages\distributed\core.py", line 695, in send_recv
    raise Exception(response["exception_text"])
Exception: TypeError("object of type 'coroutine' has no len()")
```

</details>

### Describe the problem
Although the `values` argument for `.isin()` could be a Modin Series object, the argument is not preprocessed anyhow and passed as is to the query compiler:
https://github.com/modin-project/modin/blob/8adf28f62c09d49ebb677cf14ad54a3361329b22/modin/pandas/base.py#L1711-L1717
`PandasQueryCompiler.isin` method is just a template `MapFunction` that does not process arguments as well
https://github.com/modin-project/modin/blob/8adf28f62c09d49ebb677cf14ad54a3361329b22/modin/core/storage_formats/pandas/query_compiler.py#L1349
It all ends up with serializing `modin.pandas.Series` object and passing it to workers, that are then failing to deserialize it as it requires nested initialization of the engine inside a worker: [`modin.pandas.Series.__init__` -> `Engine.subscribe(_update_engine)`](https://github.com/modin-project/modin/blob/8adf28f62c09d49ebb677cf14ad54a3361329b22/modin/pandas/series.py#L88); [`_update_engine` -> `initialize_dask`](https://github.com/modin-project/modin/blob/8adf28f62c09d49ebb677cf14ad54a3361329b22/modin/pandas/__init__.py#L135-L138) (note that [`_is_first_update` dictionary](https://github.com/modin-project/modin/blob/8adf28f62c09d49ebb677cf14ad54a3361329b22/modin/pandas/__init__.py#L96) is not shared across dask workers, so it's not protect us from nested initializations)

P.S. the reproducer works fine for Ray engine

### Expected behavior
We probably should perform a special casing for `modin.pandas.Series` objects as a `values` arguments in the front-end by extracting a query compiler and then broadcasting it to the `self` partitions in a lower end. Casting `values` to pandas would also work fine as a hotfix.

**Comment by anmyachev** [comment] 2022-04-29 11:53
@dchigarev it turns out that this error is present for all operations defined using `Map.register` and whose operand can be Modin objects?

Should we try to equalize the behavior of Ray and Dask in such cases by rewriting Dask's initialization function to work with coroutines as well?

**Comment by anmyachev** [comment] 2022-04-29 11:58
Link to previous thought about the problem: https://github.com/modin-project/modin/issues/2498#issuecomment-745808956

**Comment by vnlitvinov** [comment] 2022-09-06 15:53
I wonder if https://github.com/modin-project/modin/pull/4600 accidentally fixes this?

**Comment by anmyachev** [comment] 2023-04-04 15:23
The error is not reproduced on the master, looks like it was fixed by converting the arguments to pandas.

**Closed by anmyachev** 2023-04-04 15:23 UTC
Labels: bug 🦗, pandas concordance 🐼, P1
