### ISSUE TITLE
Modin import [OS Error]

### ISSUE THREAD

**Issue by smrazaabbas** [modin-project/modin#235] opened 2018-10-30 13:25 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Modin installed from (source or binary)**: pip source
- **Modin version**:  0.2.2
- **Python version**: 2.7.12
- **Exact command to reproduce**: import modin.pandas as pd

### Describe the problem
I have installed modin via 
pip install modin

### Source code / logs
import modin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python2.7/site-packages/modin/__init__.py", line 58, in <module>
    __git_revision__ = _git_version()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/modin/__init__.py", line 26, in _git_version
    stdout=open(os.devnull, "w"),
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by devin-petersohn** [comment] 2018-10-30 15:26
Hi @smrazaabbas, thanks for posting this!

I am not able to reproduce this locally on Ubuntu. Sometimes these kinds of errors can happen when the environment runs into an issue.

Does `os.path.exists(os.devnull)` return `True` for you?

**Comment by Trollgeir** [comment] 2018-10-31 10:18
Same error on ubuntu 16.06 python 3.6
```
import modin.pandas as pd
  File "/usr/local/lib/python3.6/site-packages/modin/__init__.py", line 58, in <module>
    __git_revision__ = _git_version()
  File "/usr/local/lib/python3.6/site-packages/modin/__init__.py", line 26, in _git_version
    stdout=open(os.devnull, "w"),
  File "/usr/local/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
```

I take it's something related to git?

**Comment by devin-petersohn** [comment] 2018-10-31 14:19
@Trollgeir thanks! It is likely something related to git, so I think the best way to continue is to just drop the git revision from our `__init__`, since that is what is causing the problem. We don't really use it in our development process anyway.

Once we get that change merged (later today), you can pip install from the GitHub repo (instructions [here](https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch) using pip and we can see if you still have the issue.

**Comment by devin-petersohn** [comment] 2018-10-31 15:45
Ok, the git dependency should be removed now, from #238. If you could, try to install from the GitHub repo:
```
pip install git+https://github.com/modin-project/modin
```

**Comment by Trollgeir** [comment] 2018-10-31 16:49
If I install it directly from github then my docker image will have git as a dependency, which seems to be the problem we're trying to avoid?

**Comment by devin-petersohn** [comment] 2018-10-31 19:11
Here is a way you should be able to run Modin locally without using `git`.

```bash
wget https://github.com/modin-project/modin/archive/master.zip
unzip master.zip
(cd modin-master && pip install -e .)
```

That will download the repo without using git and install with `pip`, so there shouldn't be any other `git` dependencies.

**Comment by Trollgeir** [comment] 2018-10-31 19:36
```
Start streaming logs:
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:14105 to respond...
Waiting for redis server at 127.0.0.1:53758 to respond...
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from clv_func import clv_job
  File "/app/clv_func.py", line 7, in <module>
    import modin.pandas as pd
  File "/app/modin-master/modin/pandas/__init__.py", line 80, in <module>
    use_raylet=True,
  File "/usr/local/lib/python3.6/site-packages/ray/worker.py", line 1866, in init
    use_raylet=use_raylet)
  File "/usr/local/lib/python3.6/site-packages/ray/worker.py", line 1661, in _init
    use_raylet=use_raylet)
  File "/usr/local/lib/python3.6/site-packages/ray/services.py", line 1802, in start_ray_head
    use_raylet=use_raylet)
  File "/usr/local/lib/python3.6/site-packages/ray/services.py", line 1524, in start_ray_processes
    use_raylet=use_raylet)
  File "/usr/local/lib/python3.6/site-packages/ray/services.py", line 1124, in start_plasma_store
    system_memory = ray.utils.get_system_memory()
  File "/usr/local/lib/python3.6/site-packages/ray/utils.py", line 326, in get_system_memory
    return vmstat("total memory") * bytes_in_kilobyte
  File "/usr/local/lib/python3.6/site-packages/ray/utils.py", line 281, in vmstat
    out = subprocess.check_output(["vmstat", "-s"])
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vmstat': 'vmstat'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ray/worker.py", line 1914, in shutdown
    assert (len(processes) == 0)
AssertionError
```

Seems like there's more issues with dependencies?

**Comment by devin-petersohn** [comment] 2018-10-31 20:32
It is possibly an issue with Docker dependencies related to Ray's dependencies, cc @robertnishihara.

**Comment by robertnishihara** [comment] 2018-10-31 20:43
You can get around this by doing *pip install psutil*. Or if that doesn’t work maybe conda instead of pip.

**Comment by Trollgeir** [comment] 2018-10-31 21:18
I installed psutil after getting the gcc compiler and managed to get a step fruther.

```
Start streaming logs:
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:17586 to respond...
Waiting for redis server at 127.0.0.1:23840 to respond...
Warning: Reducing object store memory because /dev/shm has only 67108864 bytes available. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
Starting the Plasma object store with 0.00 GB memory.
/app/modin-master/modin/pandas/io.py:318: UserWarning: Reading from buffer. Defaulting to Pandas implementation.
  "Reading from buffer. Defaulting to Pandas implementation.", UserWarning
The task with ID 00000000f7421e52effeda4bae8de524cc06cc54 is a driver task and so the object created by ray.put could not be reconstructed.
The task with ID 00000000f7421e52effeda4bae8de524cc06cc54 is a driver task and so the object created by ray.put could not be reconstructed.
The task with ID 00000000f7421e52effeda4bae8de524cc06cc54 is a driver task and so the object created by ray.put could not be reconstructed.
The task with ID 00000000f7421e52effeda4bae8de524cc06cc54 is a driver task and so the object created 
... (forever)
```

Bear in mind my example is also trying to read from a buffer object which defaults to normal pandas (will this ever be a feature?)

The warnings about the docker image seems clear at least as I have yet to try with the mentioned flags.

**Comment by robertnishihara** [comment] 2018-10-31 21:28
Looks like the relevant error is

*Warning: Reducing object store memory because /dev/shm has only 67108864 bytes available. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.*

so objects are getting evicted too quickly and Ray is attempting to reconstruct them.

**Comment by smrazaabbas** [comment] 2018-11-07 12:39
@devin-petersohn  Thanks devin. I was able to check just now, seems to be an environment issue. 
I checked the same on Redhat linux. Its working. 
Thanks.

**Comment by devin-petersohn** [comment] 2020-06-01 14:40
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.

**Closed by devin-petersohn** 2020-06-01 14:40 UTC
