### ISSUE TITLE
modin with dask is much slower than pandas 

### ISSUE THREAD

**Issue by RexHuang** [modin-project/modin#4369] opened 2022-04-06 03:35 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.14.0
- **Python version**: 3.8.12
- **Exact command to reproduce**:
%time df = pd.concat([pd.DataFrame(np.random.randint(0, 100, size=(2\*\*20, 2**5))) for _ in range(40)]) 

### Describe the problem

see the logs, use pandas Wall time is 16.4 s, when use modin with dask Wall time is 18min, 
modin is much slow than pandas.

### Source code / logs

> 

---------------------
import pandas as pd
import numpy as np
%time df = pd.concat([pd.DataFrame(np.random.randint(0, 100, size=(2\*\*20, 2**5))) for _ in range(40)]) 
Wall time: 16.4 s
---------------------
import modin.pandas as pd
import numpy as np
%time df = pd.concat([pd.DataFrame(np.random.randint(0, 100, size=(2\*\*20, 2**5))) for _ in range(40)])
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.
CPU times: user 58 s, sys: 12.9 s, total: 1min 10s
Wall time: 18min

**Comment by mvashishtha** [comment] 2022-04-06 17:41
@RexHuang thank you for filing this issue. I was unable to reproduce it with the following:

On my mac (specs below), I ran the following with Modin on dask and python:

```python
import modin.pandas as pd
import numpy as np

# Initialize a dataframe so Modin can initialize Dask before the benchmarks.
pd.DataFrame()

%time frames = [pd.DataFrame(np.random.randint(0, 100, size=(2**20, 2**5))) for _ in range(40)]
%time df = pd.concat(frames)
```

Modin takes 82 seconds to make the frames and 13.4 seconds to concat, for a total of 95.4 seconds. pandas takes 16.4 seconds to make the frames and 26.7 seconds to concat, for a total of 43.1 seconds. Modin is slower, but the performance difference is not as great as the one you reported, and the slowness is mostly in constructing the Modin frames, as the `UserWarning` you mentioned explains. The ratio of total Modin time to total pandas time is 2.21, much less than the factor of 1080/16.4 = 65 that you reported.

**Could you please give the specs, including the number of cores, the amount of RAM, the processor, and the operating system version, for your ubuntu machine?** I can try to use those to reproduce the issue.

 ### System information
- Modin version 0.14.0+2.gf41432c1
- Python version 3.9.12
- macOS Monterey 12.2.1 on MacBookPro (16-inch, 2019)
- 16 GB RAM
- Processor: 2.3 GHz 8-core intel core i9

**Comment by RexHuang** [comment] 2022-04-07 01:46
@mvashishtha Thanks for your response. 
I am using dask in K8s (with three nodes, 8threads cpu, 16GB memory limits per node)

**Comment by devin-petersohn** [comment] 2022-04-07 15:43
Thanks @RexHuang for posting! It looks like you're trying to run some simple benchmarks, happy to help here!

If you want to benchmark Modin, I recommend using a file (CSV, parquet, etc.). This more accurately reflects how people use pandas normally.

In your K8s cluster, did you start a Dask cluster? Modin will require you to stand up a Dask cluster first if you want to use all of the nodes. The instructions in the documentation are around setting up a Ray cluster (https://modin.readthedocs.io/en/stable/getting_started/using_modin/using_modin_cluster.html). Dask should be similar, but we could definitely use some better documentation for a Dask cluster.

If you do not start and connect a Dask (or Ray) client, Modin will start a local client for you. This enables Modin to work out of the box, but will take time. This is done the first time you use `pd.DataFrame` or `pd.read_csv` or any other reader.

**Comment by mvashishtha** [comment] 2022-09-20 14:50
@RexHuang the Modin maintainers would like to help answer your question, but it's hard to help without the answers to @devin-petersohn 's questions. I'm closing this issue for now because it's been over 5 months since @devin-petersohn 
 asked his questions. Please comment here if you'd like more help.

**Closed by mvashishtha** 2022-09-20 14:50 UTC
Labels: Performance 🚀, Dask ⚡
