### ISSUE TITLE
AssertionError: MultiIndex level [0] are different

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#3380] opened 2021-08-27 16:02 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.10.2
- **Python version**: 3.8.11
- **Code we can use to reproduce**:

```shell
set MODIN_EXPERIMENTAL=1
python -m pytest modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level1,multiindex_level0-int_data]
```

### Describe the problem

Occurs in 72 tests.

- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_True-over_rows_int-multiindex_level1,multiindex_level0-int_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_True-over_rows_str-multiindex_level1,multiindex_level0-int_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_None-over_rows_int-multiindex_level1,multiindex_level0-int_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_None-over_rows_str-multiindex_level1,multiindex_level0-int_data]
- modin/pandas/test/dataframe/test_join_sort.py::test_sort_values[None-ignore_index_False-first-quicksort-inplace_True-ascending_list_first_True-over_rows_int-multiindex_level1,multiindex_level0-int_data]

And also in 67 tests.

This error is also found in other variants. But they have the same reason.

### Source code / logs

<details>
<summary>Traceback</summary>

```shell
modin\pandas\test\utils.py:725: in eval_general
    comparator(*values)
modin\pandas\test\utils.py:543: in df_equals
    assert_frame_equal(
pandas\_libs\testing.pyx:53: in pandas._libs.testing.assert_almost_equal
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   AssertionError: MultiIndex level [0] are different
E   
E   MultiIndex level [0] values are different (53.90625 %)
E   [left]:  Index(['first', 'first', 'second', 'first', 'first', 'second', 'first',
E          'second', 'second', 'second',
E          ...
E          'first', 'first', 'second', 'second', 'second', 'first', 'first',
E          'second', 'second', 'second'],
E         dtype='object', name='level-0', length=256)
E   [right]: Index(['first', 'first', 'first', 'first', 'first', 'first', 'first', 'first',
E          'first', 'second',
E          ...
E          'first', 'first', 'first', 'first', 'first', 'first', 'first', 'first',
E          'first', 'first'],
E         dtype='object', name='level-0', length=256)
```

</details>

**Comment by mvashishtha** [comment] 2022-06-08 23:38
@Lozovskii-Aleksandr the test cases such as the one you showed should `xfail` because of [these lines](https://github.com/modin-project/modin/blob/5de7f18f73910a0909853e7b22f2504ef2011f8f/modin/pandas/test/dataframe/test_join_sort.py#L406-L425). For some reason setting `MODIN_EXPERIMENTAL=True` causes the `xfail` to get skipped. I can reproduce the error on my mac. I have filed #4558 for the known bug with sorting by multiindex.

**Comment by RehanSD** [comment] 2022-10-12 03:19
Hi @mvashishtha @Lozovskii-Aleksandr has this issue been resolved?

**Comment by mvashishtha** [comment] 2022-10-12 03:33
@RehanSD as of version 88f7b27d32b099c508e93251cafe503f2908d426, all of `test_join_sort` passes when `MODIN_EXPERIMENTAL=1`, so I think we can close this.

**Closed by mvashishtha** 2022-10-12 03:33 UTC
Labels: bug 🦗, P3
