### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 5: invalid continuation byte (On Python 3)

### ISSUE THREAD

**Issue by Havikz2** [modin-project/modin#3217] opened 2021-07-05 15:18 UTC
Hi Everyone, 
I am trying to import a csv file using Python and getting the following error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 5: invalid continuation byte

            During handling of the above exception, another exception occurred:
            
            UnicodeDecodeError Traceback (most recent call last)
            <ipython-input-2-975331fc3025> in <module>
                  1 # Read in the data
            ----> 2 df = pd.read_csv('movies.csv')

This is my code:

        # Import libraries
        
        import pandas as pd
        
        import seaborn as sns
        import matplotlib
        import matplotlib.pyplot as plt
        plt.style.use('ggplot')
        from matplotlib.pyplot import figure
        %matplotlib inline
        matplotlib.rcParams['figure.figsize'] = (12,8) # Adjust the configuration of the plots we will create
        
        df = pd.read_csv('movies.csv')

I have attached the csv file
[movies.zip](https://github.com/modin-project/modin/files/6765178/movies.zip)

Nali

**Comment by devin-petersohn** [comment] 2021-08-23 14:46
Thanks for the report @Havikz2, I can reproduce the issue you ran into.

I also tested this in pandas and pandas throws the same error. Since we try to maintain the same errors as pandas I would not classify this as a bug in Modin. If you think it is a bug in pandas, please link back to this issue so we can also track that. Thanks again for raising the issue!

Closing as this may be a bug in an upstream library.

**Closed by devin-petersohn** 2021-08-23 14:46 UTC
