### ISSUE TITLE
PERF: pass lengths to build_partition in read_parquet

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4785] opened 2022-08-05 17:17 UTC
In ParquetDispatcher.build_partition we pass int col_width to the Partition constructor but an ObjectRef for the length.  IIUC we should be able to infer the lengths at init-time, right?

**Comment by mvashishtha** [comment] 2022-08-05 18:00
I'm going to mark this as a duplicate of #4743. I think we don't necessarily know the lengths. We don't always materialize the indexes in the main node:

https://github.com/modin-project/modin/blob/4548012a6372b8ce79d7e07c9ae13fd7444a91c8/modin/core/io/column_stores/parquet_dispatcher.py#L310-L313

And AFAIK we don't block on reading the individual block partitions for any other reason.

**Comment by mvashishtha** [comment] 2022-08-05 18:00
Duplicate of #4743

**Closed by mvashishtha** 2022-08-05 18:00 UTC
Labels: Triage 🩹
