### ISSUE TITLE
Numerous regressions in Pandas 0.24.1

### ISSUE THREAD

**Issue by Shellcat-Zero** [modin-project/modin#518] opened 2019-03-28 22:55 UTC
Please see http://pandas.pydata.org/pandas-docs/version/0.24/whatsnew/v0.24.2.html

Due to numerous regressions in Pandas versions 0.24.0 and 0.24.1, the only viable version of Modin for me currently is 0.3.1 to avoid these issues.

**Comment by devin-petersohn** [comment] 2019-03-28 23:23
Hi @Shellcat-Zero, which regressions are specifically troublesome for your workflows?

#509 updates the pandas version to 0.24.2. It will be merged soon.

**Comment by Shellcat-Zero** [comment] 2019-03-29 00:43
@devin-petersohn the regressions I've encountered specific to 0.24.1 are [GH25196](https://github.com/pandas-dev/pandas/issues/25196), and [GH25338](https://github.com/pandas-dev/pandas/issues/25338).

**Comment by devin-petersohn** [comment] 2019-04-01 23:57
Thanks @Shellcat-Zero! Would you mind to provide a small self-contained piece of code we can add to the tests to make sure that these functionalities will always work in Modin?

In the past, we have had to regress our own functionality purposely (and temporarily) until a release of pandas has the fix for that issue. This way, we will be able to detect the regression.

**Comment by devin-petersohn** [comment] 2019-04-04 05:32
Hi @Shellcat-Zero, since #509 is merged, I am going to close this. Feel free to reopen if you still have compatibility issues.

**Closed by devin-petersohn** 2019-04-04 05:32 UTC
Labels: dependencies :link:
