### ISSUE TITLE
Func `unwrap_partitions` doesn't work for 'python' engine

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#2938] opened 2021-03-29 14:41 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Modin version** (`modin.__version__`): 0.9.1+01ba1f40c032e92f16dd6f276e238baf5473bda7
- **Python version**: 3.8.5
- **Code we can use to reproduce**:
```python
import os
os.environ["MODIN_ENGINE"] = "python"
import modin.pandas as pd
from modin.distributed.dataframe.pandas import unwrap_partitions

df = pd.DataFrame([0])
parts = unwrap_partitions(df, axis=0, get_ip=True)
print(parts)
```

### Describe the problem

Possible, support of unwrapping partitions is implemented for Ray/Dask engines only.

**Comment by prutskov** [comment] 2021-03-29 14:42
@YarShev please, take a look

**Comment by YarShev** [comment] 2021-03-29 16:33
@prutskov , that is not a bug. The feature is mainly intended for cluster users to help them minimize data movement by using partition IPs. That doesn't make sense for python engine. Reclassifying the issue as a question.

**Comment by prutskov** [comment] 2021-03-29 18:06
@YarShev, In this case need to show user-friendly exception, instead of:
```
parts = unwrap_partitions(df, axis=0, get_ip=True)
  File "/localdisk/aprutsko/modin/modin/distributed/dataframe/pandas/partitions.py", line 84, in unwrap_partitions
    return [
  File "/localdisk/aprutsko/modin/modin/distributed/dataframe/pandas/partitions.py", line 85, in <listcomp>
    part.force_materialization(get_ip=get_ip).unwrap(
  File "/localdisk/aprutsko/modin/modin/engines/base/frame/axis_partition.py", line 115, in force_materialization
    return type(self)(materialized, get_ip=get_ip)
TypeError: __init__() got an unexpected keyword argument 'get_ip'
```
The user will be confused by this error.

**Comment by YarShev** [comment] 2021-03-29 18:15
@prutskov , yes, sure. We throw the exception but it is for `axis is None` only, unfortunately. We need to add the exception for `axis=0` and `axis=1` as well. I will open a conforming issue for that. If you do not have something else, feel free to close the issue.

**Comment by YarShev** [comment] 2021-04-05 10:53
Adding the feature regarding getting partition and conforming node IP address for python engine will require additional efforts and significant refactoring of the code. I do not see that is necessary. We could support getting python partition without node IP address for debug purposes if we really want it.

**Comment by YarShev** [comment] 2022-10-13 06:50
I don't think we plan to fix something here. You can close the issue.

**Closed** 2022-10-13 15:03 UTC
Labels: question ❓, Needs more information ❔, P3
