### ISSUE TITLE
OmniSci engine failed when using loc on dataframes with multiindex

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3076] opened 2021-05-20 18:24 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): e4fa1409d6ee048dcdcafc092a10bdc90d965303
- **Python version**: 3.7.10
- **Code we can use to reproduce**:

```python
import numpy as np
from modin.pandas import DataFrame
import modin.pandas as pd

df1 = DataFrame(np.random.randint(10**6, size=(10_000, 10)), columns=[f"col{x}" for x in range(10)])

index = pd.MultiIndex.from_product([df1.index[: df1.shape[0] // 2], ["bar", "foo"]])
columns = pd.MultiIndex.from_product(
    [df1.columns[: df1.shape[1] // 2], ["buz", "fuz"]]
)

df1.index = index
df1.columns = columns

df1 = df1.sort_index(axis=1)

print(df1.loc[df1.index[2] : df1.index[-2], df1.columns[2] : df1.columns[-2]])
```

### Source code / logs

```python
Traceback (most recent call last):
  File "benchmarks/test.py", line 18, in <module>
    print(df1.loc[df1.index[2] : df1.index[-2], df1.columns[2] : df1.columns[-2]])
  File "modin/pandas/indexing.py", line 539, in __getitem__
    if hasattr(result, "index") and isinstance(result.index, pandas.MultiIndex):
  File "modin/pandas/base.py", line 2824, in __getattribute__
    attr = super().__getattribute__(item)
  File "modin/pandas/base.py", line 507, in _get_index
    return self._query_compiler.index
  File "modin/experimental/backends/omnisci/query_compiler.py", line 334, in _get_index
    return self._modin_frame.index
  File "modin/experimental/engines/omnisci_on_ray/frame/data.py", line 1170, in _get_index
    self._execute()
  File "modin/experimental/engines/omnisci_on_ray/frame/data.py", line 1030, in _execute
    self._run_sub_queries()
  File "modin/experimental/engines/omnisci_on_ray/frame/data.py", line 1059, in _run_sub_queries
    op._execute()
  File "modin/experimental/engines/omnisci_on_ray/frame/data.py", line 1033, in _execute
    new_table = self._execute_arrow()
  File "modin/experimental/engines/omnisci_on_ray/frame/data.py", line 1088, in _execute_arrow
    return self._op.input[0]._arrow_col_slice(set(self._op.exprs.keys()))
  File "modin/experimental/engines/omnisci_on_ray/frame/data.py", line 1097, in _arrow_col_slice
    [f"F_{col}" for col in self._table_cols if col not in new_columns]
  File "pyarrow/table.pxi", line 1932, in pyarrow.lib.Table.drop
KeyError: 'Column "F_(\'col0\', \'buz\')" not found'
```

**Comment by RehanSD** [comment] 2022-10-12 02:14
Duplicate of #4905

**Comment by RehanSD** [comment] 2022-10-12 02:14
Duplicate of #4904

**Closed by RehanSD** 2022-10-12 02:14 UTC
Labels: bug 🦗, OmniSci
