### ISSUE TITLE
ERROR: No matching distribution found for pandas==0.25.3 (from modin[all])

### ISSUE THREAD

**Issue by katzuv** [modin-project/modin#883] opened 2019-11-27 07:14 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Modin installed from (source or binary)**: pip
- **Modin version**: trying to install latest
- **Python version**: 2.7.15+
- **Exact command to reproduce**: `python -m pip install modin[all]`

### Describe the problem

After installing pandas with `python -m pip install pandas` I am trying to install Modin with `python -m pip install modin[all]` and getting this error:
```text
ERROR: No matching distribution found for pandas==0.25.3 (from modin[all])
```
I tried uninstalling and reinstalling pandas version `0.24.2` with these commands:
```text
python -m pip uninstall pandas
python -m pip install --no-cache-dir pandas
```
After trying to reinstall Modin with the same command above, I am still getting the same error.
What should I do to solve this problem?
Thank you!

### Source code / logs

Log after installation of pandas version `0.24.2`:
```text
python -m pip install --no-cache-dir  pandas==0.24.2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pandas==0.24.2
  Downloading https://files.pythonhosted.org/packages/db/83/7d4008ffc2988066ff37f6a0bb6d7b60822367dcb36ba5e39aa7801fda54/pandas-0.24.2-cp27-cp27mu-manylinux1_x86_64.whl (10.1MB)
     |████████████████████████████████| 10.1MB 527kB/s 
Requirement already satisfied: numpy>=1.12.0 in /home/user/Downloads/Analysis-and-Utils/venv/lib/python2.7/site-packages (from pandas==0.24.2) (1.16.5)
Requirement already satisfied: pytz>=2011k in /home/user/Downloads/Analysis-and-Utils/venv/lib/python2.7/site-packages (from pandas==0.24.2) (2019.3)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/user/Downloads/Analysis-and-Utils/venv/lib/python2.7/site-packages (from pandas==0.24.2) (2.8.1)
Requirement already satisfied: six>=1.5 in /home/user/Downloads/Analysis-and-Utils/venv/lib/python2.7/site-packages (from python-dateutil>=2.5.0->pandas==0.24.2) (1.12.0)
Installing collected packages: pandas
Successfully installed pandas-0.24.2
```
Log after trying to install Modin:
```text
python -m pip install --no-cache-dir modin[all]
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting modin[all]
  Downloading https://files.pythonhosted.org/packages/a5/32/8a1456504d88dffbfe782dc5a8c5d44cb9b2b462e6d02cadd2b1f49e11a2/modin-0.6.3.tar.gz (189kB)
     |████████████████████████████████| 194kB 519kB/s 
ERROR: Could not find a version that satisfies the requirement pandas==0.25.3 (from modin[all]) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
ERROR: No matching distribution found for pandas==0.25.3 (from modin[all])
```
Thanks again!

**Comment by devin-petersohn** [comment] 2019-11-29 20:08
Hi @katzuv, thanks for posting!

This is a duplicate of #880. Since pandas has deprecated Python 2, we also have done so and therefore we no longer support Python 2.

I highly recommend updating your Python version to 3 as it will be at end of life within a little more than a month.

Closing as duplicate. If you want to continue the conversation please discuss on the open issue #880.

**Closed by devin-petersohn** 2019-11-29 20:08 UTC
Labels: duplicate :recycle:
