### ISSUE TITLE
Can the library of multiprocessing and modin be used simultaneously?

### ISSUE THREAD

**Issue by king21guns** [modin-project/modin#550] opened 2019-04-14 15:15 UTC
### Describe the problem
My code has bug when i use modin. I wonder Can the library of multiprocessing and modin be used simultaneously？

### Source code / logs
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-04-14_23-15-00_7571/logs.
Waiting for redis server at 127.0.0.1:36216 to respond...
Waiting for redis server at 127.0.0.1:19632 to respond...
Starting Redis shard with 10.0 GB max memory.
Starting the Plasma object store with 5.0 GB memory using /tmp.

  File "/Users/apple/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 4736, in __getattr__
    if key in self.columns:
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 185, in _get_columns
    return self._query_compiler.columns
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 4736, in __getattr__
    if key in self.columns:
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 185, in _get_columns
    return self._query_compiler.columns
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 4736, in __getattr__
    if key in self.columns:
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 185, in _get_columns
    return self._query_compiler.columns
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 4736, in __getattr__
    if key in self.columns:
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 185, in _get_columns
    return self._query_compiler.columns
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/modin/pandas/dataframe.py", line 4734, in __getattr__
    return object.__getattribute__(self, key)
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by devin-petersohn** [comment] 2019-04-14 16:13
Hi @king21guns, thanks for posting!

What was the line of code that triggered the error? What version of Modin are you using? I am not able to reproduce the error locally with the information here.

To your question:
>I wonder Can the library of multiprocessing and modin be used simultaneously?

I don't think it will work very well right now because currently, Modin DataFrames can't be pickled. Modin itself is using Ray to do the multiprocessing under the hood, so depending on your workflow, multiprocessing a Modin DataFrame might be slower than using Modin natively. I realize some workflows depend on Multiprocessing for things other than performance, so in the future we do plan to allow Modin DataFrames to be pickled.

**Comment by king21guns** [comment] 2019-04-15 06:18
> Hi @king21guns, thanks for posting!
> 
> What was the line of code that triggered the error? What version of Modin are you using? I am not able to reproduce the error locally with the information here.
> 
> To your question:
> 
> > I wonder Can the library of multiprocessing and modin be used simultaneously?
> 
> I don't think it will work very well right now because currently, Modin DataFrames can't be pickled. Modin itself is using Ray to do the multiprocessing under the hood, so depending on your workflow, multiprocessing a Modin DataFrame might be slower than using Modin natively. I realize some workflows depend on Multiprocessing for things other than performance, so in the future we do plan to allow Modin DataFrames to be pickled.

Thanks for your reply!

**Comment by chaxor** [comment] 2019-05-13 23:09
Is there a way to check if a certain set of tasks that going to be used on a data frame are within modin's repertoire?  Therefore this would allow a pandas dataframe to be converted to modin if it is possible to utilize modin for certain tasks, but then transfer the data to a pandas dataframe with mulitprocessing to finish the computation.

**Comment by devin-petersohn** [comment] 2019-05-13 23:17
That's an interesting question @chaxor, there's no programmatic way to do it right now.

We do have a documentation page that lists these: https://modin.readthedocs.io/en/latest/pandas_supported.html

What kinds of tasks are you wanting to do in multiprocessing? In the question above, I assumed it would be for use with another library, but if you're hand-rolling some multiprocessing code, it may be useful to put that code into Modin for everyone to use.

**Comment by devin-petersohn** [comment] 2020-06-01 14:57
Duplicate of #672

**Closed by devin-petersohn** 2020-06-01 14:57 UTC
Labels: question :question:
