### ISSUE TITLE
UserWarning: merge defaulting to pandas implementation. Can we compare two dataframes with millions records?

### ISSUE THREAD

**Issue by ggservice007** [modin-project/modin#2652] opened 2021-01-27 12:34 UTC
I write the following records.

```python
...

lst_json_a = []
lst_json_a.append({
    'name': 'gg008',
    'age': 36
})

lst_json_a.append({
    'name': 'gg009',
    'age': 37
})


lst_json_b = []
lst_json_b.append({
    'name': 'gg008',
    'age': 36
})

lst_json_b.append({
    'name': 'gg010',
    'age': 41
})


df_a = pd.DataFrame.from_records(lst_json_a)

df_b = pd.DataFrame.from_records(lst_json_b)

df_comparison = df_a.merge(df_b, indicator=True, how='outer')

df_comparison
```

After run, it has the following warnings.

![Snip20210127_1](https://user-images.githubusercontent.com/9192908/105991644-0868ee00-60df-11eb-9d20-a48bfd76499e.png)

How many records we can compare two DataFrame at most?

**Comment by ggservice007** [comment] 2021-01-27 12:40
Several ten thousand is very OK.

```python
file_path_a = Path('data/eventlog.csv').resolve()

df_a = pd.read_csv(file_path_a, sep=';', header=None)


file_path_b = Path('data/eventlog_large.csv').resolve()

df_b = pd.read_csv(file_path_b, sep=';', header=None)


df_comparison = df_a.merge(df_b, indicator=True, how='outer')

df_comparison
```

![Snip20210127_4](https://user-images.githubusercontent.com/9192908/105992324-ef147180-60df-11eb-878a-9d4afb1c68d9.png)

**Comment by YarShev** [comment] 2021-01-28 09:53
Hi @ggservice007 , thanks for posting this!
Are you interested in distributed implementation of `merge` with `how=outer`?

**Comment by ggservice007** [comment] 2021-01-28 13:20
After vaex issue 955 issue is solved, we can refer to their code.

https://github.com/vaexio/vaex/issues/955

I will be try it.

**Comment by devin-petersohn** [comment] 2021-01-28 13:46
@ggservice007 Merge is different from `diff` in the issue you linked. Can you clarify what you are looking for?

**Comment by ggservice007** [comment] 2021-01-29 01:28
Make the "merge with how=outer" functionality of pandas to  distribute or parallel like other functions provided by modin.

**Comment by YarShev** [comment] 2021-02-02 10:35
@ggservice007 , there is already a list of similar issues (#2472, [#1003](https://github.com/modin-project/modin/issues/1003), #656). We have higher priority issues for the release but we are trying to take into account `merge` as soon as possible.

**Comment by ggservice007** [comment] 2021-02-03 09:42
@YarShev  nice

**Comment by YarShev** [comment] 2022-03-04 14:36
Closing as a duplicate of #2472, #1003, #656.

**Closed by YarShev** 2022-03-04 14:36 UTC
Labels: new feature/request 💬
