### ISSUE TITLE
How to make use of out of core memory

### ISSUE THREAD

**Issue by codecypher** [modin-project/modin#4094] opened 2022-01-27 20:33 UTC
I am using the following software version on Ubuntu 20.04.3 LTS:

```
  conda                 4.11.0
  modin-core                0.12.1
  modin-ray                 0.12.1
  ray                       1.9.2
```

I have seen some examples that mention use of `MODIN_OUT_OF_CORE` environment variable when size of the dataset exceeds the amount of memory on the system. I need to run `pivot()` on a pandas `DataFrame` and then I get the following error messages.

```
(pid=187900) UserWarning: Found unknown environment variable, please check its spelling: MODIN_OUT_OF_CORE
(pid=187902) UserWarning: Found unknown environment variable, please check its spelling: MODIN_OUT_OF_CORE
(pid=187903) UserWarning: Found unknown environment variable, please check its spelling: MODIN_OUT_OF_CORE
(pid=187904) UserWarning: Found unknown environment variable, please check its spelling: MODIN_OUT_OF_CORE

# …

numpy.core._exceptions._ArrayMemoryError: Unable to allocate 165. GiB for an array with shape (241090, 92107) and data type float64
```

Any help or code examples on how to make use of out of core memory with Ray on a local PC or laptop running Linux would be appreciated.

Below is the relevant python code:

```py
def ray_init():    
    os.environ["MODIN_CPUS"] = "4"
    os.environ["MODIN_ENGINE"] = "ray"
    os.environ["MODIN_MEMORY"]= "20000000000"  # 20*10^9 = 20GB
    os.environ["MODIN_NPARTITIONS"] = "2"
    os.environ["MODIN_OUT_OF_CORE"]= "true"
    os.environ["MODIN_PROGRESS_BAR"] = "true"
    os.environ["MODIN_STORAGE_FORMAT"] = "Pandas"
    os.environ["RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE"] = "1"
    
    ProgressBar.enable()
    ray.init()

    #ray.init(_temp_dir="/tmp/",
    #         #  _plasma_directory="./ray/"
    #         _memory=200 * 10**9,
    #         object_store_memory=20 * 10**9)

    assert ray.is_initialized() == True
    
    return None
```

```py
# Check that code is under main function
if __name__ == "__main__":
    import ray
    ray_init()
    
    import modin.config as cfg
    import modin.pandas as pd
        
    s = time.time()
    
    books_df, ratings_df, _ = load_data()
    main(books_df, ratings_df)
    
    e = time.time()
    print("Modin Loading Time = {}".format(e-s))
    
    ray.shutdown()
    assert ray.is_initialized() == False

    print('\nDone')
```

**Comment by devin-petersohn** [comment] 2022-01-27 23:05
Hi @codecypher thanks for the question!

There are a couple of things likely going on here: First, when you initialize Ray with the defaults, it does not use Modin's configurations. The fix for this would be to remove the line with `ray.init()` inside the `ray_init` function.

Once that's removed, Modin will initialize Ray for you when you call the `load_data` function, however the Ray startup time (sometimes up to 10-30 seconds or more if a lot of memory is requested) will be added to the time of your benchmark script for loading. 

Let's first try to remove the `ray.init` and see how that goes with Modin initializing. Are you able to try that and let me know?

Thanks again for the issue!

**Comment by mvashishtha** [comment] 2022-01-27 23:18
@codecypher please note that `MODIN_OUT_OF_CORE` was once part of Modin's API, but it is not any more. Please let us know if you find any Modin documentation asking users to use it: we should remove that documentation.

**Comment by codecypher** [comment] 2022-01-27 23:24
Thanks for the advice. However, I still get the same error message about _ArrrayMemory

**Comment by devin-petersohn** [comment] 2022-01-27 23:56
One thing I see from this error message: `numpy.core._exceptions._ArrayMemoryError: Unable to allocate 165 GiB for an array` 

It appears that the data that is

**Comment by devin-petersohn** [comment] 2022-01-27 23:58
(Sorry to close/reopen)

**Comment by codecypher** [comment] 2022-01-28 14:47
> One thing I see from this error message: `numpy.core._exceptions._ArrayMemoryError: Unable to allocate 165 GiB for an array`
> 
> It appears that numpy is trying to create a very large array in memory. How large are the files you're reading?

Yes I know. As I mentioned, I need to perform a pivot on a large dataset with 1.5M rows and then filter it. I was hoping that I could somehow use out of core memory (disk). Otherwise, I will have to write a lot of code to load data in chunks.

**Comment by codecypher** [comment] 2022-02-02 19:27
Today I went back and used groupby instead of pivot an it seems to be working. There are several steps before I apply piviot method, so I may have made a mistake along the way.

**Comment by mvashishtha** [comment] 2022-02-10 06:16
@codecypher I'm glad to hear that your code is working. Is it ok if we close this issue, then?

**Comment by codecypher** [comment] 2022-02-10 06:55
I do get various errors/warnings. Is that common?

There is one error/warning that I would like to ask about since I think it means I don’t have something configured correctly. I can share tomorrow. 

Jeff Holmes

On Feb 10, 2022, at 1:16 AM, Mahesh Vashishtha ***@***.***> wrote:

﻿
@codecypher I'm glad to hear that your code is working. Is it ok if we close this issue, then?

**Comment by devin-petersohn** [comment] 2022-02-17 18:51
@codecypher let us know if you're still running into an issue! Happy to continue helping!

**Comment by codecypher** [comment] 2022-02-17 19:16
I am running jupyterlab on Docker container on VM with ubuntu and it seems to be working. However, I am getting some warning messages that I could use some help resolving/understanding.

I see quite a few of the following for various Dataframe methods (not using print):

```
Error displaying widget: model not found
```

I am mainly concerned about the following two warnings labeled [1] and [2]:

```
[1]

UserWarning: Ray execution environment not yet initialized. Initializing...
To remove this warning, run the following python code before doing dataframe operations:

    import ray
    ray.init()

2022-02-10 21:35:18,897	WARNING services.py:1856 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67104768 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=0.26gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
```

```py
book_rating_count = (combine_book_rating.
     groupby(by = ['title'])['rating'].
     count().
     reset_index().
     rename(columns = {'rating': 'total_rating_count'})
     [['title', 'total_rating_count']]
    )
```

```
[2]
Exception in thread Thread-145:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/modin/core/execution/ray/generic/modin_aqp.py", line 54, in call_progress_bar
    futures = [x.oid for row in result_parts for x in row]
  File "/opt/conda/lib/python3.9/site-packages/modin/core/execution/ray/generic/modin_aqp.py", line 54, in <listcomp>
    futures = [x.oid for row in result_parts for x in row]
TypeError: 'PandasOnRayDataframePartition' object is not iterable
```

**Comment by devin-petersohn** [comment] 2022-02-28 14:29
@codecypher `[2]` looks like a bug in the progressbar, but from my testing, it did not interfere with the execution. If you are able, can you open a new issue for `[2]`? I can reproduce it locally.

`[1]` is a normal ray warning. Using `/tmp` is a bit slower (it is on disk), and if you want, you can follow the instructions in the warning when creating the docker container to increase the `/dev/shm` size. That should improve Modin's performance as well.

**Comment by vnlitvinov** [comment] 2022-08-29 16:15
@codecypher it seems that the original issue should now be solved by updating to newest Modin release.
Feel free to re-open if you disagree or open new issues when you find any.

**Closed by vnlitvinov** 2022-08-29 16:15 UTC
Labels: question ❓
