### ISSUE TITLE
Enhancement: Rewriting insert to use apply_func_to_select_indices instead of apply_func_to_select_indices_along_full_axis

### ISSUE THREAD

**Issue by williamma12** [modin-project/modin#670] opened 2019-06-11 21:38 UTC
Currently, `insert` uses `apply_along_select_indicies_full_axis`. However, this forces us to do essentially a full axis reduce, which is slow and could lead to transferring remote objects. With a bit of work, we should be able to rewrite `insert` to use `apply_along_select_indices` instead, which will be faster and not depend on any remote objects.

**Comment by manesioz** [comment] 2019-10-14 20:01
Hey, what's the status of issue? Need anyone to work on this?

**Comment by devin-petersohn** [comment] 2019-10-15 07:16
Hi @manesioz, this is still open.

The core issue at the moment is that we are forcing computation on `insert` when we don't need to. The easiest way to improve performance is to change the logic on the API layer `modin.pandas.dataframe.DataFrame.insert` to use `pd.concat` and `iloc`:

```python
df.insert(4, "new_cc", df["col1"] + df["col2"])
df = pd.concat([df.iloc[:, :3], pd.DataFrame(df["col1"] + df["col2"]), df.iloc[:, 4:]], axis=1)
```

These are functionally equivalent (outside of needing to update the column names) and the second one is significantly faster in Modin because it is not triggering any compute to insert the data.

If you can update the logic in `dataframe.py` to use the logic I posted above instead of the query compiler, that would fix this issue and improve performance of `insert` by ~10x.

**Comment by guor8lei** [comment] 2020-05-22 02:07
Hi @devin-petersohn , I've been playing around with this solving this issue and had a quick clarification question. I was wondering in your previous comment, when you wrote `pd.concat`, did you mean to have `modin.pandas.dataframe.DataFrame.insert` call the pandas `concat` method (using `to_pandas` and `from_pandas` to convert between Modin and pandas)? 

I was thinking about the other possible `concat` methods, but none of them seemed to work. Calling `modin.pandas.concat.concat` would lead to circular dependencies between `modin.pandas.dataframe` and `modin.pandas.concat`. I also tried calling `modin.backends.pandas.query_compiler.concat` but it didn't lead to any speedup.

Thanks!

**Comment by DayneSorvisto** [comment] 2021-03-20 21:25
Hi I'd like to attempt this one is it still open?

**Comment by mvashishtha** [comment] 2022-08-18 17:02
`insert` uses `apply_full_axis_select_indices` now.

**Comment by mvashishtha** [comment] 2022-08-18 17:02
Duplicate of #1772

**Closed by mvashishtha** 2022-08-18 17:02 UTC
Labels: good first issue 🔰, Performance 🚀
