### ISSUE TITLE
Add support for registering a custom accessor to allow user to extend DataFrames/Series

### ISSUE THREAD

**Issue by gsheni** [modin-project/modin#3044] opened 2021-05-05 18:25 UTC
- pandas supports adding custom methods directly onto a DataFrame/Series. [pandas docs](https://pandas.pydata.org/pandas-docs/stable/development/extending.html#registering-custom-accessors)
- This pandas feature allows users to extend a pandas DataFrame/Series, and add their own functionality. 
  - Two examples of libraries that use this are [geopands](https://github.com/geopandas/geopandas) and [woodwork](https://github.com/alteryx/woodwork)
- It would be cool to also have the ability to register custom accessor in a modin DataFrame/Series
```python
import modin.pandas as pd

@pd.api.extensions.register_dataframe_accessor("geo")
class GeoAccessor:
    def __init__(self, pandas_obj):
        self._validate(pandas_obj)
        self._obj = pandas_obj

    @staticmethod
    def _validate(obj):
        # verify there is a column latitude and a column longitude
        if "latitude" not in obj.columns or "longitude" not in obj.columns:
            raise AttributeError("Must have 'latitude' and 'longitude'.")

    @property
    def center(self):
        # return the geographic center point of this DataFrame
        lat = self._obj.latitude
        lon = self._obj.longitude
        return (float(lon.mean()), float(lat.mean()))

    def plot(self):
        # plot this array's data on a map, e.g., using Cartopy
        pass
```
```python
In [1]: ds = pd.DataFrame({"longitude": np.linspace(0, 10),
   ...:                    "latitude": np.linspace(0, 20)})
In [2]: ds.geo.center
Out[2]: (5.0, 10.0)
In [3]: ds.geo.plot()  # plots data on a map
```

**Comment by RehanSD** [comment] 2022-10-12 02:02
Duplicate of #3948

**Closed by RehanSD** 2022-10-12 02:02 UTC
Labels: new feature/request 💬, P2

**Comment by anmyachev** [comment] 2022-12-19 21:46
It looks like we need to add support for `pd.api.extensions.register_dataframe_accessor.register_dataframe_accessor`.
