### ISSUE TITLE
(apply_list_of_funcs pid=XXXX) Displaying sometimes when running Modin with Ray

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#4046] opened 2022-01-24 21:01 UTC
I have noticed this locally, and it even occurs in the quickstart: https://github.com/modin-project/modin/blob/master/examples/quickstart.ipynb

For some reason, Ray is printing something to stdout, but it doesn't always occur.

**Comment by mvashishtha** [comment] 2022-09-22 03:09
Duplicate of #4561

**Closed** 2022-09-22 03:10 UTC
Labels: Ray ⚡, P3
