### ISSUE TITLE
Where can I find documentation about Modin's implementation of NumPy?

### ISSUE THREAD

**Issue by zmbc** [modin-project/modin#6473] opened 2023-08-08 17:32 UTC
I saw this blog post: https://ponder.io/modin-0-19-numpy-welcome-to-the-modin-family/. And I see that some NumPy methods are implemented in a distributed way in Modin. But I don't see anything about it when I search the documentation. Is there a list somewhere of methods that are implemented, or the roadmap, or anything like that?

**Comment by anmyachev** [comment] 2023-08-08 17:38
Unfortunately we don't have documentation for modin.numpy module yet.

There is a issue for adding it https://github.com/modin-project/modin/issues/5734.

@RehanSD do you want to add something? Maybe an approximate timeline for adding?

**Comment by RehanSD** [comment] 2023-08-10 17:01
Hi @zmbc! We're currently working in adding the documentation (should be in within the week). In the meanwhile, if you have any questions, feel free to reach out to us on Slack!

**Comment by mvashishtha** [comment] 2023-08-17 13:49
Thank you again @zmbc for raising this issue. I'll close this issue in favor of #5734

**Comment by mvashishtha** [comment] 2023-08-17 13:49
duplicate of #5734

**Comment by mvashishtha** [comment] 2023-08-17 13:49
duplicate of #5734

**Comment by mvashishtha** [comment] 2023-08-17 13:50
Duplicate of #5734

**Closed by mvashishtha** 2023-08-17 13:49 UTC
Labels: question ❓, External
