### ISSUE TITLE
Exceptions in some cases when Series object is in groupby arguments

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1592] opened 2020-06-15 11:30 UTC
There are several examples when Series object is among groupby arguments and exception occurs

One came from the test that used in #1591. Here groupby is being made by list of Series: 
df[col].groupby([df[col]])

Another one can be seen eg in NYC taxi queries: df.groupby(["b", df["c"].dt.year]).agg({"a" : "size"})

In both cases there is 
TypeError: unhashable type: 'Series'
Uncaught exception. Entering post mortem debugging

which is triggered when we try to check whether groupby argument is in frame's columns, i.e. do smth like this:
all(obj in self._query_compiler.columns for obj in self._by)

**Comment by aregm** [comment] 2020-08-11 22:09
@Garra1980 A reproducer is needed for Modin in Ray.

**Comment by pyrito** [comment] 2022-08-18 21:35
Closing because there is not a reproducer for this.

**Closed by pyrito** 2022-08-18 21:35 UTC
Labels: bug 🦗, pandas.groupby
