### ISSUE TITLE
Group by can ignore multiple keys

### ISSUE THREAD

**Issue by goodwanghan** [modin-project/modin#1952] opened 2020-08-24 23:45 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **Modin version** (`modin.__version__`): 0.8.0
- **Python version**: 3.6.9
- **Code we can use to reproduce**:

```python
import pandas
import modin.pandas as pd

df=pd.DataFrame([[0, 1], [None, 2]], columns=["a","b"])
df["a_n"]=df["a"].isnull()
df["a_g"]=df["a"].fillna(0)
df.groupby(["a_n","a_g"]).min()
```

### Describe the problem

As you can see, it only uses a_n to group by

Interestingly, if you swap a_g and a_n, it works.
```python
df.groupby(["a_g","a_n"]).min()
```

**Comment by devin-petersohn** [comment] 2020-08-27 14:31
Hi @goodwanghan thanks for the report!

I can reproduce the issue you're seeing. It looks like the groupby is happening as expected, but the `as_index` isn't working for that case.

**Comment by YarShev** [comment] 2020-10-16 08:01
Hi @goodwanghan , I checked your workflow with both Modin (current master) and pandas (1.1.3) and got identical results.
```python
import modin.pandas as pd
import pandas

mdf=pd.DataFrame([[0, 1], [None, 2]], columns=["a","b"])
mdf["a_n"]=mdf["a"].isnull()
mdf["a_g"]=mdf["a"].fillna(0)
mdf.groupby(["a_n","a_g"]).min()
             a  b
a_n   a_g
False 0.0  0.0  1
True  0.0  NaN  2

pdf=pd.DataFrame([[0, 1], [None, 2]], columns=["a","b"])
pdf["a_n"]=pdf["a"].isnull()
pdf["a_g"]=pdf["a"].fillna(0)
pdf.groupby(["a_n","a_g"]).min()
             a  b
a_n   a_g
False 0.0  0.0  1
True  0.0  NaN  2
``` 

@goodwanghan , @devin-petersohn , if you don't mind, I will close the issue.

**Comment by devin-petersohn** [comment] 2020-10-19 14:55
Closing as this is resolved at the latest release.

**Closed by devin-petersohn** 2020-10-19 14:55 UTC
Labels: P0, bug :bug:
