### ISSUE TITLE
read_csv dtype categoricals not working

### ISSUE THREAD

**Issue by ecoughlan** [modin-project/modin#874] opened 2019-11-18 20:20 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.2
- **Modin installed from (source or binary)**: pip
- **Modin version**: 0.6.3
- **Python version**: 3.7.3
- **Exact command to reproduce**: See below

### Describe the problem

read_csv as below fails and gives
```
modin_result[0].dtype -> object
pandas_result[0].dtype -> CategoricalDtype(categories=['a', 'b'], ordered=False)
```
and then also calls such as `modin_result.select_dtypes(["object"])` fail

### Source code / logs

```python
import modin.pandas as pd
import pandas

pd.DataFrame(["a", "b"]).to_csv("tmp.csv", index = False)

modin_result = pd.read_csv("tmp.csv", dtype="category")
pandas_result = pandas.read_csv("tmp.csv", dtype="category")
assert modin_result.dtypes.equals(pandas_result.dtypes)
```

**Comment by devin-petersohn** [comment] 2019-11-18 20:49
Hi @ecoughlan thanks for posting!

I can reproduce the issue, and what you're observing is an artifact of very small files. Try the following with only a change to the size of the data created:

```python
import modin.pandas as pd
import pandas

pd.DataFrame([["a", "b"][i % 2] for i in range(1000000)]).to_csv("tmp.csv", index=False)
modin_result = pd.read_csv("tmp.csv", dtype="category")
pandas_result = pandas.read_csv("tmp.csv", dtype="category")
assert modin_result.dtypes.equals(pandas_result.dtypes)
```

In very small files when reading a CSV, we can unintentionally create empty partitions, which shouldn't affect the system. This is definitely a bug, but it's an artifact of extremely small files and how we read those files in-parallel. The solution is probably to just set a minimum limit on the number of bytes we read per-worker. Thanks for posting this, it's an edge case we should be supporting.

**Comment by ecoughlan** [comment] 2019-11-18 21:45
Thank you for the very quick reply. Maybe I made my example a bit too minimal (My actual use-case is a ~100MB csv), so I tried and the above still fails for me with
```python
pd.DataFrame([str(i) for i in range(10_000_000)]).to_csv("tmp.csv", index=False)
```
so maybe the partitions are not evenly sharded in my case? Also, I'm not even able to import them as string and then `astype("category")`, or even `df["0"] = pd.Series(df["0"].values, dtype="category"))` so not sure how I can work around this.

**Comment by devin-petersohn** [comment] 2019-11-19 17:50
Thanks @ecoughlan, I see the issue. It will take some time to get to the bottom of this one because we use pandas functionality to merge or combine the `dtypes` from the partitions. All of the partitions contain `CategoricalDtype`, when when merging them, it is classifying the merged `dtypes` as `object`.

**Closed** 2019-12-03 18:44 UTC
Labels: bug :bug:
