### ISSUE TITLE
Converting already categorical series using pd.Categorical results in AttributeError.

### ISSUE THREAD

**Issue by meijiu** [modin-project/modin#4623] opened 2022-06-30 21:43 UTC
### System information
OS X 11.6.4
Modin version '0.15.2'
Python 3.9.12*:

### Describe the problem
Calling `modin.pandas.Categorical` on a `modin.pandas.Series` which is already a `category` dtype results in `AttributeError: 'Series' object has no attribute '_codes'`. Might be a trivial issue, but I'm reporting since the behavior is unexpected.

### Source code / logs
```
import modin.pandas as pd
s = pd.Series([1,2,3,4], dtype='category')
x = pd.Series([1,2,3,4], dtype='int')

# this won't fail
pd.Categorical(x, categories=None, ordered=True)

# this will
pd.Categorical(s, categories=None, ordered=True)

**Comment by naren-ponder** [comment] 2022-07-01 15:46
Duplicate of #4275. `modin.pandas.Series` object does not have a `_codes` attribute, which pandas `CategoricalDType` code expects when reassigning a categorical to another categorical. Referencing this to the broader empty dataframe issue #4605.

**Closed by naren-ponder** 2022-07-01 15:46 UTC
