### ISSUE TITLE
BUG: Depreciation Warning with Ray 2.0 for pd.read_parquet when installing Modin from Github

### ISSUE THREAD

**Issue by benaurelschill** [modin-project/modin#5090] opened 2022-10-05 21:12 UTC
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import pandas
import modin.pandas as pd

pdf = pandas.DataFrame({"a": [0]})
pdf.to_parquet("/tmp/for_deprecation_warning.parquet")
print(pd.read_parquet("/tmp/for_deprecation_warning.parquet"))
```

### Issue Description

Just wanted to give you guys a heads up that for reading in parquet files ray will throw a deprecation warning for every read parquet function that is called when I install modin from the Github Branch and use it with Ray 2.0.

### Expected Behavior

No warnings throwing

### Error Logs

<details>

(_apply_func pid=482969) FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
(_apply_func pid=482969) FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 7871c7bc5adeeaca9b6fc4b88482be8b18333faa
python           : 3.9.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.14.0-70.26.1.el9_0.x86_64
Version          : #1 SMP PREEMPT Fri Sep 2 16:07:40 EDT 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

</details>

**Comment by mvashishtha** [comment] 2022-10-06 00:04
@benaurelschill thank you for reporting this bug. I really appreciate that you caught a bug that, AFAICT, only appeared on the latest commit to Modin. I edited your code so it's a complete reproducer.

I'm investigating what it will take to fix the bug.

**Comment by benaurelschill** [comment] 2022-10-06 00:10
Hey @mvashishtha Thanks for the quick response. I have just seen that somebody opened a similar issue and is already working on this. #5092 So i think we can close this issue.

**Comment by mvashishtha** [comment] 2022-10-06 00:12
Duplicate of #5092

**Closed by mvashishtha** 2022-10-06 00:12 UTC
Labels: bug 🦗, Triage 🩹
