### ISSUE TITLE
`df.loc` on range-like indexers returns an extra item compared with pandas behaviour

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#4497] opened 2022-05-25 16:30 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version** (`modin.__version__`): 60518ca
- **Python version**: 3.8.13
- **Code we can use to reproduce**:
```python
import pandas
import modin.pandas as pd
from modin.pandas.test.utils import create_test_dfs

md_df, pd_df = create_test_dfs({"a": [1, 2, 3, 4, 5, 6]})

md_res = md_df.loc[range(2), :]
pd_res = pd_df.loc[range(2), :]
print(f"Modin.loc:\n{md_res}")
print(f"Pandas.loc:\n{pd_res}")
```

Output:
```
Modin.loc:
   a
0  1
1  2
2  3
Pandas.loc:
   a
0  1
1  2
```

### Describe the problem
`.loc` on a range-like indexer seems return rows that matches the passed indexer including its upper bound (return indices `0, 1, 2` for a range `0-2`). The pandas itself appears to not return an upper bound, so we have a missmatch here.

For range-like indexers, a positions of rows to take by `loc` are defined here:
https://github.com/modin-project/modin/blob/60518ca737bf13cc37c8f1269985dcbb68dad4c7/modin/pandas/indexing.py#L795-L798
The `slice_indexer` function returns a `[0, 1, 2]` positions for `range(0, 2)` input.

**Comment by mvashishtha** [comment] 2023-03-02 11:40
Duplicate of #5702

**Closed by mvashishtha** 2023-03-02 11:40 UTC
Labels: pandas concordance 🐼, P2
