### ISSUE TITLE
Boolean masking with a Series works incorrect on `BaseOnPython` execution

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3701] opened 2021-11-18 12:26 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version** (`modin.__version__`): 8d67cd3a467d1eb2262898f6f5e2cf159c27d7b0
- **Python version**: Any
- **Code we can use to reproduce**:
```python
from modin.conftest import set_base_execution

import modin.pandas as pd
import pandas

pd_df = pandas.DataFrame({"a": [1, 2, 3, 4], "b": [5, 6, 7, 8], "c": [9, 10, 11, 12]})
pd_bool_mask = pd_df["a"] > 2

print(f"Pandas:\n{pd_df[pd_bool_mask]}\n")

df = pd.DataFrame(pd_df)
bool_mask = pd.Series(pd_bool_mask)

print(f"PandasOnRay:\n{df[bool_mask]}\n")

# Set `BaseOnPython` execution
set_base_execution()

df = pd.DataFrame(pd_df)
bool_mask = pd.Series(pd_bool_mask)

print(f"BaseOnPython:\n{df[bool_mask]}\n")

```

Output:
```
Pandas:
   a  b   c
2  3  7  11
3  4  8  12

PandasOnRay:
   a  b   c
2  3  7  11
3  4  8  12

BaseOnPython:
     a   b   c
0  NaN NaN NaN
1  NaN NaN NaN
2  3.0 NaN NaN
3  4.0 NaN NaN
```

### Describe the problem
The reason for such behaviour is that [`BaseQueryCompiler`](https://github.com/modin-project/modin/blob/8d67cd3a467d1eb2262898f6f5e2cf159c27d7b0/modin/core/storage_formats/base/query_compiler.py) treats any query-compiler-like input as a DataFrame inside [`getitem_array`](https://github.com/modin-project/modin/blob/8d67cd3a467d1eb2262898f6f5e2cf159c27d7b0/modin/core/storage_formats/base/query_compiler.py#L1962-L1963). The presented behaviour of the `BaseOnPython` is expected for DataFrame-like boolean mask, but not for Series.

**Comment by mvashishtha** [comment] 2022-06-30 17:56
This looks like a duplicate of #4482, which is fixed. I confirmed that the reproducer in the first comment on this issue now works correctly in `BaseOnPython`.

**Comment by mvashishtha** [comment] 2022-06-30 17:56
Duplicate of #4482

**Closed by mvashishtha** 2022-06-30 17:56 UTC
Labels: bug 🦗
