### ISSUE TITLE
PERF: infer length/width in binary_operation?

### ISSUE THREAD

**Issue by jbrockmendel** [modin-project/modin#4738] opened 2022-07-29 21:46 UTC
IIUC PandasDataframePartitionManager.binary_operation is used for calling arithmetic/comparison ops partition-by-partition, and the resulting partitions will have the same shapes as the inputs.  If this is accurate, then we should be able to have the result partitions copy any cached length/width info on the inputs, right?

**Comment by jbrockmendel** [comment] 2022-08-01 19:21
@mvashishtha I understand copartitioning may occur.  But _after_ co-partitioning, aren't the partition-by-partition operations shape-preserving?  That's why im suggesting they be preserved in binary_operation, not in binary_op.

**Comment by mvashishtha** [comment] 2022-08-01 19:27
@jbrockmendel I think that `binary_op` is doing its best it to preserve the sizes caches at the `PandasDataframe` level. I think you might be thinking of the caches at the partition level? We do lose those when we apply a function per partition in `binary_operation` here:

https://github.com/modin-project/modin/blob/88c3c33cf9b8aab5f5b7077555bea9f2d8466534/modin/core/dataframe/pandas/partitioning/partition_manager.py#L1290-L1293

and I think you're correct that the binary operations at that point should preserve shape.

As I mentioned [here](https://github.com/modin-project/modin/issues/4732#issuecomment-1199820703), there are many places like that in Modin, but I doubt we'd get much marginal utility from preserving caches at the partition level in addition to the overall dataframe level. Should we follow up on #4732, where you mentioned that you had an example where losing the partition shape cache was hurting performance?

**Comment by mvashishtha** [comment] 2022-08-01 21:26
@jbrockmendel is this bug a dupe of #4727?

**Comment by vnlitvinov** [comment] 2022-08-02 09:15
> @mvashishtha I understand copartitioning may occur. But _after_ co-partitioning, aren't the partition-by-partition operations shape-preserving? That's why im suggesting they be preserved in binary_operation, not in binary_op.

I might be missing some context, but I would like to add that co-partitioning produces a copy of the right operand which is discarded after the operation.

I mean, if you do e.g. `df3 = df1 + df2`, then `df3` should have similar shape to `df1`, but `df2` will still have its original shape even if we repartitioned it to perform the binary operation.

**Comment by jbrockmendel** [comment] 2022-08-02 15:04
@YarShev i think you said you confirmed this optimization is correct but found it didn't make a huge difference in the use case you were profiling?  worth making a PR?

**Comment by YarShev** [comment] 2022-08-02 20:39
Yes, I didn't see any perf gain from that by profiling our use case so I don't think it is worth making a PR for now.

**Comment by YarShev** [comment] 2024-03-20 09:08
We do preserve lengths and widths for a binary operation so closing this issue. Feel free to reopen if needed. https://github.com/modin-project/modin/blob/7c835a2761ede41d402c1febd29826c1d0b9512f/modin/core/dataframe/pandas/dataframe/dataframe.py#L3752-L3753

**Closed by YarShev** 2024-03-20 09:08 UTC
Labels: Performance 🚀, P2
