### ISSUE TITLE
Different behavior between modin and pandas for operation with loc

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#4616] opened 2022-06-28 19:55 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

import modin.pandas as pd

df = pd.DataFrame(
{'a': ['a_1', 'a_2'],
 'b': ['b_1', 'b_2'],},
 index=['row1', 'row2'])

df.loc['row1', 'd'] = 'dd1'
df.loc['row2', 'd'] = 'dd2'

### Describe the problem

For the code above modin gives 

Traceback (most recent call last):
  File "/localdisk/izamyati/tpcx-ai-v1.0.2/../modin/loc_issue.py", line 10, in <module>
    df.loc['row1', 'd'] = 'dd1'
  File "/localdisk/izamyati/modin/modin/pandas/indexing.py", line 718, in __setitem__
    row_lookup, col_lookup = self._compute_lookup(row_loc, col_loc)
  File "/localdisk/izamyati/modin/modin/pandas/indexing.py", line 845, in _compute_lookup
    raise KeyError(missing_labels)
KeyError: array(['d'], dtype='<U1')

while pandas just creates new column

**Comment by mvashishtha** [comment] 2022-06-28 19:57
@Garra1980 Thanks for reporting this issue. It looks like a duplicate of #3764. I'm going to close this one as a duplicate for now.

**Comment by mvashishtha** [comment] 2022-06-28 19:58
Duplicate of #3764

**Closed by mvashishtha** 2022-06-28 19:58 UTC
