### ISSUE TITLE
read_csv with OmniSci backend incorrectly handles multilines if skiprows is present

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2904] opened 2021-03-18 12:45 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: c1ad0997fa0468efb980731a5212f28e604a7575
- **Python version**: 3.7.10
- **Code we can use to reproduce**:
```
import os

os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_BACKEND"] = "omnisci"

import modin.pandas as pd
from modin.pandas.test.utils import df_equals
import pandas

df_modin = pd.read_csv("modin/pandas/test/data/newlines.csv", skiprows=4)
df_pandas = pandas.read_csv("modin/pandas/test/data/newlines.csv", skiprows=4)

print(df_modin)
print(df_pandas)

df_equals(df_pandas, df_modin)
```

### Source code / logs

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    df_modin = pd.read_csv("modin/pandas/test/data/newlines.csv", skiprows=4)
  File "modin/modin/pandas/io.py", line 134, in read_csv
    return _read(**kwargs)
  File "modin/modin/pandas/io.py", line 60, in _read
    pd_obj = EngineDispatcher.read_csv(**kwargs)
  File "modin/modin/data_management/factories/dispatcher.py", line 104, in read_csv
    return cls.__engine._read_csv(**kwargs)
  File "modin/modin/data_management/factories/factories.py", line 87, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "modin/modin/experimental/engines/omnisci_on_ray/io.py", line 215, in read_csv
    convert_options=co,
  File "pyarrow/_csv.pyx", line 714, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 1 columns, got 4
```

**Comment by amyskov** [comment] 2021-03-19 14:56
Corresponding issue was created in the Arrow Jira ([ticket](https://issues.apache.org/jira/browse/ARROW-12025)).

**Comment by amyskov** [comment] 2021-04-26 16:20
According to PyArrow documentation `skip_rows` parameter doesn't guarantee correctness of skipping data rows (only header rows), so we need to handle multilines in Modin.

**Comment by RehanSD** [comment] 2022-10-11 16:52
Hi @amyskov! Is this issue still present? @vnlitvinov @YarShev - tagging Intel folks since this is OmniSci!

**Comment by Garra1980** [comment] 2022-10-11 17:18
it's better to ask @AndreyPavlenko to check

**Comment by AndreyPavlenko** [comment] 2022-10-11 17:48
The code above works for me. Closing the issue as not reproducible.

**Closed by AndreyPavlenko** 2022-10-11 17:48 UTC
Labels: bug 🦗, P2, OmniSci
