### ISSUE TITLE
modin astype function converts object dtype to "string"

### ISSUE THREAD

**Issue by c3-qiangyao** [modin-project/modin#4340] opened 2022-03-21 19:55 UTC
### System information
ray 1.9.2
modin 0.12.0
python 3.9.7

### Describe the problem

If we have a modin dataframe of string columns, the dtypes would be object. If we want to create a new column by applying `astype(str)` function on the string column, the new column would be of dtype `<U0`, instead of `object` that is returned in pandas `astype`.
### Source code / logs

```
import modin.pandas as pd
df = pd.DataFrame(data={'a':[1,2,3],'b':['hello','world','modin']})
df.dtypes
---
a     int64
b    object
dtype: object
=============
df['new'] = df['b'].astype(str)
df.dtypes
---
a       int64
b      object
new       <U0
dtype: object
```
If we do the same thing with pandas, the `new` column would be of dtype `object`.

**Comment by mvashishtha** [comment] 2022-03-21 19:59
@c3-qiangyao thank you for reporting this! This is known issue #4316 . We hope to fix the bug soon.

**Comment by mvashishtha** [comment] 2022-03-21 19:59
Duplicate of #4316

**Comment by devin-petersohn** [comment] 2022-03-22 18:56
Closing as duplicate.

**Closed by devin-petersohn** 2022-03-22 18:56 UTC
Labels: duplicate ♻️
