### ISSUE TITLE
ValueError: bins must be monotonically increasing or decreasing

### ISSUE THREAD

**Issue by Deom23** [modin-project/modin#866] opened 2019-11-13 14:08 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin installed from (source or binary)**: pip install modin[dask]
- **Modin version**: 0.6.2
- **Python version**: 3.6
- **Exact command to reproduce**:

### Describe the problem
I was going to test modin out on Windows and am receiving this ValueError when simply trying to do a .loc[] statement. 

simdata_hh.loc[simdata_hh['first_year'] == 2019,:]

**Comment by devin-petersohn** [comment] 2019-11-13 17:22
Hi @Deom23, thanks for reporting!

This is a duplicate of #852, and was fixed in #858. We haven't released a version that includes this patch just yet, but if you'd like to use the latest Modin master branch, there are instructions on how to do this in the documentation: https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch

**Comment by devin-petersohn** [comment] 2019-11-13 17:22
Closing as duplicated

**Closed by devin-petersohn** 2019-11-13 17:22 UTC
Labels: duplicate :recycle:
