### ISSUE TITLE
``shift`` doesn`t work correctly at MODIN_STORAGE_FORMAT=omnisci

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#3841] opened 2021-12-10 21:43 UTC
When I run at MODIN_STORAGE_FORMAT=omnisci:
```
import pandas
import modin
import modin.pandas as pd
from modin.utils import to_pandas
from modin.pandas.test.utils import test_data_values
data = test_data_values[0]
modin_series = pd.Series(data)
data_column_length = len(data[next(iter(data))])
modin_series.index = np.arange(2, data_column_length + 2)
modin_res = modin_series.shift(periods=1)
```
I have error:
```
pyarrow.lib.ArrowInvalid: Schema at index 1 was different:
F___reduced__: int64
vs
F___reduced__: double
```

**Comment by vnlitvinov** [comment] 2022-08-26 14:02
@modin-project/modin-omnisci  could someone please check if this still happens?

**Comment by AndreyPavlenko** [comment] 2022-10-26 19:19
I'm unable to reproduce this issue. Closing as not reproducible.

**Closed** 2022-10-27 07:25 UTC
Labels: bug 🦗, pandas concordance 🐼, P2, OmniSci
