### ISSUE TITLE
pd.dataframe.at won't work in modin

### ISSUE THREAD

**Issue by cinnqi** [modin-project/modin#4111] opened 2022-01-29 09:56 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Modin version** (`modin.__version__`):0.13
- **Python version**:3.8
- **Code we can use to reproduce**:

### Describe the problem

I am trying to insert an object into a cell of data frame, by using pd.dataframe.at(index,'row', object). 
it works in pandas but not in modin. 

### Source code / logs

File "compare_modin.py", line 98, in <module>
    df_record.loc[i,'mainsnaks'] = mainsnaks  
  File "/home/chengxi/.local/lib/python3.8/site-packages/modin/pandas/indexing.py", line 742, in __setitem__
    super(_LocIndexer, self).__setitem__(
  File "/home/chengxi/.local/lib/python3.8/site-packages/modin/pandas/indexing.py", line 412, in __setitem__
    item = self._broadcast_item(row_lookup, col_lookup, item, to_shape)
  File "/home/chengxi/.local/lib/python3.8/site-packages/modin/pandas/indexing.py", line 475, in _broadcast_item
    raise ValueError(
ValueError: could not broadcast input array from shape (631,) into shape (1, 1)

**Comment by devin-petersohn** [comment] 2022-01-29 15:34
Hi @cinnqi thanks for reporting!

It looks like the error happens at `loc` instead of `at` (although they are quite similar). In this line:

```python
df_record.loc[i,'mainsnaks'] = mainsnaks
```

What is `i` and `mainsnaks`? It looks like `i` is a row label (maybe an integer) and `mainsnaks` is a 1D Series or array. If you could provide something I can run locally to reproduce that would really help us. Thanks again for reporting!

**Comment by cinnqi** [comment] 2022-01-30 10:41
yes, I tried both at and loc, and none of them worked. i is a row label indeed and mainsnaks is a list of objects, format below
```
  [
      {
        "snaktype":"value",
        "property":"P1064",
        "datavalue":{
          "value":{
            "entity-type":"item",
            "numeric-id":3319112,
            "id":"Q3319112"
          },
          "type":"wikibase-entityid"
        },
        "datatype":"wikibase-item"
      },
      {
        "snaktype":"value",
        "property":"P31",
        "datavalue":{
          "value":{
            "entity-type":"item",
            "numeric-id":728937,
            "id":"Q728937"
          },
          "type":"wikibase-entityid"
        },
        "datatype":"wikibase-item"
      },
      ........
    ]
```
I am trying to insert the mainsnaks to one indicated datafram cell. Actually, I don't understand why it can work in pandas.

**Comment by mvashishtha** [comment] 2022-01-31 18:11
@cinnqi thanks for describing the data. Could you please also add the line of your code that causes the error?

@devin-petersohn I think this might be another case of someone trying to use `loc` to append to a dataframe, as in #3764.

**Comment by devin-petersohn** [comment] 2022-02-16 21:12
@mvashishtha Yes, it does appear related

**Comment by mvashishtha** [comment] 2022-08-17 01:22
@cinnqi because you haven't posted any more information, I'm closing this issue. Hopefully we can solve your bug by fixing #3764. Please comment here if you need more help.

**Closed by mvashishtha** 2022-08-17 01:22 UTC
Labels: bug 🦗
