### ISSUE TITLE
FEAT: read_csv from http URL

### ISSUE THREAD

**Issue by matthewdeng** [modin-project/modin#3170] opened 2021-06-22 01:38 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS Big Sur 11.2.3
- **Modin version** (`modin.__version__`): 0.10.0
- **Python version**: 3.7.10
- **Code we can use to reproduce**:
```python
import ray
import modin.pandas as pd


FILE_URL = "https://archive.ics.uci.edu/ml/machine-learning-databases/" \
           "00280/HIGGS.csv.gz"
ray.init()
data = pd.read_csv(FILE_URL)
```

Same thing happens if I try to read from the unzipped CSV on my local machine:
```python
import ray
import modin.pandas as pd


FILE_PATH = "~/data/HIGGS.csv"
ray.init()
data = pd.read_csv(FILE_PATH)
```

### Describe the problem

I'm running a very simple script with just a `read_csv` call, but it is defaulting to `pandas` implementation and not being parallelized.

### Source code / logs

```bash
python read_csv.py        
2021-06-21 18:21:00,783	INFO services.py:1274 -- View the Ray dashboard at http://127.0.0.1:8265
UserWarning: Parameters provided defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
```

In the long run, I am trying to run this remotely on an AWS cluster (using `ray.client.connect`), as well as provide the `names` parameter into `read_csv`. To reduce the problem scope I have simplified the provided code example to use `ray.init()` and removed the `names` parameter, but am still able to reproduce the same behavior defaulting to `pandas`.

**Comment by amyskov** [comment] 2021-06-22 10:32
Hi @matthewdeng , thanks for reporting!
The first reproducer you provided outputs `defaulting to pandas` message because Modin `read_csv` doesn't support URL based inputs, in order to avoid defaulting-to-pandas behavior you can use AWS S3 bucket.
Regarding the second reproducer with local file - i have some problems with reproducing it on my side, see example below (computations are parallelized and no warnings are present):
```
import ray
import modin.pandas as pd
import pandas
from timeit import default_timer as timer

FILE_PATH = "HIGGS.csv"
col_names = [f"col{x}" for x in range(29)]

ray.init()

t0 = timer()
data = pd.read_csv(FILE_PATH, names=col_names)
t_modin = timer() - t0
print("Modin time:", t_modin)

t0 = timer()
data = pandas.read_csv(FILE_PATH, names=col_names)
t_pandas = timer() - t0
print("pandas time:", t_pandas)

Output:
2021-06-22 05:17:15,168 INFO services.py:1274 -- View the Ray dashboard at http://127.0.0.1:8265
Modin time: 14.894548802869394
pandas time: 57.876808954868466
```

So can you provide more details about the second reproducer (is it any additional code not presented in the reproducer, etc.)?

**Comment by matthewdeng** [comment] 2021-06-23 04:32
@amyskov thank you for looking into this, I was able to confirm that I could read from an S3 bucket (where the file is unzipped).

For the problem with reading from my local machine, I was able to fix the problem by expanding the `~` into the home directory.

```python
import ray
import modin.pandas as pd
import os

FILE_PATH = "~/data/HIGGS.csv"
path = os.path.expanduser(FILE_PATH)
ray.init()
data = pd.read_csv(path)
```

**Comment by devin-petersohn** [comment] 2021-06-23 14:18
@matthewdeng I am going to reopen this as a feature request for distributed https URL support so we can track it.

**Comment by mvashishtha** [comment] 2022-07-29 04:59
Duplicate of #4657

**Closed by mvashishtha** 2022-07-29 04:59 UTC
Labels: new feature/request 💬
